### ISSUE TITLE
init-functions not called during inner chunk initialisation

### ISSUE THREAD

**Issue by lionel-** [polymode/polymode#101]
One problem with the R help examples section is that I have `(setq show-trailing-whitespace t)` hooked in all prog modes. This creates a really messy output as R help files contain lots of trailing whitespace.

I could deal with this with my config but it probably makes sense to set this variable to nil from polymode. I'm trying to do this by adding setting the `init-functions` slot of `pm-inner/ess-help+R`:

``` lisp
:init-functions '((lambda () (setq-local show-trailing-whitespace nil))))
```

However this doesn't get called because of the `unless` check here:

``` lisp
(defun pm--run-init-hooks (object &optional emacs-hook)
  (unless pm-initialization-in-progress
    (when emacs-hook
      (run-hooks emacs-hook))
    (pm--run-hooks object :init-functions)))
```

Is this intended?

Also it'd make sense to have a `init-vars` slot that accept an alist of variables and values to do this sort of configuration.

**Comment by lionel-** [comment]
Maybe polymode is not the way to go for R help, it seems to disrupt `quit-window` behaviour. I notice that `q` works as intended up until I move the cursor inside the examples chunk. Then when I go back to another section and try to quit the window, nothing happens.

**Comment by vspinu** [comment]
> Maybe polymode is not the way to go for R help, it seems to disrupt quit-window behaviour.

:) It's a different mode altogether. If you want to be able to edit the code (which I do) then you have to make this tradeoff. 

> I could deal with this with my config but it probably makes sense to set this variable to nil from polymode. 

Not really. This should be fixed on ESS side. 

> However this doesn't get called because of the unless check here:

That check is there to allow dispatch from inherited methods. That is, parent methods should not run this hook multiple times. Eventually it should be running; it's a bug if it doesn't.

**Comment by vspinu** [comment]
> his should be fixed on ESS side. 

I have just done that.

**Comment by lionel-** [comment]
>  It's a different mode altogether

I mean, `quit-window` stops working not only in the R chunks but even when I go back to the help chunk. Or is it just on my config?

> This should be fixed on ESS side.

Oh, of course.

> I have just done that.

Thanks!

**Comment by lionel-** [comment]
That may be due to the internal window history that Emacs keep track of.

The weird thing is that quit-window moves the cursor to where it was before I enter the R chunk.

**Comment by vspinu** [comment]
> I mean, quit-window stops working not only in the R chunks but even when I go back to the help chunk. 

I never noticed this because I always use "k" in help buffers. Indeed, it's a bug.
