### ISSUE TITLE
polymode-weave.el:Warning: Unused lexical variable `scoped-class`

### ISSUE THREAD

**Issue by nachti** [polymode/polymode#106]
Using the github version of polymode, starting GNU Emacs 24.3.1 gives a warning:
`~/.emacs.d/site-lisp/polymode/polymode-weave.el:Warning: Unused lexical variable 'scoped-class'`, which is annoying. Compiling `polymode-weave.el` to `polymode-weave.elc` (not trouble-free) _solved_ the problem. I found the hint here: https://github.com/emacs-helm/helm/issues/603

~g

**Comment by vspinu** [comment]
Well, just like pointed in that issue, eieio underwent major refactoring after 24.3.1 and there are many bugs in that emacs version which no-one will ever be fixing. Polymode seem to work with 24.3 but it's explicitly not supported (see the note on the main github page).

**Comment by vspinu** [comment]
After the rewrite polymode supports emacs 25+.  Time helps ;)
