### ISSUE TITLE
Inconsistent Matcher Function Behaviour

### ISSUE THREAD

**Issue by Xaldew** [polymode/polymode#107]
Hello,

I started some work on a Python + ReST docstring poly-mode and so far I've come up with this:

``` emacs-lisp

  (defvar ReST-head-regexp
    (concat "^[ \t]*\\(def\\|class\\).*:" ;; Match start of function/class.
            "\\(?:\n\\)\\{1,\\}"          ;; Match at least 1 newline.
            "[ \t]*"                      ;; Match optional whitespace.
            "u?\\(\"\"\"\\|\'\'\'\\)")    ;; Match start of docstring.
    "Regexp for matching the `head' of a ReST inner mode.")

  (defvar ReST-tail-regexp
    "\\(\"\"\"\\|\'\'\'\\)"
    "Regexp for matching the `tail' of a ReST inner mode.")

  (defun ReST-match-head (ahead)
    (pm--default-matcher ReST-head-regexp ahead))

  (defun ReST-match-tail (ahead)
    (pm--default-matcher ReST-tail-regexp ahead))

  (defcustom pm-host/python
    (pm-bchunkmode "python"
                   :mode 'python-mode
                   :font-lock-narrow nil)
    "Python host chunkmode"
    :group 'hostmodes
    :type 'object)

  (defcustom pm-inner/ReST
    (pm-hbtchunkmode "ReST"
                     :mode 'rst-mode
                     :head-reg ReST-head-regexp
                     :tail-reg ReST-tail-regexp
                     :head-mode 'host
                     :tail-mode 'host)
    "ReST inner chunk."
    :group 'innermodes
    :type 'object)
  (defcustom pm-poly/python+ReST
    (pm-polymode-one "python+ReST"
                     :hostmode 'pm-host/python
                     :innermode 'pm-inner/ReST)
    "Python and ReST polymode."
    :group 'polymodes
    :type 'object)
  (define-polymode poly-python-mode pm-poly/python+ReST))

```

This works rather well, but I noticed some issues when using it together with
`yasnippet`. When some snippets entered and attempted to leave the docstring,
`yasnippet` would get stuck. So I figured I could fix that inside a matcher
function and only enable a chunk if it did not overlap with the region
`yasnippet` was working on.

The problem is, when I try to replace `head-reg`/`tail-reg` with the default
matcher functions above (`pm-default-matcher`), the poly-mode breaks down:

``` emacs-lisp

  (defcustom pm-inner/ReST
    (pm-hbtchunkmode "ReST"
                     :mode 'rst-mode
                     :head-reg #'ReST-match-head
                     :tail-reg #'ReST-match-tail
                     :head-mode 'host
                     :tail-mode 'host)
    "ReST inner chunk."
    :group 'innermodes
    :type 'object)

```

I'm not entirely sure why but I suspect it has something to do with part of the
`tail-regexp` is present in the `head-regexp`.

Here's two images with `pm-debug-mode` enabled that illustrates the problem:
# Using Regexps

![poly_regexp](https://cloud.githubusercontent.com/assets/1394310/18618401/597224dc-7de6-11e6-91c7-d296a4b96fd5.gif)
# Using Default Matcher

![poly_matcher](https://cloud.githubusercontent.com/assets/1394310/18618403/5f52f76e-7de6-11e6-99a7-ac1b354ae126.gif)

**Comment by vspinu** [comment]
Can you provide a clear text example of your file? 

> So I figured I could fix that inside a matcher function and only enable a chunk if it did not overlap with the region yasnippet was working on.

I am not quite following. You didn't provide this code above. Your `default-matcher` examples are for illustration only, right? Otherwise I don't see how it can help with yas problem. 


In any case I think it would be good if you can open a dedicated issue for yas. Then we can try to figure out where it is coming in the first place, and maybe fix it more generally.

**Comment by Xaldew** [comment]
Hello!

Here's a clear text Python example with a few more blocks that I used to test
the initial code:

```python

#!/usr/bin/env python

import sys


class KeycodeParser:
    """Parser for X11 key codes.

    .. Class Attributes:
    :cvar: modifier_map:
    :cvar: keycode_map:

    .. Class Types:
    :vartype: modifier_map:
    :vartype: keycode_map:

    """
    def __init__(self):
        """This is another test."""
        for i in range(5):
            print "Hello, world!"


def main(a, b):
    """This is a simple test function.

    .. Keyword Arguments:
    :param a: A test argument.
    :param b: A test argument.

    .. Types:
    :type a: Arbitrary.
    :type b: Arbitrary.

    .. Returns:
    :returns: 0 if successful. Otherwise non-zero.
    :rtype: An integer.

    """
    test = """This is a test."""
    test1 = '''Not a docstring.'''
    return 0


if __name__ == '__main__':
    sys.exit(main())
```


Basically, if I use this code to define the inner chunk:


```emacs-lisp

(defcustom pm-inner/ReST
    (pm-hbtchunkmode "ReST"
                     :mode 'rst-mode
                     :head-reg ReST-head-regexp
                     :tail-reg ReST-tail-regexp
                     :head-mode 'host
                     :tail-mode 'host)
    "ReST inner chunk."
    :group 'innermodes
    :type 'object)

```

Then everything seems to work well, all chunk boundaries are where they're
supposed to be. (Except the `yas` issue, but lets ignore that for now). This
would correspond to the *Using Regexp* image above.


Now, I wanted to add some custom behavior that plain regexps couldn't, so I
started by using `pm-default-matcher` to try things out with the code below:


```emacs-lisp

(defun ReST-match-head (ahead)
  (pm--default-matcher ReST-head-regexp ahead))

(defun ReST-match-tail (ahead)
  (pm--default-matcher ReST-tail-regexp ahead))


(defcustom pm-inner/ReST
  (pm-hbtchunkmode "ReST"
                   :mode 'rst-mode
                   :head-reg #'ReST-match-head
                   :tail-reg #'ReST-match-tail
                   :head-mode 'host
                   :tail-mode 'host)
  "ReST inner chunk."
  :group 'innermodes
  :type 'object)

```

Using this code gives the erroneous chunk behavior seen in the *Using Default
Matcher* image.

As far as I can tell, the `pm-default-matcher` is supposed to provide a behavior
equivalent to that of using plain regexps but something seems to go wrong in
this case. Or is this equivalence just a false assumption on my part?

**Comment by vspinu** [comment]
Works as expected in my tests.
