### ISSUE TITLE
While editing Rmd files in evil-mode the 'f' key jumps me back to a point in insert mode

### ISSUE THREAD

**Issue by roryk** [polymode/polymode#108]
Hi @vspinu,

When editing Rmd files in evil-mode sometimes I can get in a state where the `f` key jumps me back to somewhere else in the buffer, even when I am in insert mode. It always jumps back to the same place once it starts doing that, every time I press the f key it jumps me back. If I kill the buffer and reload the file, it is fine. I have no idea how to reproduce this behavior, it seems to happen randomly. Sorry for the crappy issue, I'm posting this because hopefully other folks will run into the same behavior and have more of a clue about why it is happening.

**Comment by roryk** [comment]
When it starts doing this behavior, in insert mode it tries to search via `regexp i-search` when I press the 'f' key.

**Comment by vspinu** [comment]
What is f bound to in insert mode? Could you try to edebug that command and pinpoint where the jump occurs?

**Comment by vspinu** [comment]
I haven't tested it myself but I am reasonably confident this one is fixed. Point should no longer jump around under any circumstances. Feel free to re-open if you still see it.

**Comment by roryk** [comment]
Hi @vspinu, sorry for not closing this out myself. It is fixed for sure.
