### ISSUE TITLE
YAML syntax highlighting in Rmd file

### ISSUE THREAD

**Issue by jdtonkin** [polymode/polymode#114]
I'm struggling to get YAML highlighting working in .Rmd files. I have (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode)) in my init file and that works for the rest of the document but YAML syntax isn't highlighted. Is there a version that includes YAML. e.g. poly-markdown+r+yaml-mode? Thanks!

**Comment by vspinu** [comment]
YAML needs to be added to markdown polymode directly. I think it's a common requirement these days.
