### ISSUE TITLE
Problems after opening second R noweb file

### ISSUE THREAD

**Issue by Jehops** [polymode/polymode#115]
Hi,

If I open an Rnw file, all is well.  I see three buffers associated with the file with major modes LaTeX/MPS, ESS[S], and HeadTail.  Syntax highlighting switches properly when the point moves.  However, if I close the file and open it or just open a second Rnw file, only one buffer with either mode LaTeX/MPS or ESS[S] (depending on the location of the point) will be open and syntax highlighting will not work (e.g., all text is green in an R chunk) and the key bindings are undefined.

This is in Emacs 25.2.1.

**Comment by vspinu** [comment]
It probably some new thingy in emacs 25.2.1. I will have to update my emacs and try to reproduce this.

**Comment by Jehops** [comment]
Here is a simple example to reproduce the problem.

1. Start `R` (version 3.4.3 here) without any user-installed packages and install the `knitr` package.
2. Start `Emacs` (version 25.3 here) without any installed packages and a blank `~/.emacs.d/init.el`.
3. Add `(setq package-archives '(("melpa" . "https://melpa.org/packages/")))` to `~/.emacs.d/init.el` and evaluate the line.
4. Install the `ess` (version 20180216.1616 here) and `polymode` (version 20170307.322 here) packages.
5. Add `(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))` to `~/.emacs.d/init.el`.
6. Restart Emacs.
7. Open `~/tmp/test1/test1.Rnw` (sample `Rnw` file shown below).  This looks good.
8. Open `~/tmp/test2/test2.Rnw` (same sample `Rnw` file shown below).

Moving point through the buffer displaying `test2.Rnw` will produce messed up syntax highlighting when the point is inside an `R` chunk.

```
\documentclass[]{article}

\begin{document}

<<setup,include=FALSE>>=
library(knitr)
@

\end{document}
```

**Comment by vspinu** [comment]
These issues are pretty surely gone in the new version of polymode.
