### ISSUE TITLE
HeadTail Mode doesn’t support Hideshow Minor Mode

### ISSUE THREAD

**Issue by rdiaz02** [polymode/polymode#119]
I have the following line in my .emacs
` (add-hook 'prog-mode-hook #'hs-minor-mode)`

Now if I do
1. Open emacs (with above line in .emacs)
2. Start R 
3. Get the help of something with examples (e.g., `?rnorm`).

I will get the error

`Polymode error (pm--mode-setup ’poly-head-tail-mode): HeadTail Mode doesn’t support Hideshow Minor Mode` 

Commenting the above line will remove the error (but, of course, also having hs-minor-mode immediately available in programming modes).

**Comment by vspinu** [comment]
I see where this comes from. `hs-mode` checks if comment regexp is defined in the mode and as `head-tail-mode` (only used in header and footer of the chunk) doesn't define any you get an error.

What is your use case and what do you expect hs-minor-mode to do in headers and tails? Or you just want to get rid of that error message?

**Comment by rdiaz02** [comment]
I just want to get rid of the error message. it seems that as soon as I hit that error, other unrelated things start failing (e.g., I noticed that when trying to commit using Magit, as launching the client fails).

**Comment by vspinu** [comment]
> I noticed that when trying to commit using Magit, as launching the client fails

This is unrelated. I don't use polymode much these days, but magit client failure happens all the time. Would be happy to figure that one out.
