### ISSUE TITLE
[R] polymode-insert-new-chunk implementation

### ISSUE THREAD

**Issue by pavopax** [polymode/polymode#123]
hard to believe this is "not yet implemented" (is it?)

edit `polymode.el` to have this:

```
(defun polymode-insert-new-chunk ()
  (interactive)
  (insert "\n```{r}\n")
  (save-excursion
    (newline)
    (insert "```\n")
    (previous-line)))
```

for working with .Rmd files.

source: https://gist.github.com/chlalanne/7403341

**open for comments**

**Comment by vspinu** [comment]
This inserts R chunk. It might be meaningfull in Rmd and Rnw files but not in a general .md files.   General implementation is not trivial.

I would think such feature is better suited for addons like yasnippet or smart-parents. Everyone is free to tweak his own.

**Comment by brendan-r** [comment]
@pavopax I've found the yasnippet solution to work great (some examples, including an R block here https://github.com/brendan-r/dotemacs/tree/master/snippets)

**Comment by brendan-r** [comment]
Note: It turns out that this doesn't work for rmarkdown chunks where you'd like to set parameters as part of the snippet (e.g. https://emacs.stackexchange.com/q/27405/15016), though this [thread](https://github.com/joaotavora/yasnippet/issues/742) looks like it might contain a workaround.

**Comment by vspinu** [comment]
The following yasnippet works as expected with current polymode:

```
# -*- mode: snippet -*-
# name: rmd-block
# key: rb
# --
\`\`\`{r $1}
$0
\`\`\`
```

Place it into `markdown-mode/rmd-block` somewhere within your `yas-snippet-dirs`. 

Generic chunk-insertion is meaningful only for a handful of modes, different people want different behavior of the snippet and some modes (like noweb) traditionally use their own shortcuts (< at bol). Therefore, I decided against having a generic functionality for chunk insertion as part of polymode. 

YAS is perfect for such things and if there are further issues with yas-polymode interaction they should be addressed accordingly.

**Comment by vspinu** [comment]
Actually yas is not working. Contrary to my previous belief fixing YAS is quite a challenging task.
