### ISSUE TITLE
Rmd file not working

### ISSUE THREAD

**Issue by ibayer** [polymode/polymode#124]
Hi,

I'm trying to get polymode to work for Rmd files but can't get past this error message:

```(poly-lock-fontify-now 4 873) -> (nil 594 604 nil): End of buffer 
(poly-lock-fontify-now 4 873) -> (nil 723 781 nil): End of buffer 
(poly-lock-fontify-now 4 873) -> (nil 821 862 nil): End of buffer 
mwheel-scroll: Beginning of buffer
mwheel-scroll: End of buffer
mwheel-scroll: Beginning of buffer [5 times]
ESS-style: RStudio
(poly-lock-fontify-now 1 873) -> (nil 1 121 nil): End of buffer 
ESS-style: RStudio
(poly-lock-fontify-now 1 873) -> (nil 423 437 nil): End of buffer 
(poly-lock-fontify-now 1 873) -> (nil 594 604 nil): End of buffer 
(poly-lock-fontify-now 1 873) -> (nil 723 781 nil): End of buffer 
(poly-lock-fontify-now 1 873) -> (nil 821 862 nil): End of buffer 
```

I'm using this Rmd file [gitst](https://gist.github.com/fernandomayer/65e44e5fa93236ff4bb8) that has been posted in issue https://github.com/vspinu/polymode/issues/105.

```
Status: Installed in ‘polymode-20161218.1326/’ (unsigned). Delete
Status: Installed in ‘markdown-mode-20161222.1416/’ (unsigned). Delete
GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2016-10-20
Status: Installed in ‘ess-20170118.232/’ (unsigned). Delete
```

Any help to fix this is much appreciated.

**Comment by vspinu** [comment]
I don't see this with emacs 25 pre-release. Will have to upgrade to check this properly. You can also try [next](https://github.com/vspinu/polymode/tree/next) branch, maybe it works. But you will have to instal lint manually, not through melpa.

**Comment by ibayer** [comment]
My config settings (cp from various places), maybe they are helpful to reproduce the problem.

```
(use-package polymode 
  :ensure t
  :mode
  ("\\.Snw" . poly-noweb+r-mode)
  ("\\.Rnw" . poly-noweb+r-mode)
  ("\\.[rR]md" . Rmd-mode)
  :init
  (progn
    (defun Rmd-mode ()			
      "ESS Markdown mode for Rmd files"
      (interactive)
      (require 'poly-R)
      (require 'poly-markdown)
      (R-mode)
      (poly-markdown+r-mode)))
  )

(use-package markdown-mode 
  :ensure t
  :commands (markdown-mode gfm-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :config
  (setq markdown-enable-math t))

(use-package ess-site 
    :ensure ess
    :diminish eldoc-mode
    ;; :defer 3
    ;; :bind (:map ess-mode-map
    ;;             ("C-h h" . ess-help))
    :config
    (add-hook 'ess-mode-hook
    	    (lambda ()
    		(ess-set-style 'RStudio)))
;;     (setq ess-offset-arguments 'prev-line)
;;     (setq ess-ask-for-ess-directory nil)
;;     (setq ess-pdf-viewer-pref "emacsclient")

;;     (defun my/add-pipe ()
;;     "Adds a pipe operator %>% with one space to the left and then
;; starts a newline with proper indentation"
;;     (interactive)
;;     (just-one-space 1)
;;     (insert "%>%")
;;     (ess-newline-and-indent))
;;     (define-key ess-mode-map (kbd "M-p") 'my/add-pipe)
    )
```

**Comment by dale0007** [comment]
Howdy! Piggybacking off this issue as I'm having the same/a similar one.

Details of my system:
- Ubuntu 16.04 LTS x64
- Emacs 24.5.1
- polymode installed thru MELPA and configured with .emacs file below

Here is a screenshot of what happens:
![screenshot-window-2017-02-13-173231](https://cloud.githubusercontent.com/assets/16261898/22909717/f50572e6-f212-11e6-9bfb-73b051f7ff0e.png)

Relevant polymode section of .emacs file:
```
;; polymode (for .rmd)
(require 'poly-R)
(require 'poly-markdown)

(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
(add-to-list 'auto-mode-alist '("\\.Snw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
```

I get a bunch of errors that look like what the OP described:
```
(poly-lock-fontify-now 59 918) -> (nil 59 918 nil): Args out of range: 917, 920 
(poly-lock-fontify-now 59 919) -> (nil 59 919 nil): Args out of range: 917, 920 
(poly-lock-fontify-now 59 918) -> (nil 59 918 nil): Args out of range: 917, 920 
(poly-lock-fontify-now 59 917) -> (nil 59 917 nil): End of buffer 
(poly-lock-fontify-now 59 916) -> (nil 59 916 nil): End of buffer 
```

There is no indication that r-mode is functioning inside the .Rmd file (ie. no syntax highlighting or help with indentation, etc.)

I'm happy to send along the .Rmd file I am using if you think that would be helpful. Many thanks for any help & for creating such a sweet mode.

**Comment by kleinschmidt** [comment]
I'm not sure if these are really all the same issue but i'm suddenly having fontification trouble, too. I'm using emacs 25 and just updated some other packages which somehow broke fontification (possibly the markdown mode package, which had a MELPA release about a week ago).  The problem for me is with everything except the _last_ markdown chunk (which always fontifies fine).  It also appears to depend on the number of characters in some or all of the chunks.  For example, this file fontifies fine:

    # 345678901234567
    ```{r testing}
    
    ```

This one does not:

    # 34567890123
    ```{r testing}
    
    ```

I get this error:
```
(poly-lock-fontify-now 1 15) -> (nil 1 15 nil): End of buffer 
```

As I type more numbers in the title (4, 5, 6), I get these three errors:

```
(poly-lock-fontify-now 1 16) -> (nil 1 16 nil): Args out of range: 15, 18 
(poly-lock-fontify-now 1 17) -> (nil 1 17 nil): Args out of range: 15, 18 
(poly-lock-fontify-now 1 18) -> (nil 1 18 nil): Args out of range: 18, 19 
```

If it's any help, this is what the last one looks like:
![screenshot from 2017-12-04 12-56-15](https://user-images.githubusercontent.com/135920/33567868-91e28574-d8f2-11e7-96fd-006f1e91c44d.png)  The last two characters are fontified as markdown-markup-face (as are all the characters in the head-tail mode bit).

**Comment by vspinu** [comment]
Yes. It's likely a markdown issue. I have been noticing issues with markdown before as well.Things are not as robust as they can be. Need to have a deep look one day.

**Comment by kleinschmidt** [comment]
FWIW, font locking using `markdown-mode` by itself has no trouble:
![screenshot from 2017-12-04 15-34-49](https://user-images.githubusercontent.com/135920/33574858-b29b4844-d908-11e7-812a-946810d146f9.png)

**Comment by jdtonkin** [comment]
Same issue here. If I call M-x markdown-mode then the markdown syntax is highlighted. If not, it's not. My R chunks are fine.

**Comment by jdtonkin** [comment]
Looks like any text that is after the last code chunk has markdown syntax highlighting, anything with a code chunk after it doesn't. I'm using latest versions of everything via Melpa, and also tried most recent version of polymode from here on github.

**Comment by cgroza** [comment]
I am also having these issues? Heading are sometimes not recognized and the syntax highlighting changes midway through the text.

**Comment by vspinu** [comment]
Most of the issues with markdown font-lock are fixed (at least in my tests) in the `next` branch. Some of them are markdown-mode issues for whic relevant PRs are currently pending there.

**Comment by vspinu** [comment]
[next] is merged. Please report new issues on poly-R or poly-markdwon tracker.
