### ISSUE TITLE
switching font size/type between modes

### ISSUE THREAD

**Issue by sbellan61** [polymode/polymode#136]
Hi I have polymode installed so I can edit Rmd files with markdown & R formatting. I'd like the font size/type to be continuous when moving in and out of R chunks. At the moment, they're different which makes it quite annoying when switching b/w them. How can I set them to be the same by default? Thanks!

**Comment by vspinu** [comment]
Fonts should not change when moving in/out. If they do, it's a bug somewhere or your peculiar setup.

**Comment by sbellan61** [comment]
Do you have any advice on where to look into this w/in my setup?

**Comment by vspinu** [comment]
Could you upload a couple of screenshots? What does `C-u C-x C-=` say on a troublesome font?

**Comment by sbellan61** [comment]
See attached screenshots as I move the cursor down through a code chunk. The last one is the shortcut you specified—it zoomed in quite a lot.

**Comment by sbellan61** [comment]
![screen shot 2017-08-08 at 4 00 54 pm](https://user-images.githubusercontent.com/6191367/29092082-0555d0d0-7c53-11e7-9ffa-aa02e48d5a4b.png)
![screen shot 2017-08-08 at 4 00 31 pm](https://user-images.githubusercontent.com/6191367/29092085-055ed7ca-7c53-11e7-9b8e-6f38fd4be3f6.png)
![screen shot 2017-08-08 at 4 00 28 pm](https://user-images.githubusercontent.com/6191367/29092084-055ec3ca-7c53-11e7-97f5-d6825b3b4ed4.png)
![screen shot 2017-08-08 at 4 00 26 pm](https://user-images.githubusercontent.com/6191367/29092083-055b7904-7c53-11e7-945d-d6332d58d9e9.png)

**Comment by vspinu** [comment]
Oh, I meant `C-u C-x =` I need to see the font info, not to zoom out. 

Could you provide two screenshots of the same buffer with different positions of the cursor? Such that I can clearly see the difference.

**Comment by sbellan61** [comment]
gotcha, does this help?

![screen shot 2017-08-09 at 10 05 42 am](https://user-images.githubusercontent.com/6191367/29125663-5a34de7e-7cea-11e7-9fb4-4c77e7c1c916.png)
![screen shot 2017-08-09 at 10 05 33 am](https://user-images.githubusercontent.com/6191367/29125661-5a31b780-7cea-11e7-97d3-aa99a1f8902d.png)
![screen shot 2017-08-09 at 10 04 13 am](https://user-images.githubusercontent.com/6191367/29125665-5a3946c6-7cea-11e7-8d80-43e3520be92c.png)
![screen shot 2017-08-09 at 10 04 08 am](https://user-images.githubusercontent.com/6191367/29125662-5a32bc0c-7cea-11e7-9e86-95955dd2effd.png)
![screen shot 2017-08-09 at 10 04 04 am](https://user-images.githubusercontent.com/6191367/29125664-5a3571d6-7cea-11e7-86cf-09d72becfa4c.png)
![screen shot 2017-08-09 at 10 03 58 am](https://user-images.githubusercontent.com/6191367/29125666-5a3e413a-7cea-11e7-8c8d-0c28669d0cfe.png)

**Comment by sbellan61** [comment]
also I put some stuff in my .emacs a while back to set the default text size to be bigger. I wonder if that is what's doing it?

```
(set-default-font "Inconsolata 20")

(setq tramp-default-method "ssh")
(set-face-attribute 'default nil :font "Inconsolata 20" )

(defun sacha/increase-font-size ()
 (interactive)
 (set-face-attribute 'default
                     nil
                     :height
                     (ceiling (* 1.10
                                 (face-attribute 'default :height)))))
(defun sacha/decrease-font-size ()
 (interactive)
 (set-face-attribute 'default
                     nil
                     :height
                     (floor (* 0.9
                                 (face-attribute 'default :height)))))
(global-set-key (kbd "C-+") 'sacha/increase-font-size)
(global-set-key (kbd "C--") 'sacha/decrease-font-size)
(global-set-key [(control c) r] 'revert-buffer)
```

**Comment by vspinu** [comment]
Hm, so the whole buffer has different text-scale right? Just to make sure what are the values of `text-scale-mode-amount` in different chunks?  I cannot reproduce this, text-scale is preserved between buffers for me, and that's by design. What emacs is this?

**Comment by sbellan61** [comment]
Yes, the whole buffer changes scale when I move in/out of chunks. 

How do I find out the values of text-scale-mode-amount in each chunk?

Aquamacs 3.3  GNU Emacs 25.1.1 (x86_64-apple-darwin14.1.0, NS appkit-1344.72 Version 10.10.2 (Build 14C109)) of 2016-09-19 on 24a02dbf6b34ae061ef4df89f15bfbc5d3ed497e

**Comment by vspinu** [comment]
> Yes, the whole buffer changes scale when I move in/out of chunks.

So you are using your commands that you posted earlier to increase the font size in one chunk, but then you switch to other chunk and font is not adjusted? Or how do you end up with different fonts in the first place?

> How do I find out the values of text-scale-mode-amount in each chunk?

`C-h v text-scale-mode-amount RET`

**Comment by sbellan61** [comment]
So the font sizes vary when I move through chunks right from when I open the Rmd file. I can change the font size in each of the modes using my keyboard shortcuts, but it only affects the active mode (i.e. code vs code header vs markdown) in which I apply the shortcut. So I can manually make the different modes have approximately similar font sizes that way; but even then the font type still appears different (the horizontal spacing differs between them).

the text-scale-mode-amount doesn't appear to be an option (see screenshot w/ autocompletions of C-h v text-)

![screen shot 2017-08-10 at 2 02 12 pm 3](https://user-images.githubusercontent.com/6191367/29184564-a4a10dd0-7dd4-11e7-9cb8-de3072b59b9d.png)

**Comment by MilesMcBain** [comment]
I accidentally reproduced something like this: I was trying to see if I could use a proportional font for the markdown combined with a monospace for the code. I set `variable-pitch-mode` in the markdown portion and then everything I could see was converted to proportional. When I navigated the cursor into code chunk, everything I could see flipped over to monospace.

**Comment by vspinu** [comment]
Thanks @MilesMcBain. I could reproduce with simple `M-x buffer-face-mode` or `M-x variable-pitch-mode`.  

I am afraid you cannot have two distinct default faces for code chunks and for text. Text properties are shared between indirect buffers which polymode uses to implement differetn chunks. So it has to be same default face. The best I can do is to move the default face between buffers when buffers are changed. I think that should solve the OP problem.
