### ISSUE TITLE
Support for rmarkdown document powered by shiny (rmarkdown::run)

### ISSUE THREAD

**Issue by dickoa** [polymode/polymode#144]
Hi,

Thanks again for Polymode, it's really great to be able to process Rmd file in Emacs.
I would like know if there's a way to have a new exporter or to tell the exporter to call `rmarkdown::run` instead of `rmarkdown::render` when we `runtime: shiny` in yml header of a document (e.g flexdashboard).

It is documented here: http://rmarkdown.rstudio.com/authoring_shiny.html

Particularly this quote from the link above

> If you’re not using RStudio, or want to run the document in-process for troubleshooting, you can also run the document from the console using the `rmarkdown::run` function.

Thanks again and let me know how to help.

Best,

**Comment by vspinu** [comment]
This would require some tweaks on the emacs side. Can yo uprovide a small example with instructions of how to run it? I don't use shiny nor I have time to figure out all the details at the moment.

**Comment by vspinu** [comment]
@dickoa Are you still interested in this?  I have rewritten polymode and finally got down to the UI. 

Do you have an interesting enough Rmd with shiny apps that I can play with?

**Comment by dickoa** [comment]
@vspinu Yes, I'm still interested and sorry for the delay. Thanks a lot for this and it works perfectly when when we have `runtime: shiny` in the yaml header but it doesn't cover all cases i.e. Rmd based tutorial using the `learnr` package use `runtime: shiny_prerendered` (https://rmarkdown.rstudio.com/authoring_shiny_prerendered.html).

We can extend this regex to support this
https://github.com/polymode/poly-R/blob/master/poly-R.el#L522
What do you think ? do you want me to do a PR ?
Thanks again

**Comment by vspinu** [comment]
Yes. Please. 

I have just switched jobs, so the earliest I could do it is probably in a few months from now. Could you please open a new issues and link to this one? Thanks.

**Comment by dickoa** [comment]
Thanks and congrats for the new job. 
I will create an issue and do PR to update the regex to have support for `shiny_prerendered`.
