### ISSUE TITLE
"polymode-insert-new-chunk" does not work

### ISSUE THREAD

**Issue by jooyoungseo** [polymode/polymode#151]
Hello,

I have recently installed polymode using git and found that polymode-insert-new-chunk does not work in Rmd file.
What I attempted to call the function by pressing "M-n, followed by M-i".
I have added the following lines in my ".emacs.el" file:

(setq load-path
      (append '(".emacs.d/elpa/polymode/"  ".emacs.d/elpa/polymode/modes")
              load-path))

(require 'poly-R)
(require 'poly-markdown)

;;; MARKDOWN
(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))

;;; R modes
(add-to-list 'auto-mode-alist '("\\.Snw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
FYI, I am using GNU Emacs on Windows 10 64 bit.

Please advise me how to resolve this issue.

Thank you.

**Comment by deepthoughts** [comment]
I have the same problem here. I noticed that this function is defined in the polymode.el file but it not implemented yet. As a stopgap measure, I was able to achieve that by using this function in the .emacs file 

Original source: 
https://emacs.stackexchange.com/questions/27405/insert-code-chunk-in-r-markdown-with-yasnippet-and-polymode

Put this code in your .emacs file and restart emac.

```
;;;Insert new chunk for Rmarkdown
(defun tws-insert-r-chunk (header) 
  "Insert an r-chunk in markdown mode. Necessary due to interactions between polymode and yas snippet" 
  (interactive "sHeader: ") 
  (insert (concat "```{r " header "}\n\n```")) 
  (forward-line -1))


(global-set-key (kbd "C-c C-i") 'tws-insert-r-chunk)
```

Remember to change "C-c C-i" to your liking.

**Comment by vspinu** [comment]
Closing in favor of #123
