### ISSUE TITLE
Syntax highlighting issue in Rmd using LaTeX expressions

### ISSUE THREAD

**Issue by brycefrank** [polymode/polymode#152]
I seem to be having some syntax highlighting issues when using LaTeX $$ expressions after the line is wrapped. Below is an example:

![polymode](https://user-images.githubusercontent.com/24326298/37557788-0d4f3ea8-29c7-11e8-8f9c-e1b00e7f338f.png)

As you can see, I would prefer the red segment to be white across the wrapped line. This same issue does not occur by itself in markdown-mode.

Thoughts?

**Comment by vspinu** [comment]
Sorry for super late reply. Could you please post minimal reproducible example in text form? 

I am back at maintaning polymode so will look at it pretty soon now.

**Comment by vspinu** [comment]
Ok, I see. In your example string between `_` is highlighted by markdown. Normally it should be italic, but it's not for you. Strings between `$` are not LaTeX in markdown mode nor in polymode. In polymode only displayed math delimited by `$$` on a new line is recognized as LaTeX. 

So I am pretty confident this is not polymode issue.

**Comment by vspinu** [comment]
In any case, font-lock issues are fixed in the [next] branch. I am closing this to reduce the noise in the issue tracker.
