### ISSUE TITLE
[next] wrong major mode after inline-math

### ISSUE THREAD

**Issue by theGreatWhiteShark** [polymode/polymode#160]
polymode: branch `next`:  0e9483d

When writing inline-math as described in issue #141 (delimited with a `$` sign, no spaces within), **polymode** falsely identifies everything after the math snippet as a LaTeX chunk.

Adding a space behind the first `$` delimiter solves the problem.

Example:

````
Some text with $\text{inline math}$.

```{r 'r-chunk'}

## Polymode enables LaTeX and not ESS mode in here
x <- 1

```
````

**Comment by vspinu** [comment]
You mean space after last one? That's part of the current regexp which enforces one space before and one after the $. Otherwise one finds false positive $s in R code. It's a temporary solution till I get down to limit inner math in host chunks only. 

For now you can fix it by adding more relax regexp:

```el
(oset pm-inner/markdown-inline-math :tail-matcher (cons "[^ $\\\t]\\(\\$\\)[^:alnum:]" 1))
```

**Comment by theGreatWhiteShark** [comment]
No, I meant a white space after the first delimiter. Thanks!

P.S. you got a typo in your code example. An 'o' was introduced in `pset`.

**Comment by vspinu** [comment]
Weird. White space is not allowed after first delimiter and before last one. 

That's not a typo. that's how slots of objects are set in emacs. `oset`.

**Comment by vspinu** [comment]
Fixed! Thanks for reporting. Really appreciate you testing all of this.

**Comment by theGreatWhiteShark** [comment]
No problem. Thanks for writing all the code and doing all the work!

Works almost perfectly. But I could find one setting where the fix didn't worked properly.

When including a *display math* snippet at the very beginning of a line and adding an arbitrary symbol afterwards, it still recognizes the following parts as LaTeX chunk.

```
Text

$$\text{display math}$$.

Text
```

Adding any symbol in front of the first `$$` delimiter or removing the symbol after the closing delimiter fixes the issue. Only the setting above does not work.

**Comment by vspinu** [comment]
Fixed. Displayed math now can now be used within the text just like the inline math can.

**Comment by theGreatWhiteShark** [comment]
Thanks!

Hmm. I really don't want to be picky but I found yet another combination, which does not work.

```
Text

$$\text{display math}
$$

Text
```

I hope this will be the last one.

**Comment by vspinu** [comment]
Fixed. I really have to anchor head on new line. Tail can be followed by any non-alpha-nums.

**Comment by theGreatWhiteShark** [comment]
Thanks.

Still a minor thingy:

If the delimiter of a display math happen to be the only characters in a line, LaTeX-mode won't be detected. Adding a whitespace after the first delimiter fixes it.

```
No LaTeX-mode
$$
\text{display math}
$$

LaTeX-mode
$$ 
\text{display math}
$$
```

But it does not affect any code outside of the delimiters. Just pure cosmetic.

**Comment by vspinu** [comment]
This is by design. You have to add arbitrary character after the head (can be a comment % or space). Otherwise there is no way to differentiate between heads and tails and I don't want to parse from the beginning of the buffer every time a span is needed.

**Comment by theGreatWhiteShark** [comment]
Alright, then everything seems fine and working properly
