### ISSUE TITLE
[next] propertize error on pressing space in chunk header

### ISSUE THREAD

**Issue by theGreatWhiteShark** [polymode/polymode#161]
polymode: branch `next`:  0e9483d 

Every time point is in the header of a chunk and the space is getting hit, the following error occurs

> parse-sexp-propertize-function did not move syntax-propertize--done

and point jumps to the beginning of the line after the header.

**Comment by vspinu** [comment]
Which header? Markdown header? I don't see this. Could you please give a snippet and exact position of the pointer?

For me this parse-sexp-propertize errors usually come from eldoc or some other other function which relies on timers. I don't know the exact reason yet because tracking that would likely mean instrumenting emacs C code.

**Comment by theGreatWhiteShark** [comment]
Sure.

````
Some text

```{r 'r-chunk',fig.cap='string'}
## Polymode
```
````

Introducing a white space in the header of the r chunk enclosed by `{` and `}` yields the error above. It does not matter whether I add it directly after the first "r" or in the string of the _fig.cap_ option.

When I disable ElDoc the error still occurs.

Also the error was only thrown since my latest pull. If you want I can check which commit is the culprit.

**Comment by theGreatWhiteShark** [comment]
Yes, it revealed the issue was actually caused by **yasnippet** (current master 1e71360). When deactivating it, insertion does work properly again.

**Comment by vspinu** [comment]
Could you please share yasnippet config relevant for this error?

**Comment by theGreatWhiteShark** [comment]
Sure.

I use the current master of `yasnippet` (commit 1e71360) and `markdown` (commit 74c0a06) and `Emacs` version 27.0.50 (commit 45ee24e).

The configuration to reproduce the error for the above minimal script is the following

```
;; run with emacs -Q -l ~/epoly.el --file path/to/file.Rmd

(setq polymode-dir "~/dev/polymode/"
      markdown-dir "~/VC/markdown-mode/"
      ;; markdown-dir "~/Dropbox/ELPA/markdown-mode-20180707.1255/"
      ess-dir      "~/dev/ESS/"
      yas-dir      "~/dev/yasnippet/")

(unless (file-exists-p polymode-dir)
  (user-error "Polymode dir (%s) does not exist" polymode-dir))
(add-to-list 'load-path polymode-dir)
(add-to-list 'load-path (expand-file-name "modes" polymode-dir))

(unless (file-exists-p markdown-dir)
  (user-error "Markdown dir (%s) does not exist" markdown-dir))
(add-to-list 'load-path markdown-dir)

(unless (file-exists-p ess-dir)
  (user-error "ESS dir (%s) does not exist" ess-dir))
(add-to-list 'load-path ess-dir)
(add-to-list 'load-path (expand-file-name "lisp" ess-dir))


(unless (file-exists-p yas-dir)
  (user-error "Yasnippet dir (%s) does not exist" yas-dir))
(add-to-list 'load-path yas-dir)

(require 'markdown-mode)
(require 'poly-markdown)
(require 'poly-R)
(require 'ess-site)
(require 'yasnippet)

(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))

(yas-global-mode 1)

(add-hook 'markdown-mode-hook (lambda() (auto-fill-mode 1)))
```

**Comment by vspinu** [comment]
I see. This was fixed yesterday while fixing something else :)

I have also simplified the epoly script to do the requires and the load-path updating automatically:

```el
;;; Modify `deps` and `pkg-dirs` and then run with
;;;   emacs -Q -l ~/epoly.el --file path/to/file.Rmd

;; Dependencies
(defvar deps '(yasnippet markdown-mode poly-R poly-markdown ess-site))

;; These directories and their children matching `deps` regexp are added to load
;; path. The later directories have precedence.
(defvar pkg-dirs '("~/Dropbox/ELPA/"
                   "~/VC/"
                   "~/dev/"
                   "~/dev/ESS/lisp/"))

;; Add all dirs to the load-path
(let* ((deps (append '("polymode" "poly-[[:alpha:]]+") deps))
       (pkg-regexp (format "^\\(%s\\)\\(-[0-9.]+\\)?$"
                           (mapconcat (lambda (x) (format "%s" x)) deps "\\|"))))
  (dolist (dir pkg-dirs)
    (add-to-list 'load-path dir)
    (let ((paths (reverse (directory-files dir t pkg-regexp))))
      (setq load-path (append paths load-path)))))

;; require all deps
(dolist (dep deps)
  (when (symbolp dep)
    (require dep)))

;; Other Configuration
(yas-global-mode 1)
(add-hook 'markdown-mode-hook (lambda() (auto-fill-mode 1)))
```

**Comment by theGreatWhiteShark** [comment]
works
