### ISSUE TITLE
[next] Wrong rendering of bold and italic in the presence of punctuations

### ISSUE THREAD

**Issue by theGreatWhiteShark** [polymode/polymode#162]
commit  d6176b6

Whenever a punctuation symbol follows the delimiters of bold font and an italic section is present afterwards, the rendering in between is slightly off. For a change in order (first italic, then bold) the problem does not occur.

```
**Fat**, normal *italic*, normal **fat**
```

**Comment by vspinu** [comment]
This is markdown issue. You can always check if it's polymode by `M-x markdown-mode` and see if the issue persists.

**Comment by theGreatWhiteShark** [comment]
Ah, indeed
