### ISSUE TITLE
[next] Fail to kill buffer with point inside a chunk

### ISSUE THREAD

**Issue by theGreatWhiteShark** [polymode/polymode#163]
On branch `next`: commit  92c9cbb
Using Emacs 27.0.50 (commit 45ee24e)

---

When I execute `kill-buffer` with point in a chunk, the buffer won't be killed but only the fontification disappears. Now, whenever I insert or delete a symbol the following error will be thrown

> (poly-lock-fontify-now 7 80 [span 7 80 minimal.Rmd[r]]) -> (font-lock-default-fontify-region 7 80): Selecting deleted buffer

In addition, I can not kill the buffer, regardless of how many times I call `kill-buffer`. This only works outside the chunks.

An example: 
````
```{r}
## Inside this chunk the `kill-buffer` command does not work.
x <- 1

```
````

---

Using the startup script 

```
;; run with emacs -Q -l ~/epoly.el --file path/to/file.Rmd

(setq polymode-dir "~/dev/polymode/"
      markdown-dir "~/VC/markdown-mode/"
      ;; markdown-dir "~/Dropbox/ELPA/markdown-mode-20180707.1255/"
      ess-dir      "~/dev/ESS/")

(unless (file-exists-p polymode-dir)
  (user-error "Polymode dir (%s) does not exist" polymode-dir))
(add-to-list 'load-path polymode-dir)
(add-to-list 'load-path (expand-file-name "modes" polymode-dir))

(unless (file-exists-p markdown-dir)
  (user-error "Markdown dir (%s) does not exist" markdown-dir))
(add-to-list 'load-path markdown-dir)

(unless (file-exists-p ess-dir)
  (user-error "ESS dir (%s) does not exist" ess-dir))
(add-to-list 'load-path ess-dir)
(add-to-list 'load-path (expand-file-name "lisp" ess-dir))

(require 'markdown-mode)
(require 'poly-markdown)
(require 'poly-R)
(require 'ess-site)

(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
```

**Comment by vspinu** [comment]
Perfect. I can reproduce with the startup script.

**Comment by vspinu** [comment]
Fixed! 

Looks like we are really making progress here ;)

**Comment by theGreatWhiteShark** [comment]
Very nice
