### ISSUE TITLE
Error when trying to install poly-org

### ISSUE THREAD

**Issue by noctuid** [polymode/polymode#164]
I get this error during compilation:
```
poly-org.el:70:1:Error: No pm-polymode config object with name ‘pm-poly/pm-poly/org’
```

I've tried installing with `quelpa` (and straight) (in case the melpa package was out of date). I've also tried vanilla `package-install`. I can require poly-org and enable poly-org-mode after installing, but all source blocks are just in fallback mode.

**Comment by noctuid** [comment]
Thanks, polymode's performance is really amazing compared to how it was when I first tried it. I really appreciate the work you've put into this package.

One thing I've noticed immediately is that if I call `lispy-up` in an emacs lisp source block on the first list (or `lispy-down` on the last list) is that Emacs freezes if the previous (or next) source block is folded/hidden. If press `C-g` (or if the source block isn't folded), the point will actually move into the previous (or next) list outside of the current source block. And if the previous list (i.e. pair of parens) is *not* in a source block, the point will move to that. I'd expect the point to stay with in the current source block (or at least stay in an Emacs Lisp source block). Also, would you like me to make a separate issue for this (and for anything else that I find)?

**Comment by vspinu** [comment]
Thanks. Yes. Would be nice to have separate problem in separate issues. 

Lispy is not aware of the chunk. The most straightforward way to tackle that is to advise those function to operate within narrowed chunks. The trick is that in some situations (not org) paranthetic forms could span multiple chunks. Will have a look.
