### ISSUE TITLE
`poly-noweb+R-mode` should offer a command to Sweave/tangle/knit the current `.Rnw` buffer

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [polymode/polymode#167]
First of all, thank you for this refactoring. I was waiting for it to strt a R+Sage+noweb mode.

I note that this current setup does not offer a way to `Sweave`/`tangle`/`knit `the current `.Rnw` buffer.

My previous workaround (execute `(ess-noweb-minor-mode)`, *then* set mode to `poly-noweb+R-mode`, *then* set buffer-local variables, **in that order**, see [this issue](https://github.com/polymode/polymode/issues/150)) still works, but has little future (see [this issue](https://github.com/emacs-ess/ESS/issues/609) in `ESS`'s Github site, which hints at the imminent demise of `ess-noweb-mode`).

Could you suggest a solution ?

**Comment by vspinu** [comment]
There are a few commands for weaving and exporting. No tangling atm. See https://polymode.github.io/usage/#exporting-weaving-and-tangling

**Comment by EmmanuelCharpentier** [comment]
Thanks ! I note that I *had* to explicitly add : 
```
(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
```
to my `.emacs.` By default, one cannot `M-x poly-noweb.R` (Emacs complains it's undefined...). Did you plan to have *that* done automatically ?

**Comment by EmmanuelCharpentier** [comment]
I forgot : is there a hook that can be caled *after* exportation ? Alternatively, can one add an advice to the exporting function ?

I have a handy function that patches a "concordance" file to allow going from the PDF to the .Rnw-source, and I'd like to call it after successful compilation...

**Comment by vspinu** [comment]
> plan to have that done automatically

It's already there in poly-R

```el
(add-to-list 'auto-mode-alist '("\\.Snw$" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.[rR]nw$" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.[rR]md$" . poly-markdown+r-mode))
(add-to-list 'auto-mode-alist '("\\.rapport$" . poly-rapport-mode))
(add-to-list 'auto-mode-alist '("\\.[rR]html$" . poly-html+r-mode))
(add-to-list 'auto-mode-alist '("\\.[rR]brew$" . poly-brew+r-mode))
(add-to-list 'auto-mode-alist '("\\.[Rr]cpp$" . poly-r+c++-mode))
(add-to-list 'auto-mode-alist '("\\.cpp[rR]$" . poly-c++r-mode))
```

Probably it's overwriten by ESS or your own emacs somewhere. 

> I have a handy function that patches a "concordance" file to allow going from the PDF to the .Rnw-source, and I'd like to call it after successful compilation...

There is currently a way. A global hook might be added in the future. 

Every weaver and exporter has :sentinel slot to hold the process sentinel which is called when process finishes. Let's assume that you are using `pm-exporter/latexmk`. Then you would overwrite the sentinel with 

```el
(oset pm-exporter/latexmk :sentinel #'my-exporter-sentinel)
```

Here `#'my-exporter-sentinel` (see (elisp) Sentinels) should probably call `pm-default-shell-export-sentinel` at some point but not necessary. 

Also note that these details are not currently advertised much because they might change slightly. Once the polymode core is robust enough I will get down to these UI details.

**Comment by EmmanuelCharpentier** [comment]
> Probably it's overwriten by ESS or your own emacs somewhere.

Probably ESS : my .emacs is simple enough to allow me to check that it doesn't associate ?Rnw to anything.

I understand that the cohabitation between ESS and polymode may sometimes be difficult, especially given the future ESS updates --- I understand that ESS maintainers intend to get rid of `ess-noweb-mode...). I have to stress that this cohabitation has to stay : ESS is too damn useful ! 

> [ Sentinels... ]

Thanks, I'll have to read a bit about that before knowing how to ask a pertinent question ;-)...

> Also note that these details are not currently advertised much because they might change slightly.

Is that also the case for [initialization of polymodes](https://polymode.github.io/internals/#initialization-of-polymodes) and [poly-lock]https://polymode.github.io/internals/#poly-lock), currently undocumented ?

I'd like to readapt a first try at a poly-noweb+Sage-mode I started about a year ago and never finished because a code refactoring was underway... Do you think that the still undocumented parts may be relevant, or that I could adapt your solutions ?

**Comment by vspinu** [comment]
> Is that also the case for initialization of polymodes

Yes. I am still making quite some changes. The big picture is unlikely to change though. The initialization is pretty much settled. Poly-lock is really an internal thing though. 

>  Do you think that the still undocumented parts may be relevant,

Not at all. All you need is [defining polymodes](https://polymode.github.io/defining-polymodes/) sections and looking around for more complex examples inside polymode organization.  

Regarding noweb+Sage you might want to wait a bit. I will create a new repo `poly-python` which will have `noweb+python` mode among other things.

**Comment by vspinu** [comment]
> Maybe you could pool some part of the works ?

That's beyond the scope of polymode. Individual authors are welcome to extend their polymodes with whatever weavers and exporters they want but I cannot feasibly maintain things which I don't use myself. 

Plus that's just tooling. If weaver or exporter already exists it's a trivial exercise to define a polymode  weaver or exporter for it.
