### ISSUE TITLE
New problem(s ?) with Rmarkdown-ESS exporter (seen on Sep 4, 2018).

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [polymode/polymode#169]
The Rmarkdown-ESS exporter gives someting unpalatable to `rmarkdown::render` : 
```
## First-attempt, selecting "AUTO" as the output format prompt :
> rmarkdown::render('/home/charpent/Boulot/Cellule Innovation/Microbiome/NotesEC.Rmd', output_format = 'all', knit_root_dir=getwd())
Error in do.call(output_format_func, options) : 
  second argument must be a list
## Second attempt, selecting the PDF format :
> rmarkdown::render('/home/charpent/Boulot/Cellule Innovation/Microbiome/NotesEC.Rmd', output_format = 'pdf_document', output_file = '/home/charpent/Boulot/Cellule Innovation/Microbiome/NotesEC.pdf', knit_root_dir=getwd())
Error in do.call(output_format_func, options) : 
  second argument must be a list
```

Furthermore (from my `*ùMessages*` buffer), I see this at the compilation of the new version of the exporter : 
```
../../../.emacs.d/elpa/poly-R-20180902.2236/poly-R.el: Obsolete name arg "Rmarkdown-ESS" to constructor pm-callback-exporter
```

I also see this when trying to export : 
```
Exporting ’NotesEC.Rmd’ with ’#<pm-callback-exporter UNNAMED>’ ...
using process ’*R*’
Wrong type argument: stringp, nil
Exporting ’NotesEC.Rmd’ with ’#<pm-callback-exporter UNNAMED>’ ...
Wrong type argument: stringp, nil
```

HTH...

**Comment by vspinu** [comment]
Thanks. I missed that warning. 

Regarding the error, it comes from ESS. Something changed in the meanwhile. I am looking into it. 

For time being select non-ess weaver with `M-n E`. It should work. That's actually the preferred way to run weavers and exporters because they run in a clean environment this way.

**Comment by EmmanuelCharpentier** [comment]
See issue [#1439](https://github.com/rstudio/rmarkdown/issues/1439) against rmarkdown...

**Comment by vspinu** [comment]
Thanks. I have fixed the string nil issue. It was on a poly-R side. 

Regarding the rmardown, I don't see the change. With rmarkdown ` rmarkdown   1.10    2018-06-11 CRAN (R 3.6.0) ` I do see the `output_format` argument.

**Comment by vspinu** [comment]
Arh. Nevermind. The argument issue is more subtle. Thanks for reporting it upstream.
