### ISSUE TITLE
Polymode doesn't currently (2018-09-09) installs its modemap.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [polymode/polymode#171]
Symptom : when trying to use polymode functions via their shortcuts, one gets immediately a beep and the message `M-n is undefined` in the echo area and the `*Messages*`buffer.

Polymodes functions are still functional : calling `M-x polymode-set-weaver` and `polymode-weave` works.

**Comment by vspinu** [comment]
Thanks. It's a consequence of recent bug fixes.

**Comment by EmmanuelCharpentier** [comment]
Thanks. 

Is there a workaround ?
