### ISSUE TITLE
Syntax highlighting of R code changes to uniform color, seemingly randomly

### ISSUE THREAD

**Issue by jason-morgan** [polymode/polymode#172]
I am on the `origin/next` branch (commit `856c4e7`, updated today, 2018-09-20) and I am getting some strange syntax highlighting behavior in R code blocks. Here is an example of a block with the correct highlighting:

![screenshot from 2018-09-20 08-07-52](https://user-images.githubusercontent.com/4924143/45817510-055ac900-bcad-11e8-8400-742cec270470.png)

But when I go to work in the block (any R block in my doc), it sometimes changes to the following:
![screenshot from 2018-09-20 08-07-34](https://user-images.githubusercontent.com/4924143/45817577-30451d00-bcad-11e8-931b-6fbfc2add14b.png)

If I make changes to the block, it will seemingly randomly switch between these highlighting schemes. This has been happening for some time.

**Comment by vspinu** [comment]
BTW, origin/next has been the master for quite a wile. No more next branch.

**Comment by jason-morgan** [comment]
I will try to put together a generic, reproducible example. Are you saying I should be on `master`? If so, I will switch to that before running tests.

**Comment by vspinu** [comment]
Yes, you are 3 weeks late in your commit. Most likely your issues are gone in the form you have experienced it. If you can find a reproducible example, it would be very much apreiciated.

**Comment by jason-morgan** [comment]
Thanks, I will investigate after switching to the `master` branch.

**Comment by jason-morgan** [comment]
Ok. I found the issue. After updating to `master`, I discovered that if I had a space after the opening 3 back-ticks, right before `{r ...`, then the syntax was not highlighted as if it was R. Removing the space seems to have done the trick. tl;dr my bad. And thanks for all your work on `polymode`!
