### ISSUE TITLE
(Minor issue) poly-noweb-electric-< inoperative in poly-noweb+R-mode

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [polymode/polymode#173]
Currently, typing `<` at the start of a new paragraph simply inserts `<`. I expected to get the creation of a new R chunk...

Some trials : 
* `C-h k <` confirms that `<` is indeed bound correctly : 
```
< runs the command poly-noweb-electric-< (found in
poly-noweb+R-mode-map), which is an interactive compiled Lisp function
in ‘poly-noweb.el’.

It is bound to <.

(poly-noweb-electric-< ARG)

Auto insert noweb chunk if at bol followed by white space.
If given an numerical argument, it simply insert ‘<’. Otherwise,
if at the beginning of a line in a host chunk insert "<<>>=", a
closing "@" and a newline if necessary.
```
* `M-x poly-noweb-electric-<` doesn't work : it inserts a literal `^M'`. 
* `M-: (poly-noweb-electric-<)` gives an error ; the backtrace is : 
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 0)
  poly-noweb-electric-<()
  eval((poly-noweb-electric-<) nil)
  eval-expression((poly-noweb-electric-<) nil)
  funcall-interactively(eval-expression (poly-noweb-electric-<) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```il
* `M-: (poly-noweb-electric-< nil)` : inserts a `^M` and returns nil in the echo area.
* `M-: (poly-noweb-electric-< 1)` : inserts a `^M` and returns nil in the echo area.
* `M-: (poly-noweb-electric-< 0)` : doesn't insert anything and returns nil in the echo area.
```
From the source : 
```
(defun poly-noweb-electric-< (arg)
  "Auto insert noweb chunk if at bol followed by white space.
If given an numerical argument, it simply insert `<'. Otherwise,
if at the beginning of a line in a host chunk insert \"<<>>=\", a
closing \"@\" and a newline if necessary."
  (interactive "P")
  (if (or arg (not (eq pm/type 'host)))
      (self-insert-command (if (numberp arg) arg 1))
    (if (not (looking-back "^[ \t]*"))
        (self-insert-command 1)
      (insert "<<")
      (save-excursion
        (insert ">>=\n\n@ ")
        (unless(looking-at "\\s *$")
          (newline)))
      (ess-noweb-update-chunk-vector))))
```

compare with `ESS`'s implementation of the (similar) `ess-noweb-electric-<` :
```
(defun ess-noweb-electric-< (arg)
  "Smart incarnation of `<', starting a new code chunk, maybe.
If given an numerical argument, it will act just like the dumb `<'.
Otherwise and if at the beginning of a line in a documentation chunk:
insert \"<<>>=\", a closing \"@\" and a newline if necessary.  Leave point
in the middle and and update the chunk vector."
  (interactive "P")
  (if arg
      (self-insert-command (if (numberp arg) arg 1))
    (if (and (ess-noweb-at-beginning-of-line)
             (not (ess-noweb-in-code-chunk)))
        (progn
          (insert "<<")
          (save-excursion
            (insert ">>=\n@ ")
            (if (not (looking-at "\\s *$"))
                (newline)))
          (ess-noweb-update-chunk-vector))
      (self-insert-command 1))))
```

The treatment of the mandatory argument `arg` looks suspicious to me. It seems that `(not (eq pm/type 'host))` somehow returns non-`nil`, but I can't be sure (I do not know how to debug or trace an elisp function).

Furthermore (separate issue ?), the idea of a `poly-markdown-electric-backtick` put forth in the (now closed)  [#33](https://github.com/polymode/polymode/issues/33), should be pursued...

**Comment by EmmanuelCharpentier** [comment]
Data point : I've dived in the debugging tutorial, and I'm trying to debug `poly-noweb-electric-<` by evaluting `(debug-on-entry 'poly-noweb-electric-<)`. This is difficult, since the function is compiled ; I'm debugging "blind".

After entering the function, and typing `d` twice (or thrice ?), I get a call to `self-insert-command(1)`, which presumably comes from the third line of code of the function). At this point, using the debugger's `e` command, `pm/type` is `nil` and `arg` is unbound (`(boundp 'arg)` returns `nil`).

As far as I understand the code, _this should not happen_.

Suggestions ?

[ BTW : how to debug the *uncompiled* code ? Is it sufficient to delete the  `.elc` files in the relevant directory, or are there better ways ? ]

**Comment by vspinu** [comment]
Fixed. Thanks!

> how to debug the uncompiled code ?

Best way to compile is to go to the source location of the function and instrument it with `C-u C-M-x`. Next time it's called you will get an interactive debugger where you can press `n n n ...` to move forward, `e` to eval code etc.
