### ISSUE TITLE
Indentation of R chunks in LaTeX environments

### ISSUE THREAD

**Issue by mwlodarczak** [polymode/polymode#174]
Thanks for this great package!

I have had a lot of success using polymode with .Rnw fies and I have recently tried to use it to produce beamer presentations with R chunks included.

In this cases, R chunks are commonly included in `frame` environments, which leads to two indentation problems:

1. When a new chunk is inserted (with `poly-noweb-electric-<`, for instance),  it is indented correctly relative to the enclosing environment. However, after leaving the chunk, the indentation is lost and the point lands in column 0.

2. Selecting the entire buffer and running `indent-region` hangs Emacs. See for instance, [this sample Rnw document](https://gist.github.com/1803930).

As far as I understand, the head-tail mode is basically like fundamental mode so I imagine this is what might be messing this up.

This is on Emacs 25.1.1, polymode 20180912.1854, polymode-R 20180924.957 and poly-noweb 20180923.1439 

Best wishes,
Marcin

**Comment by vspinu** [comment]
I am not fully following on the first problem. What do you mean by "after leaving the chunk"? I would need a small example with expected and actual indentation here.

**Comment by mwlodarczak** [comment]
Sure. Let's say, you have something like this (cursor marked with _)

```
\begin{frame}
  <<>>=
  v <- 1:10
  @_
\end{frame}
```

On pressing RET, I would expect to end up with an indented line (since we're still inside `frame`):
```
\begin{frame}
  <<>>=
  a <- 1:10
  @
  _
\end{frame}
```

Instead, I end up with this:
```
\begin{frame}
  <<>>=
  a <- 1:10
  @
_
\end{frame}
```

**Comment by vspinu** [comment]
I see. Something is not right indeed. I will have a look.

**Comment by mwlodarczak** [comment]
Great, thanks. BTW, not sure if it helps but this seems to work fine with the default ESS noweb mode.

**Comment by mwlodarczak** [comment]
Sorry but this still does not work for me. Tested with `emacs -Q` and

```
(require 'polymode)
(require 'poly-noweb)
(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb-mode))
```

**Comment by vspinu** [comment]
There are several noweb's. You need the R one. Just install `poly-R` from melpa and it should work out of the box. None of those lines is needed, and the last one is wrong because you won't have chunks in R-mode.

I will have a look why `poly-noweb-mode` is not working.

**Comment by mwlodarczak** [comment]
True. I tried `poly-noweb-mode` because that was the mode touched by your commit above.

In any case, I seem to have to manually set `poly-noweb+r-mode` for Rnw files, otherwise I am 
getting the default ESS noweb mode. But even with  `poly-noweb+r-mode` the indentation is still broken.

Am I missing anything?

**Comment by vspinu** [comment]
It's because ESS is loaded after poly-R. The most recent entry in auto-mode-alist has precedence.

**Comment by mwlodarczak** [comment]
Vitalie Spinu <notifications@github.com> writes:

> It's because ESS is loaded after poly-R. The most recent entry in
> auto-mode-alist has precedence.

I see, that makes sense. But as I said, I'm getting the indentation
problems even with poly-noweb+r-mode enabled.

**Comment by EmmanuelCharpentier** [comment]
Just chiming in : 

I have had similar problems on a .Rnw file (therefore using `poly-noweb+R-mode`) with indent-region either getting me an inscrutable error message about a too large depth recursion or starting in a (seemingly) infinite loop (had to `killall emacs`). Ditto for `M-q` not doing anything.

Back to `Rnw-mode` for now. It probably is a booboo. But for now this a _lethal_ booboo...

**Comment by vspinu** [comment]
I have made a small change to noweb code and I no-longer see any issues even on emacs 25.

**Comment by vspinu** [comment]
I don't know. I cannot reproduce the problem which means that it's something specific to your setup or you are loading by accident an older version of poly-noweb. Maybe you have redefined 'pm-inner/noweb' in your config? I am traveling till mid next week. Will have a closer look once back.

**Comment by mwlodarczak** [comment]
On 10/5/18 10:16 AM, Vitalie Spinu wrote:
> I don't know. I cannot reproduce the problem which means that it's
> something specific to your setup or you are loading by accident an older
> version of poly-noweb. Maybe you have redefined 'pm-inner/noweb' in your
> config? I am traveling till mid next week. Will have a closer look once
> back.

Thanks! I would also suspect my own config but I have just started an
instance of Emacs with a clean .emacs.d/, installed `poly-R` from Melpa
but there was no change. Then tried again but this time cloned the repos
from GitHub, added them to the load-path, and required them with the
same result. I don't think there is anything else I can do.

**Comment by vspinu** [comment]
Thanks. I can see an issue with that file but not the one which you described. 

There is now an easy way to test polymode without your config

```sh
# git clone https://github.com/polymode/poly-R.git
# cd poly-R
# export EMACS=emacs26
make cleanall
make start
# navigtate to the the Rnw file and reproduce the problem
```

The above will download all the dependencies from MELPA for the first time and will load poly-R. 

For emacs25 there is indeed a problem. I am getting latex error "unended \begin" for e26 and e27 everything works fine. I will have a look but I am afraid fixing small issue for emacs 25 is not a high priority atm I prefer to move polimode forward in the small time that I have to work on it.

**Comment by mwlodarczak** [comment]
Yes, not supporting older versions of Emacs in the face of time constraints is quite understandable.

I have now compiled and installed Emacs 26.1 from source (I'm on Debian stable) and followed the recipe above but, incredible as it seems, I still see the problem as reported in my previous message: everything gets indented correctly except for the closing "@" in the final code chunk. However, when I navigate to that "@" and press TAB, it gets the right indent.

**Comment by vspinu** [comment]
Hmm. This is indeed a bit crazy. The TAB and indent-region should be indistinguishable.  I am on ubuntu with emacs26.1 from source as well.

No errors or messages in the minibuffer on your side I presume?

**Comment by mwlodarczak** [comment]
On 10/11/18 11:17 PM, Vitalie Spinu wrote:
> Hmm. This is indeed a bit crazy. The TAB and indent-region should be
> indistinguishable. I am on ubuntu with emacs26.1 from source as 
> well.

Well, that's really strange. I can try it on another machine later
today. I will report back.

> No errors or messages in the minibuffer on your side I presume?

No, and nothing in the `*Messages*` buffer either.

**Comment by mwlodarczak** [comment]
OK, I have tested it on Emacs 26.1 ([from here](https://emacsformacosx.com/)) and Mac OS X Mojave, all with the same result.

**Comment by vspinu** [comment]
Uff. I see now. It's a really peculiar issue. Once you indented that `@` and un-indent, all works as expected.  It's only the first invocation of indent-region which gets botched. Will track it down tomorrow. Thanks for all the efforts.

**Comment by vspinu** [comment]
The indent and the hang issues should be gone now. Indentation of regions is now consistent with indentation of regions in plain modes which wasn't always the case before.

**Comment by mwlodarczak** [comment]
Sorry to bring this up again but after the latest change I am getting no indentation at all (tested on Emacs 26.1 and the Rnw file above).

I'm not sure I understand what you mean by "plain modes" but if in this case that's `latex-mode`, then switching to it and re-indenting produces the expected result.

**Comment by vspinu** [comment]
Plain modes are those which use `indent-relative` or `indent-relative-maybe` as their `indent-line-function` those are the defaults and are tab indentation function. In any case, what do you mean by "no indentation at all" can you please provide an example and open a  new issue for that?

**Comment by mwlodarczak** [comment]
On 10/14/18 9:45 PM, Vitalie Spinu wrote:
> In any case, what do you mean by "no indentation at all" can you
> please provide an example and open a new issue for that?

I can open a new issue but I'm not sure whether this is not the same
problem all along. What I mean by no indentation at all is that all
lines are aligned at column 0.

The way to reproduce it is the same as before:
1. Open the example Rnw file I have been linking to all along (note that
this file has no indentation to begin with)
2. Mark the whole buffer and indent it.

Outcome: No change to indentation.

**Comment by vspinu** [comment]
Sorry, I confused the conversation. This is the right issue. There was a tiny mistake in the last commit. I guess I would need to add this file to the indentation tests.

**Comment by mwlodarczak** [comment]
On 10/15/18 12:03 PM, Vitalie Spinu wrote:
> There was a tiny mistake in the last commit. I guess I would need to
> add this file to the indentation tests.

Right. Given how much trouble it has caused, that might be a good idea.

**Comment by mwlodarczak** [comment]
I can confirm that this now works, many thanks!

There is only a small oddity -- the first time you call `indent-region` on the entire buffer, everything works fine. If you call it again on the same (properly indented) buffer, the mark jumps to the end of the buffer, stays there for a short while and then returns to the beginning of the buffer.

**Comment by vspinu** [comment]
I don't see this. The file is now part of `poly-R` repo (`tests/input/knitr-beamer-orig.Rnw`), so you can simply `make start` and try it out directly to check if it's your config.

**Comment by mwlodarczak** [comment]
Vitalie Spinu writes:

> I don't see this. The file is now part of poly-R repo
> (tests/input/knitr-beamer-orig.Rnw), so you can simply make start and
> try it out directly to check if it's your config.

I'm still seeing this. Mind you, you have to re-indent the whole buffer
*twice*.

**Comment by vspinu** [comment]
I do twice, trice etc with emacs 25, 26, 27, with `make start` from the most recent poly-R repo, and I don't see the mark jumping.

**Comment by mwlodarczak** [comment]
Vitalie Spinu writes:

> I do twice, trice etc with emacs 25, 26, 27, with make start from the
> most recent poly-R repo, and I don't see the mark jumping.

Ha, I have tried it on a different machine running Mac OS X Mojave and
it does indeed work fine. So it must be something with my Emacs but it's
still strange that I see it when I run the "make start" recipe above.

In any case, this seems to be unrelated to the present bug. Thanks for
all your patient help, Vitalie!
