### ISSUE TITLE
polymode-mode-map defined incorrectly

### ISSUE THREAD

**Issue by plantarum** [polymode/polymode#175]
https://github.com/polymode/polymode/blob/056ce9ea6e55655065bbbf234a03a04f5d0ed21d/polymode.el#L99

`polymode-mode-map` is defined using defalias, pointing to the variable `polymode-minor-mode-map`. defalias sets function defintions, and mode maps are variables, so this code ends up defining `polymode-mode-map` as an alias for a non-existent function:

> polymode-mode-map is an alias for ‘polymode-minor-mode-map’, which is not
defined. Please make a bug report.

I think you can fix this by using `defvaralias` instead.

**Comment by vspinu** [comment]
Of course. Thanks!
