### ISSUE TITLE
Wishlist : have the output formats proposed by `bookdown` available as choices for `polymode-export`

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [polymode/polymode#176]
The title says it all...

The workaround is, of course, to insert the relevant data in a YAML header and to use `AUTO DETECT`, which passes `"all"` as output format to `rmarkdown::render`. But (this is ill-documented in the rmarkdown "documentation"), the YAML header **MUST** be the first thing in the `.Rmd file...

A better workaround might be useful...

**Comment by vspinu** [comment]
Could you please provide a minimal example of a book and how to render from R?

**Comment by vspinu** [comment]
Nevermind. It's all in the book. Will see what I can do.

**Comment by vspinu** [comment]
Done. Unfortunately `book_serve` requires Rstudio but everything else seem to work.

**Comment by EmmanuelCharpentier** [comment]
Thanks a lot !

I'm not actually looking to use the server (nor Rstudio) : running a local R with emacs is more adequate to my needs... My interest in `bookdown` lies in the possibility to have cross-references (to tables, figures, references, etc...), which are a _sine qua non_ not only in papers (which can usually be submitted as \LaTeX) but also for anything vaguely scholarly oriented (be it an HTML page, a presentation, or even an interactive app) ; `bookdown` is a plus for this kind of work, for which \LaTeX entails some severe workarounds, and is unable to give results unusable on paper and quite useful on a screen (think animation or dynamic tables...).
