### ISSUE TITLE
poly-org-mode is enabled by default and arguably should not be

### ISSUE THREAD

**Issue by malcook** [polymode/polymode#177]
Hi,

In #148 you say that poly-mode is " not enabled by default" 

However, I find that  to be false in version 20180926.2044 

Testing by running emacs with minimal init file of:

```
(require 'package)
(package-initialize)
(require 'use-package)
(use-package polymode)
```
and then visiting an .org buffer and polymode is enabled.

I am used to controlling whether .org files enable poly-org-mode by including / commenting the following from my init.el file: 
`;;;	      (add-to-list ' auto-mode-alist '("\\.org" . poly-org-mode))
`
But now I must explicitly remove it,
`	      (delete '("\\.org$" . poly-org-mode) auto-mode-alist)
`
This works but seems wrong.

BTW - I know I can toggle it with `poly-org-mode`, but regardless of whether it toggle it on or off, it always reports in the minibuffer "org polymode enabled" which seems another (related?) bug.

BTW2 - THANKS for poly-mode!

**Comment by vspinu** [comment]
`poly-org-mode` is active in org files only if you have installed `poly-org`.  It is presumed if you have installed poly-org, you want it in org files.

**Comment by malcook** [comment]
> `poly-org-mode` is active in org files only if you have installed `poly-org`. It is presumed if you have installed poly-org, you want it in org files.

I think this is an improper presumption which you should reconsider.  Installation of a package is different from requiring it.  I have it installed because I want to use it *sometimes* and I don't want to have to control it by uninstalling it when I don't want it and reinstalling it when I do.

It may be that when I get fully used to it, I will want it all the time, but, that verdict is out...  I've been living in emacs for 30 years and modal edit contexts very much mess with my experience.

I recommend that you reconsider your method for determining activation for the benefit of others.  Your choice is highly non-standard in my experience.  I have determined a workaround that works for me. 

BTW - I used to use-package polymode but not require polymode-configuration for this very reason - I wanted control over the file associations.  But this seems to have been deprecated.

Thanks, and, I'll come back to you later about my issues with poly-org-mode.  I've been using org in combination with ESS for years, and do find some troubles, but I need to take time to collect them and communicate them clearly.

**Comment by vspinu** [comment]
>  Installation of a package is different from requiring it

The trouble is that install and require is confounded with MELPA because of the autoloads. So when you install and if the pacakge is active it is autoloaded and registered in auto alist on startup.

To say it differently, you can have poly-org.el lying around but once you do `(require 'poly-org)` you get the auto-list registration. Because package.el does the require for you, you get what you get. 

> Your choice is highly non-standard in my experience.

I am afraid this is _the_ standard and _the_ only practice. Every emacs mode designed for an extension `.xyz` will add it to the `auto-alist`. `poly-noweb` is designed for .nw so it registeres .nw, poly-org is designed for org, so it registers .org, etc. I don't really see how it could work otherwise.

You can disable `poly-org` in `package-load-list`, but I guess you know that already.

**Comment by vspinu** [comment]
There is a `:disabled` keyword in `use-package`, I think this is what you need, or not?

**Comment by malcook** [comment]
> once you do `(require 'poly-org)` you get the auto-list registration

hmmm... but, I *don't* have `(require 'poly-org)` or `(use-package poly-org)` in my init.el.


_(well, actually I do but it is commented out now)_


That was the point of my original report, where I in my 4 line replacement init file I don't do either and *still* poly-mode it invoked in .org files.

Or, perhaps I should understand your point to mean:

> once you do `(require 'poly-org)` **_for the first time_** you get the auto-list registration **_even on later emacs sessions where you don't._**

I would be very surprised by this, but then, it might explain exactly the behavior by which I am very surprised!

!!??

**Comment by malcook** [comment]
> There is a `:disabled` keyword in `use-package`, I think this is what you need, or not?

Good to know about this.  Thanks.  For now I'm just going to delete the association and turn poly-org by hand...

And also take a more careful study of polymode and report any issues as they arise.

Thanks for taking this up.... and I appreciate this so much, and understand we may disagree and that your sense should most often prevail.

Cheers ~ Malcolm

**Comment by vspinu** [comment]
> hmmm... but, I don't have (require 'poly-org) or (use-package poly-org) in my init.el.
> (well, actually I do but it is commented out now)

That should not be indeed. I have just grepped for auto-mode-alist my whole dev directory and there is only one instance of `(add-to-list 'auto-mode-alist '("\\.org$" . poly-org-mode))`, the one in poly-org. So I am pretty sure it's not on my side. Something adds it to auto-mode-alist on your side. Forgotten config somewhere or a require. You can check if it's a require once you start emacs with `(featurep 'poly-org)`.

> For now I'm just going to delete the association and turn poly-org-mode by hand when I want it.

You can just add a new entry to the top of alist. It will take precedence and it's robust to changes to the exact regexp or mode name.

I have an even more troubling situation with markdown but no-one complained so far. Some derived polymodes like `poly-markdown+r-mode` require `poly-markdown` as a results not only Rmd files are associated with a polymode but the md files as well. This might not be what the user wants.

**Comment by malcook** [comment]
> there is only one instance

yes - and that instance is preceeded by `;;;###autoload` which results in it being copied to the fle `poly-org-autoloads.el` which gets loaded during emacs startup from my init.el by calling  `(package-initialize)`.

Like I say, I have a workaround.  And, despite my preferences, it is reasonable that

> It is presumed if you have installed poly-org, you want it in org files.

... and you are not alone in make such presumptions as [apparently it is commonly done](https://emacs.stackexchange.com/questions/34523/how-to-autoload-a-package-without-requiring-in-the-init-file)

as further revealed to me by

`grep auto-mode-alist ~/.emacs.d/elpa/**/*-autoloads.el
`
_(though most of the ones I depend upon I have put in my init.el - where I am used to managing them myself)_

Anyway, I am happy to end this _arguably_ exchange and defer to your preferences here.

After all, it is easy enough to turn it off!
