### ISSUE TITLE
polymode-next-chunk-same-type should stay put if there is no additional chunk of same type

### ISSUE THREAD

**Issue by malcook** [polymode/polymode#179]
In my hands, M-n C-M-n will advance to EOF if at last chunk of a given type

Arguably preferable would be to beep, message "no more chunks of type %s", and stay put....

**Comment by vspinu** [comment]
Sounds reasonable.

**Comment by vspinu** [comment]
On this occasion I implemented the "cycling" for chunk navigation. See the docstring. I am sure you will like it.

**Comment by malcook** [comment]
> I am sure you will like it.

Yes indeed.  Much obliged!
