### ISSUE TITLE
Strange automatic indentation in SQL[ANSI] blocks in `poly-markdown-mode`

### ISSUE THREAD

**Issue by ashiklom** [polymode/polymode#181]
Unnecessary extra indentation is inserted when editing `sql` code blocks in markdown.

To reproduce:
1. Start emacs with `emacs -q`.
2. `(package-initialize)` and `(require 'poly-markdown)`
3. `C-X C-F test.md`
4. Try to enter text like the following:

````
```sql
SELECT * FROM table;
SELECT * FROM table;
SELECT * FROM table;
```
````

After each `<return>`, the block gets re-indented. After entering the second line, I automatically get this:

````
```sql
SELECT * FROM table;
       SELECT * FROM table;
```
````

After the third line, I get this (note that the third line starts with a tab, not spaces).

````
```sql
SELECT * FROM table;
       	 SELECT * FROM table;
	 SELECT * FROM table;
```
````

Editing a plain SQL file in SQL [ANSI] mode works as expected (no extra indentation). What's going on here?

**Comment by vspinu** [comment]
This has to do with the fact that sql mode uses a very simple indentiation mechanism (`indent-relative`). The built-in emacs region indenting provides a special case for it and I wasn't aware of that. Will think of something today.

**Comment by ashiklom** [comment]
You guys are the best. Thanks for fixing that so quickly!

**Comment by livnev** [comment]
Thanks for fixing this, I've been puzzled by this issue with some custom modes for a long time! :smiley:
