### ISSUE TITLE
Issue with aggressive-indent-mode

### ISSUE THREAD

**Issue by noctuid** [polymode/polymode#183]
With `aggressive-indent-mode` on, I get two spaces of indentation on the first line of a source block (when there should be no indentation).

**Comment by vspinu** [comment]
Please provide more info and reproducible example. I am using aim and haven't noticed issues so far.

**Comment by vspinu** [comment]
Aggressive indent should indent exactly the same as indent-region AFAIK.

**Comment by noctuid** [comment]
I'm no longer having this issue with the latest polymode. I'll reopen if I start having it again and can reliably produce it.

**Comment by noctuid** [comment]
For anyone who comes across this issue, this fixes it:
```elisp
(setq org-src-preserve-indentation t
      org-edit-src-content-indentation 0)
```
Before I had `org-edit-src-content-indentation` at the default 2 and `org-src-preserve-indentation` as t.
