### ISSUE TITLE
Different visual-line-mode states across chunks

### ISSUE THREAD

**Issue by lionel-** [polymode/polymode#185]
When `visual-line-mode` is enabled in markdown-mode and not in the language mode of chunks, the global value changes depending on cursor position. This leads to lots of flickering.

**Comment by vspinu** [comment]
Are you sure you are using the most recent polymode? Visual line mode (among other minor modes) is explicitly ported between buffers. You can git pull poly-R repo and do `make start` there to get a clean emacs+polymode state.

**Comment by lionel-** [comment]
Yes I have updated it today. The last time was in 2016, I have to say the experience is much much better! Thanks for all the work!

What do you mean by "explicitly ported between buffers"? Does it mean that if the markdown is in visual-line, the chunk is set to have visual-line as well? If yes, that's what is causing the flicking.

**Comment by vspinu** [comment]
Once you move from markdown to chunk the value of visual-line-mode is moved to the chunk, when you go back it's moved from the chunk to the markdown. They are kept in sync in order to provide similar experience as in normal buffers. 

I don't see how this could be provoking flicks because it's only done when the state don't match. In other words if a minor mode is already on, nothing is done. Something local is probably playing a role. This is why I am saying you should try `make start` to try without your config.

**Comment by vspinu** [comment]
>  If yes, that's what is causing the flicking.

It might cause the flick first time you move, yes. But not on subsequent transitions.

**Comment by vspinu** [comment]
I don't think so.  I just tried it and it works fine even when adaptive-wrap-prefix is on in one buffer and off in another. The way adaptive wrap works is by placing text properties in the buffer which are automatically shared between indirect buffers so I don't have to move that mode around.

**Comment by lionel-** [comment]
It's not about adaptive wrap but about visual-fill-column-mode. I can reproduce it in the Emacs instance started with `make start`.

**Comment by lionel-** [comment]
Within markdown:

```
M-x package-install
visual-fill-column
M-x visual-fill-column-mode
```

Then move to an R chunk.

**Comment by lionel-** [comment]
I'm not sure if there's a way to fix this because IIUC this is implemented with window margins. Perhaps I should just enable the fill column mode in the chunks as well, and keep the code within 80 columns which seems like a good idea for R markdown documents anyway.

**Comment by vspinu** [comment]
Thanks, I see it now.

**Comment by lionel-** [comment]
Awesome, thanks!
