### ISSUE TITLE
No valid exporters in current context

### ISSUE THREAD

**Issue by Jehops** [polymode/polymode#186]
After a recent upgrade of the `polymode` and `poly-*` packages from MELPA, with R noweb files, `polymode-export` and `polymode-set-exporter` report `user-error: No valid exporters in current context`. `polymode-weave` reports `apply: Symbol’s value as variable is void: goto-address-mode`.

This is with an Emacs build from the master branch (commit 8602bd8) with no poly-specific customizations other than these lines in `init.el`.
```
(add-to-list 'auto-mode-alist '("\\.md"  . poly-markdown-mode))
(add-to-list 'auto-mode-alist '("\\.Snw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
```

**Comment by vspinu** [comment]
I see the goto-addrees issue but regarding exporters, do you see it in Rnw or Rmd files?

**Comment by Jehops** [comment]
I see it in `Rnw` files.

**Comment by Jehops** [comment]
Looks good after upgrading from MELPA.  Thank you.

**Comment by justmytwospence** [comment]
I'm seeing this now in my Rmarkdown files. My polymode config:

```
(use-package poly-markdown
  :mode
  (".Rmd$". poly-markdown-mode)
  :config
  (setq polymode-display-process-buffers nil
        polymode-exporter-output-file-format "%s"))
```

**Comment by vspinu** [comment]
Remove Rmd association. Those exporters are registered in `poly-markdosn+r-polymode`. If it worked before, it was a bug.

**Comment by vspinu** [comment]
Actually, you should have got only `pandoc` exporter, not an error. Make sure both poly-R and polymode are up-to-date.

**Comment by justmytwospence** [comment]
I've cut it down to just 

```
(use-package poly-markdown :ensure t)
(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
```

then I have to manually enable poly-markdown-mode still (not sure why), and I'm getting the same error.

**Comment by vspinu** [comment]
Something is not right with your install. I have just tried both with use package and plain MELPA load and first line is enough. No error with M-n E either. Jump to the definition of `poly-markdown-mode` and look at the `poly-markdown-autoloads.el` there must be an entry for auto-mode-alist there. If not that means you are using an outdated file. The directory as of this writing should have `20190317.1352` in it.

**Comment by justmytwospence** [comment]
I deleted the polymode directories (and ess) from my elpa directory and reinstalled with use-package. Now I have:

```
poly-markdown-20190317.1352
polymode-20190325.745      
```

Still the same issue. Could it be something in my ESS config?

**Comment by justmytwospence** [comment]
I've figured out the problem. My oversight was that the file I'm working on is labeled with an `.Rmd` extension, which caused both the autoload issue and the exporter issue. `.Rmd` is a pretty standard extension when working with Rmarkdown, do you think it should be supported?

**Comment by justmytwospence** [comment]
ack actually I still only have the pandoc exporter available it seems.

**Comment by vspinu** [comment]
You need poly-R package. poly-markdown+r-mode, R specific exporters and Rmd association  are all defined there.

**Comment by justmytwospence** [comment]
Ah hmm. So what would your recommended `use-package` loading method for someone who works exclusively with Rmarkdown files?

**Comment by vspinu** [comment]
`(use-package poly-R)` and nothing else. Your error is, yet again, likely due to conflicting versions of packages. Just make sure that everything is up to date. I would think use-package to be able to detect stalled dependencies, too bad if not.

**Comment by bnicenboim** [comment]
I'm getting the same error with emacs doom and everything up-to-date. So what is the recommended configuration for Rmd files?

**Comment by bnicenboim** [comment]
never mind, it's working, sorry
