### ISSUE TITLE
Autoload fails

### ISSUE THREAD

**Issue by cruizh** [polymode/polymode#190]
When using the following init file, polymode does not work

```emacs-lisp
(require 'package)
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)
(package-initialize)

(require 'use-package)
(use-package polymode
  :ensure t)
(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
```

When finding a `.md` file, it returns the following error:
```File mode specification error: (void-function poly-markdown-mode)```

Using `poly-markdown` instead works fine.

**Comment by vspinu** [comment]
After the rewrite all polymodes live in their own repos. You just need `(use-pacakge  poly-markdown)`. No ensure or file associations needed.
