### ISSUE TITLE
Polymode for VueJS

### ISSUE THREAD

**Issue by Juli4nAc0sta** [polymode/polymode#191]
I am currently using web mode for the syntax of vuejs, but it does not work well, so I want to replace it with polymode.

So, to practice a bit, try to create my own polimode based on the documentation, but I have not managed to work with the 3 modes that would be html, js and css.

Do you have a polymode example working with more than 2 different modes or is there already a way to use VueJS with pylomode?

**Comment by vspinu** [comment]
Polymode can be used with arbitrary number of inner modes. Does VueJS have any special requirements or you are just looking for a basic web-mode (HTML+JS+CSS)? If so I think there is a built-in emacs mode for that called `mhtml-mode`.

**Comment by Juli4nAc0sta** [comment]
Yes, researching a little bit effectively is `mhtml-mode`, but from what I see it is for emacs 26 and currently I have version 25. I will update my emacs and try, if it does not work well I will continue trying with polymode

**Comment by Juli4nAc0sta** [comment]
in emacs-26 mhtml-mode works very well
