### ISSUE TITLE
New Example poly-markdown+r-mode definition

### ISSUE THREAD

**Issue by patrickeganfoley** [polymode/polymode#192]
My `poly-markdown+r-mode` no longer works since the large refactor (I get `File mode specification error: (error Autoloading file /Users/patrickfoley/.emacs.d/elpa/polymode-20181030.1841/polymode.elc failed to define function poly-markdown+r-mode)` )

Should we now be defining `poly-markdown+r-mode` ourselves, as shown [here](https://polymode.github.io/defining-polymodes/) ?  And if so, does anyone have an example definition? 

Sorry if this is the wrong place to ask this!

**Comment by wedens** [comment]
Do you have [poly-R](https://github.com/polymode/poly-R) package installed?

**Comment by patrickeganfoley** [comment]
Ah!  No idea how I missed that!  Thanks so much - it works perfectly now.



For reference, relevant parts of my config are

```
(use-package polymode
  :ensure t
  :commands (poly-markdown+r-mode)
  :mode (("\\.rmd\\'" . poly-markdown+r-mode)
	 ("\\.Rmd\\'" . poly-markdown+r-mode))

  :init
  (autoload 'r-mode "ess-site.el" "Major mode for editing R source." t)
)


(use-package poly-markdown
  :ensure t
  :mode (
	 ("\\.md" . poly-markdown-mode)
  )
)

(use-package poly-R
  :ensure t
)
```

Thanks!!
