### ISSUE TITLE
fill paragraph with inline code chunks

### ISSUE THREAD

**Issue by kleinschmidt** [polymode/polymode#193]
First I wanted to say how much I appreciate having inline R code chunks treated as code chunks.  However,  I've encountered a problem with how they're handled by `fill-paragraph`.  Let's say I have a `.Rmd` file with a single long line: 

```
Testing blach ablah asdfa asdfas adg a `r 345678` asdf asdf aasd fas dasdf asd asdfa sdf asdfa dsf asd fas asdfas falsdkjg a;ldh gasdlkjh
```

# Desire outcome

With my `fill-column` set to 80, I'd expect that `fill-paragraph` run anywhere on this line should wrap the line to 80 characters, like this:

```
Testing blach ablah asdfa asdfas adg a `r 345678` asdf asdf aasd fas dasdf asd
asdfa sdf asdfa dsf asd fas asdfas falsdkjg a;ldh gasdlkjh 
```

# Actual outcome

What I actually get depends on the location of point when I run `fill-paragraph`.  As far as I can tell, it treats each bit of markdown on either side of the chunk as it's own paragraph/isolated markdown chunk.

With point anywhere before the code chunk, and the only change is that the space before the code chunk is deleted (which is what I'd expect to happen to trailing whitespace):

```
Testing blach ablah asdfa asdfas adg a`r 345678` asdf asdf aasd fas dasdf asd asdfa sdf asdfa dsf asd fas asdfas falsdkjg a;ldh gasdlkjh
```

With point anywhere inside the code chunk, there's no change.

With point after the code chunk, the long line is wrapped at 80 characters _after the code chunk_:

```
Testing blach ablah asdfa asdfas adg a `r 345678` asdf asdf aasd fas dasdf asd asdfa sdf asdfa dsf asd fas asdfas falsdkjg a;ldh
 gasdlkjh
```

Note that there's also a leading space on the wrapped line, as if the space between the code chunk and the following text "asdf" is leading white space (e.g. because of an indented paragraph).

# Old behavior

I'll also add that in the past I've also had trouble with `fill-paragraph` and inline r code chunks, but there the problem was the opposite: code chunks were treated as "normal" text, and `fill-paragraph` would sometimes insert a line break in the middle of the chunk which is not valid in RMarkdown.  So the new behavior is progress IMO.  

# Possible solution

What I'd like to see is that each inline code chunk is treated as a single word for the purposes of wrapping.  I don't know if this is feasible to do with polymode.  My old workflow of putting each "inline" code chunk on it's own line actually works really well with this new behavior, since the inline chunk blocks reflowing so it's not inserted back into the paragraph (and possibly being split in the process).  But splitting out the inline code chunks feels unnecessarily fiddly.

**Comment by vspinu** [comment]
Thanks for reporting this.  Previous treatment of fill paragraph in polymode was definitely too simplistic (just narrowing to current span). 

Should be fixed now for most cases and will likely break on cases when two adjacent paragraph have different modes but those are rare and I am not sure it's worth dealing with explicitly. Mardown mode itself breaks on those.

**Comment by kleinschmidt** [comment]
Thank _you_ for addressing it so quickly!  And thanks for all your work on polymode!

**Comment by kleinschmidt** [comment]
The latest MELPA release looks good on all my use cases; thanks again.
