### ISSUE TITLE
Highlighting difference 

### ISSUE THREAD

**Issue by wedens** [polymode/polymode#195]
I have a configuration that enables sql mode inside scala mode.

This is how it looks in scala-mode buffer with polymode:
![image](https://user-images.githubusercontent.com/697162/49206931-301c7880-f3e6-11e8-99f3-f1ef31da7d51.png)

Notice weird `current` and `exists` words highlighting.

And this is how it looks in a regular sql-mode buffer:
![image](https://user-images.githubusercontent.com/697162/49206904-1f6c0280-f3e6-11e8-8b3e-611120e36139.png)

Both buffers use postgres backend via hook that does `(sql-set-product "postgres")`. And major mode info shows that it's indeed active in both cases.

If I do prefixed `C-x =` in a scala-mode buffer with a cursor on the word "current" it shows:
```
There are text properties here:
  :pm-mode             sql-mode
  :pm-span             [Show]
  face                 ((background-color . "#216820371dd4") font-lock-builtin-face)
  fontified            t
```
If I do the same in plain sql-mode buffer it doesn't have a `face` property.

my polymode configuration:
```elisp
(use-package polymode
  :commands poly-scala-mode
  :mode ("\\.scala\\'" . poly-scala-mode)
  :config
  (defcustom pm-host/scala
    (pm-host-chunkmode :name "scala"
                       :mode 'scala-mode)
    "Scala host chunkmode"
    :group 'poly-hostmodes
    :type 'object)

  (defcustom pm-inner/scala-sql-multiline
    (pm-inner-chunkmode :name "doobie-multiline-sql"
                        :mode 'sql-mode
                        :head-matcher "sql\"\"\"[ \t]*\n?"
                        :tail-matcher "[ \t]*\"\"\"")
    "Multiline sql interpolator"
    :group 'poly-innermodes
    :type 'object)

  (defcustom pm-inner/scala-sql-multiline-fr
    (pm-inner-chunkmode :name "doobie-multiline-fr"
                        :mode 'sql-mode
                        :head-matcher "fr\"\"\"[ \t]*\n?"
                        :tail-matcher "[ \t]*\"\"\"")
    "Multiline fragment interpolator"
    :group 'poly-innermodes
    :type 'object)

  (defcustom pm-inner/scala-sql
    (pm-inner-chunkmode :name "doobie-sql"
                        :mode 'sql-mode
                        :head-matcher "sql\""
                        :tail-matcher (cons "\\(^\\|[^\\\\]\\)\\(\"\\)" 2))
    "Sql interpolator"
    :group 'poly-innermodes
    :type 'object)

  (defcustom pm-inner/scala-sql-fr
    (pm-inner-chunkmode :name "doobie-fr"
                        :mode 'sql-mode
                        :head-matcher "fr\""
                        :tail-matcher (cons "\\(^\\|[^\\\\]\\)\\(\"\\)" 2))
    "Fragment interpolator"
    :group 'poly-innermodes
    :type 'object)

  (define-polymode poly-scala-mode
    :hostmode 'pm-host/scala
    :innermodes '(pm-inner/scala-sql-multiline
                  pm-inner/scala-sql
                  pm-inner/scala-sql-multiline-fr
                  pm-inner/scala-sql-fr)))
```

Emacs version: 27.0.50
polymode: f9034ce (HEAD)

**Comment by vspinu** [comment]
Hmm. This one is funny indeed. Do you observe other issues besides incorrect highlighting?

Can you post full file here where you see the problem? I will try to reproduce.

**Comment by wedens** [comment]
>  Do you observe other issues besides incorrect highlighting?

I haven't noticed any other issues.

What's funnier is that when I copy/paste the same code to the other buffer, paster code doesn't have such problem. Same code in 2 buffers in split windows:
![image](https://user-images.githubusercontent.com/697162/49265988-fe0f2300-f486-11e8-9eb9-f06a303aa4ea.png)

I can't share this code, but I'll try to reproduce it with some shareable minimal example.

**Comment by wedens** [comment]
Looks like this is enough to reproduce the problem:
```scala
object test {

  def setCurrentLicenseQ(license: TLicense) =
    sql"""
      INSERT INTO current_license (license) VALUES ($license)
      ON CONFLICT (license_exists) DO UPDATE SET license = EXCLUDED.license
    """.update
}
```

**Comment by vspinu** [comment]
This one turned to be a bit crazy. For the record, the core of the issue was that in one buffer you get `(let ((with-syntax-table fl-syntax-tbl (re-search-forward fl-matcher nil t)))` to find something and in another one not. 

I tracked it down to scala-mode setting it's own syntax stuff in sql buffer. Particularly `parse-sexp-lookup-properties` was set to buffer local `t`, I didn't even know that this variable affects search :|

Anyways, setting `:protect-syntax` to `t` in host mode should do the trick. 

```el
(defcustom pm-host/scala
  (pm-host-chunkmode :name "scala"
                     :mode 'scala-mode
                     :protect-syntax t)
  "Scala host chunkmode"
  :group 'poly-hostmodes
  :type 'object)

(defcustom pm-inner/scala-sql-multiline
  (pm-inner-chunkmode :name "doobie-multiline"
                      :mode 'sql-mode
                      :head-matcher "\\(sql\\|fr\\)\"\"\"[ \t]*\n?"
                      :tail-matcher "[ \t]*\"\"\"")
  "Multiline sql interpolator"
  :group 'poly-innermodes
  :type 'object)

(defcustom pm-inner/scala-sql
  (pm-inner-chunkmode :name "doobie-sql"
                      :mode 'sql-mode
                      :head-matcher "\\(sql\\|fr\\)sql\""
                      :tail-matcher (cons "\\(^\\|[^\\\\]\\)\\(\"\\)" 2))
  "Sql interpolator"
  :group 'poly-innermodes
  :type 'object)

(define-polymode poly-scala-mode
  :hostmode 'pm-host/scala
  :innermodes '(pm-inner/scala-sql-multiline
                pm-inner/scala-sql))
```

You  don't need 4 innermodes btw.

**Comment by wedens** [comment]
Thanks! That seems to work perfectly.
