### ISSUE TITLE
poly-lock-mode is too slow when open large file.

### ISSUE THREAD

**Issue by jingtaozf** [polymode/polymode#197]
The attachment file can be used to test the slow performance.

[test.org.gz](https://github.com/polymode/polymode/files/2633010/test.org.gz)

**Comment by vspinu** [comment]
To clarify, you mean slow on opening, not slow on editing, right? 

poly-lock is triggered on the entire file so the startup delay is expected. I will do something about that at some point. Your file opens in about 3 seconds for me which is not that bad given its size.

**Comment by jingtaozf** [comment]
Yes, opening is very slow for me, it cost about 5 seconds on my computer, but it is immediately opened with org mode.

I would like to store as much as possible contents in one org file,may be 1M size for an org file.


I hope polymode is lightweight and more quick.:)

**Comment by vspinu** [comment]
I will see what I can do.

> ,may be 1M size for an org file.

This is pretty crazy :)

**Comment by jingtaozf** [comment]
I found that package jit-lock will fontify at a most size `jit-lock-chunk-size`(in function `jit-lock-function`).
maybe poly-lock should follow the same behavior in function `poly-lock-function`, this is the diff file for my simple modification, which speed up opening instantly, but maybe there are some other place to apply the same rule.
```lisp
169c169
<                          (min (point-max) (+ start jit-lock-chunk-size)))))
---
>                          (point-max))))
```

**Comment by gdkrmr** [comment]
This is part of the profile report of a 700 line org-file. I turned of poly-mode in file local variables, but it still seems to still use cpu:
```
- redisplay_internal (C function)                                1090  39%
 - poly-lock-function                                             840  30%
  - poly-lock-fontify-now                                         836  30%
   - jit-lock-fontify-now                                         832  30%
    - jit-lock--run-functions                                     816  29%
     - run-hook-wrapped                                           816  29%
      - #<compiled 0x275ed01>                                     816  29%
       - font-lock-fontify-region                                 816  29%
        - font-lock-default-fontify-region                        816  29%
         - font-lock-fontify-keywords-region                      800  29%
          + org-activate-links                                    573  20%
          + org-activate-footnote-links                            92   3%
          + #<lambda 0x20b6c4771>                                  32   1%
          + eval                                                    8   0%
            org-activate-code                                       4   0%
            org-font-lock-add-priority-faces                        4   0%
            org-activate-tags                                       4   0%
            org-do-emphasis-faces                                   3   0%
         + font-lock-unfontify-region                              16   0%
```

**Comment by rdiaz02** [comment]
I am experiencing this problem: working with https://github.com/rdiaz02/OncoSimul/blob/master/OncoSimulR/vignettes/OncoSimulR.Rmd
polymode makes **editing** unbearably slow: I can type for seconds without anything being shown, and I need to C-g to see what I have just typed.  (I have just updated all my packages).

**Comment by vspinu** [comment]
@rdiaz02 please make sure poly-r and polymode are up to date (delete all old versions from ELPA folder). I don't see the problem you have described but there are issues indeed, most likely with the markdown-mode. I cannot even open the file in markdown-mode. Could you please open a new issues and describe at which location you experience the problem. Please provide emacs, poly-r, polymode and mardkown-mode versions. Thanks. You can also `git clone` poly-r repo and do `make start` from inside then open your file. If problem doesn't show up, that means it's something wrong with your local setup.

**Comment by rdiaz02** [comment]
Thanks! I did as you said, removed markdown-mode, and all poly*. I reinstalled:
- markdown-mode (20190305.319)
- poly-markdown (20190415.1547)
- poly-noweb (20190317.1352)
- poly-R (20190504.1020)
- polymode (20190508.1847)

Everything is much faster now, though I still experience occasional and hard to reproduce problems, reported in new issue: https://github.com/polymode/polymode/issues/227
