### ISSUE TITLE
polymode slow with `string-rectangle` 

### ISSUE THREAD

**Issue by andreasleha** [polymode/polymode#200]
Might be related to #197.  Working with non-tiny Rmd files is unbearably slow.

I attach a profiler report from commenting some code in an R block using rectangles to add '##'.  This operation took 19 (!) seconds to finish.  The Rmd file has 5000 lines -- mostly in code blocks.

I can confirm this with `emacs -q`.

[pm.profile.txt](https://github.com/polymode/polymode/files/2657618/pm.profile.txt)

**Comment by vspinu** [comment]
Do you have very big inner spans? What are the steps to reproduce? What emacs/polymode is this?

**Comment by jinlin82** [comment]
I have encounter the similar problem. When I type some words into Rmd file， it takes some seconds to appear. Then I updated markdown-mode to the latest Melpa version (markdown-mode-20181229.1430), the problem disappeared. I don't kown why.

Just for reference.
