### ISSUE TITLE
Error "Variable binding depth exceeds max-specpdl-size"

### ISSUE THREAD

**Issue by wedens** [polymode/polymode#203]
Sometimes it happens when just editing a scala file. In this case it happened on newline.

My configuration is the same as I've posted in #201.

I don't have any polymode chunks in the buffer where the error have occurred.

Increasing `max-specpdl-size` doesn't help.

[Stacktrace](https://pastebin.com/JNPHqqar) (too long to be inlined here)

**Comment by vspinu** [comment]
This is indentation issue. I cannot fix it without an example.
