### ISSUE TITLE
Poly-org-mode is slow when opening tabs containing large code blocks

### ISSUE THREAD

**Issue by FredeEB** [polymode/polymode#204]
I've recently installed polymode, because I use org-files for my [Emacs config](https://github.com/fredeeb/.emacs.d), but sometimes there's a big delay when expanding, especially, but not limited to, the [Packages section](https://github.com/fredeeb/.emacs.d/blob/master/config.org#Packages).

I've only installed polymode and poly-org, and enabled it by default in org-mode. If there's a fix for this, it would be greatly appreciated. All the configuration I've done for polymode can be found [here](https://github.com/FredeEB/.emacs.d/blob/master/config.org#org-stuff). 

Steps to repoduce is just download config.org and look through it with poly-org-mode enabled.

**Comment by vspinu** [comment]
Thanks for the example. I will have a look. Can you please post the steps to reporoduce the slow-down? Do you observe it during the startup? (see #200) Or it's really only during the expansion? I guess during the expansion the buffer is re-fontified. In that case it would be the same problem as with #200, the font-lock.

**Comment by FredeEB** [comment]
I haven't noticed it during startup, it's only when expanding tabs, that contain large amounts of source blocks, like the example from the original post. 

Steps to reproduce is to expand a tab, that contains many or large source blocks (+100 lines ish). I've just noticed that it doesn't happen on my desktop, so it might be a hardware related issue.. I'll keep you updated :)

**Comment by vspinu** [comment]
The #197 has been fixed and a specific speed-up fix to poly-org has been added. On your config files I see no slow-down whatsoever, either on opening or on section expansion. So I presume the issue has been fixed.
