### ISSUE TITLE
default name of output file in rmarkdown::render()

### ISSUE THREAD

**Issue by linc0380** [polymode/polymode#205]
Hi there,

the default output file name passed to `rmarkdown::render()` by the exporter results in an error. In particular, with the Rmarkdown file named `template.Rmd`, the default output file name appears to be `template[exported].pdf` and a resulting R graphic `unnamed-chunk-2-1.pdf` is searched in `template{[}exported{]}_files/figure-latex` which, however, does not exist.

When the command `rmarkdown::render()` is issued with the output file name argument manually set to `template.pdf`, everything works fine.

See also [this post](https://stackoverflow.com/questions/54220921/exporting-of-rmd-file-in-emacs-polymode-does-not-work) on StackOverflow.

Thanks,
Michael

**Comment by vspinu** [comment]
What do you export to?  Looks like you are configuring your exporter manually in the yaml header. In that case you should use `AUTO` exporter. 

The rmarkdown has been changing arguments I think, so things might not be working as expected anymore. I would need a small example and exact description of the keys pressed. Thanks.

**Comment by linc0380** [comment]
Hi Vitalie,

You are right. When I load [this file](http://www.jacolienvanrij.com/Tutorials/template.Rmd), press `M-n E` to select exporter `Rmarkdown`, and then `M-n e` to export to `AUTO DETECT`, the resulting html file looks perfect. The same is true by exporting to `html document (html)`.

When, however, I change the output specification in the yaml header to `pdf_document`, press `M-n E` to select exporter `Rmarkdown`, and then `M-n e` to export to `pdf document (pdf)` I get the said error. The output is given [here](https://github.com/polymode/polymode/files/2793573/polymode.log)

My emacs is version 25.1.1, as far as I can see I have polymode 0.1.5. installed (`M-x list-packages` does not actually provide that number but `poly-R-20190111.1908`.

Thanks a lot!

Regards,
Michael

**Comment by vspinu** [comment]
> press M-n E to select exporter Rmarkdown, and then M-n e to export to pdf document (pdf) I get the said error. The output is given here

I see. If you configure pdf output in yaml then you should use AUTO exporter, not pdf. Those targeted exporters are for cases when there is no yaml metadata. 

 I will have a look, maybe it could be possible to auto-detect this scenario and do the right thing automatically and avoid such confusion.

**Comment by linc0380** [comment]
Dear Vitalie,

selecting the `AUTO` exporter indeed works when there is a yaml entry `output: pdf_document`. That's great! The procedure does not work, however, when there is no such entry and the `pdf` exporter is picked .

Incidentally, when producing the pdf file using the `AUTO` exporter, the pdf opens up in Emacs afterwards. Can a proper pdf viewer be configured?

Regards,
Michael

**Comment by vspinu** [comment]
> The procedure does not work, however, when there is no such entry and the pdf exporter is picked .

That means it's a bug. I will check. 

> Can a proper pdf viewer be configured?

Polymode uses `display-buffer`. There is package `openwith` which does display pdf (and other files) outside of emacs. You just need a simple configuration like:

```
(setq openwith-associations
        '(;; ("\\.pdf\\'" "okular" (file))
          ("\\.docx?\\'" "xdg-open" (file))
          ;; ("\\.mp3\\'" "xmms" (file))
          ;; ("\\.\\(?:mpe?g\\|avi\\|wmv\\)\\'" "mplayer" ("-idx" file))
          ;; ("\\.\\(?:jp?g\\|png\\)\\'" "display" (file))
          ))
```


There is also https://github.com/politza/pdf-tools which is a very good pdf viewer inside emacs.

**Comment by linc0380** [comment]
> > The procedure does not work, however, when there is no such entry and the pdf exporter is picked .
> 
> That means it's a bug. I will check.
> 
Thanks a lot, Vitalie. Please keep me posted.

> > Can a proper pdf viewer be configured?
> 
> Polymode uses `display-buffer`. There is package `openwith` which does display pdf (and other files) outside of emacs. You just need a simple configuration like:
> 
> ```
> (setq openwith-associations
>         '(;; ("\\.pdf\\'" "okular" (file))
>           ("\\.docx?\\'" "xdg-open" (file))
>           ;; ("\\.mp3\\'" "xmms" (file))
>           ;; ("\\.\\(?:mpe?g\\|avi\\|wmv\\)\\'" "mplayer" ("-idx" file))
>           ;; ("\\.\\(?:jp?g\\|png\\)\\'" "display" (file))
>           ))
> ```
> 
> There is also https://github.com/politza/pdf-tools which is a very good pdf viewer inside emacs.
>
These are two wonderful packages. Thanks for suggesting them to me; I was not aware of them.

Regards,
Michael

**Comment by vspinu** [comment]
Has been fixed. Pandoc doesn't recognize the `[]` in file names correctly. I have renamed the file format patterns without using `[]`.
