### ISSUE TITLE
ploy-r does not respect Rmarkdown's `output:` specified meta information 

### ISSUE THREAD

**Issue by feng-li** [polymode/polymode#207]
According to rmarkdown's documentation, the command
```r
rmarkdown::render('myfile.Rmd')
```
reads the meta option (via `output:` tag) from Rmarkdown file. 

Whilst the current output command in poly export process is hard-coded as 
```r
rmarkdown::render('myfile.Rmd', output_format = 'pdf_document', output_file = 'myfile[exported].pdf')
```
which ignores the `output:` meta information.

**Comment by vspinu** [comment]
You have to select AUTO, then the output will be auto-detected. If you select pdf, then pdf is "hardcoded" as you say.
