### ISSUE TITLE
Stuck when including this trunk in rmd file

### ISSUE THREAD

**Issue by crotoc** [polymode/polymode#209]
Thanks very much for your great work on polymode!
I have a question that when including this trunk in the file, It freezes. And also when I paste the bash command to the sh trunk using right click, it takes forever. Can you help me have a check. I don't know how to debug so have no idea to address it. When testing it, please change the suffix to rmd and use poly-markdown-mode to open. Thanks! 
My env is emacs 26.1, linux (centos + ubuntu), newest version of polymode from Mepla. 

[test.rmd.txt](https://github.com/polymode/polymode/files/2894797/test.rmd.txt)

**Comment by crotoc** [comment]
I shortened the cmd and then opened emacs firstly and then turn poly-markdown-mode on by "M+x poly-markdown-mode" . It stucked and the trunk's highlighting color was wrong. Then I pressed ctrl-g for many times, and until the right color was shown I could continue using emacs again. From the message, I see a lot of error druing redisplay. I guess there should something wroing in poly-lock-function. 

![image](https://user-images.githubusercontent.com/12446554/53258826-3479ca00-3693-11e9-9345-15de295e38c9.png)

**Comment by vspinu** [comment]
I can reproduce. Thanks for reporting. Will have a look.

**Comment by crotoc** [comment]
Thanks!

**Comment by vspinu** [comment]
This is a bug in emacs regexp search. I have reported it [there](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34823). So closing this as an upstream issue. The search fails on `"$_\t$tmp\t$cat\t$donor\t$stage\t$pool\t$rep\t$time\t$comment"'`. So maybe you can re-formulate that as an workaround.

**Comment by crotoc** [comment]
Great! Thanks very much for looking at this! I will try to see how to re-formulate!
