### ISSUE TITLE
This file switches to latex-mode partway

### ISSUE THREAD

**Issue by roryk** [polymode/polymode#211]
Hey all,

When opening this file in `poly-markdown+r-mode`, it switches to latex-mode halfway through the code block. Deleting the line `cnames = gsub("\\(", "", cnames)` fixes it.

I am having troubling figuring out why this is happening and was hoping someone could reproduce here. Im using spacemacs so it also could be something conflicting there as well.

https://www.dropbox.com/s/rf3cet7pqpu9yzl/latex-issue.Rmd?dl=1

**Comment by vspinu** [comment]
This is a bug. Latex inner mode should not be allowed within other innermodes.

**Comment by roryk** [comment]
Thanks @vspinu, I use polymode for almost all of my work and I super appreciate all of your work on it, it is invaluable.
