### ISSUE TITLE
.tex file opens in new frame after Sweave processing

### ISSUE THREAD

**Issue by marcschwartz** [polymode/polymode#215]
After using Sweave or Sweave-ESS to process a .Rnw file using M-n w, the resultant .tex file opens in a new frame. I would prefer that the .tex file not be opened in this manner, as I typically do not review the content unless there are errors and this just opens yet one more frame.

This behavior was not present prior to using polymode with ESS.

This is using Emacs 26.1 (from https://emacsformacosx.com) and polymode, etc., installed via melpa.

A simple .Rnw file that can reproduce this is attached, with the extension changed to .txt for Github compatibility.

[Example.txt](https://github.com/polymode/polymode/files/2975187/Example.txt)

Steps to reproduce:

1. Double click on the .Rnw file in Finder (macOS), which opens Emacs and the .Rnw file in a frame.

2. Start a new R session with M-x R

3. Place the cursor in the .Rnw file buffer and use M-n w  to begin Sweave, using either 'Sweave' or 'Sweave-ESS' when prompted.

4. Once Sweave completes, the resultant .tex file opens in a new frame.

Note that if Sweave hits an error and terminates prematurely, the 'partial' .tex file does not open. So Sweave needs to complete the processing of the .Rnw file successfully for this behavior to occur.

Thanks.

**Comment by vspinu** [comment]
Polymode uses `display-buffer` and that means you can modify how buffers are displayed by customizing `display-buffer-alist`. In your case:

```el
(add-to-list 'display-buffer-alist '("-woven\\.tex"
                                     (display-buffer-no-window)
                                     (allow-no-window . t)))
```

There is also a global `polymode-display-output-file` which when set to nil will inhibit display of all buffers.  This one is radical solution and thus not recommended.

**Comment by vspinu** [comment]
I will make `polymode-display-output-file` to be able to hold a function. This should be able to fill arbitrary load display patterns.

**Comment by marcschwartz** [comment]
Vitale,

Thanks for your consideration here.

If I could ask, once you have a chance to look at this, if you could provide an example function, that would enable non-lisp programmers to model such a function and make needed changes? Perhaps something that models the current behavior in a stepwise fashion, such that one could replace/edit that function incrementally.

Thanks!

**Comment by vspinu** [comment]
`polymode-display-output-file` is not a defcustom and can be a function. 

For your `.tex` case:

```el
(setq polymode-display-output-file
      (lambda (ofile)
        (not (string-match-p "-woven.tex\\'" ofile))))
```

**Comment by marcschwartz** [comment]
Hi Vitale,

Thanks for these updates. I updated polymode via melpa and can confirm that the additional buffer no longer opens.

I appreciate your spending time on this.
