### ISSUE TITLE
Apply polymode in temp buffer then copy as string?

### ISSUE THREAD

**Issue by damiencollard** [polymode/polymode#219]
Hello,

I'm trying to get polymode to render e-mails I receive whose body is markdown and contains fenced code blocks. 

To that end, using `with-temp-buffer` I copy the text of the body into the temporary buffer, enable `poly-markdown-mode` and copy the temporary buffer's contents back onto the e-mail's body.

Unfortunately, while `markdown-mode` does work (the text copied back into the e-mail's body has markdown highlighting), it seems polymode doesn't: the fenced code blocks aren't highlighted. Does it require the buffer to be visible?

I tried forcing it using `poly-lock-flush` (and also, `poly-lock-fontify-now`, `font-lock-ensure`) before copying the temp buffer back to the e-mail, but nothing works. Is there something I can do to force the highlighting?

**Comment by vspinu** [comment]
> Does it require the buffer to be visible?

Not really. `font-lock-fontify-buffer` and `poly-lock-fontify-now` should have worked. 

Can you post your copy-paste function? 

If you are interested just in font-lock, then there is markdown's built-in `markdown-fontify-code-block-natively`. Have you tried that?

**Comment by damiencollard** [comment]
On Dim, mar 24 2019, Vitalie Spinu wrote:

>> Does it require the buffer to be visible?
>
> Not really. `font-lock-fontify-buffer` and `poly-lock-fontify-now` should have worked.
>
> Can you post your copy-paste function?

Here's the function I used in Gnus' article (view) mode. Where I call
`(font-lock-fontify-buffer)`, I also tried the aforementioned functions.

```lisp
(defun test-highlight-markdown ()
  (interactive)
  (with-silent-modifications
    (save-excursion
      ;; Put point at the beginning of the message's body.
      (message-goto-body)
      (let* ((text (buffer-substring (point) (point-max)))
             (new-text (with-temp-buffer
                         (poly-markdown-mode)
                         (insert text)
                         ;; Tried several things here...
                         (font-lock-fontify-buffer)
                         (buffer-substring (point-min) (point-max)))))
        (delete-region (point) (point-max))
        (insert new-text)))))
```

> If you are interested just in font-lock, then there is markdown's
> built-in `markdown-fontify-code-block-natively`. Have you tried that?

I hadn't, thanks for suggesting it. It does work, but ideally I'd like
to get rid of part of the treatment of the Discourse e-mails I have
written, since `markdown-mode` + `polymode` would do a much better job.

--
Damien Collard

**Comment by vspinu** [comment]
You should first insert text then call poly-markdown-mode. Fontificaiton is deffered. 

> but ideally I'd like to get rid of part of the treatment of the Discourse e-mails I have written, 

Not sure what you mean by this. Do you mean that you would like to have the gnus buffer (both article and composition) to be in some gnus + markdown polymode of some kind? 

I have been thinking for long to add an option to be able to use polymode for font-lock only purpose. That is, never switch to innermode-buffers, but rather always keep in the host, thus preserving all host shortcuts but have the font-lock from indirect buffers. I think this gnus article polymode would be a nice application.

**Comment by damiencollard** [comment]
On Dim, mar 24 2019, Vitalie Spinu wrote:

> You should first insert text then call
> poly-markdown-mode. Fontificaiton is deffered.

I tried the following sequence, and it doesn't seem to do anything (at
least, the text copied back in the article shows no highlighting
whatsoever):

```lisp
  (insert text)
  (poly-markdown-mode)
  (poly-lock-flush)
```

And the following does highlight the markdown, but the code in the
fenced blocks is not highlighted using their major modes:

```lisp
  (insert text)
  (poly-markdown-mode)
  (font-lock-fontify-buffer)
```

>> but ideally I'd like to get rid of part of the treatment of the Discourse e-mails I have written,
>
> Not sure what you mean by this. Do you mean that you would like to
> have the gnus buffer (both article and composition) to be in some gnus
> + markdown polymode of some kind?

Yes, exactly. I'm currently more focused on the reading side, but
composition would be nice too.

> I have been thinking for long to add an option to be able to use
> polymode for font-lock only purpose. That is, never switch to
> innermode-buffers, but rather always keep in the host, thus preserving
> all host shortcuts but have the font-lock from indirect buffers. I
> think this gnus article polymode would be a nice application.

That would be great!

In fact, I had first tried to write a polymode (gnus-article-mode
hostmode + markdown-mode innermode) to read Gnus articles highlighted as
markdown but I had troubles since an e-mail body has no obvious head and
tail matchers. I wrote functions for the matchers and it sort of worked,
but it spewed errors. I could expand on that and post the code, but from
what you way I guess it's not feasible at the moment?

--
Damien Collard

**Comment by vspinu** [comment]
> e-mail body has no obvious head and tail matchers

The body is detected by gnus (or message.el) some how, so should be possible. Just need to write a small function for head matching . 

> t's not feasible at the moment?

It's possible but the text of innermode spans will be editable and you will be placed into corresponding modes which is not what you want. 

Preventing buffer switching to innermodes is trivial, I can add this feature anytime. I suggest that you post whatever you have already with examples of gnus articles that you want to highlight and we go from there.

**Comment by damiencollard** [comment]
On Lun, mar 25 2019, Vitalie Spinu wrote:

>> e-mail body has no obvious head and tail matchers
>
> The body is detected by gnus (or message.el) some how, so should be
> possible. Just need to write a small function for head matching .

The beginning of the body is detected by finding the first blank line
after the headers.

Emacs provides the function `message-goto-body` that moves point at the
beginning of the body.

I did write a small function that makes use of it (note that this was a
separate attempt from the temp buffer way I described in a previous
post):

```lisp
(define-hostmode poly-gnus-article-hostmode
  :mode 'gnus-article-mode)

(defun discourse-article--beginning-of-body (_)
  (let ((b (save-excursion (message-goto-body) (point))))
    (cons b b)))

(defun discourse-article--end-of-body (_)
  (cons (point-max) (point-max)))

(define-innermode poly-gnus-markdown-innermode
  :name "Markdown innermode"
  :mode 'markdown-mode
  :protect-font-lock t
  :head-matcher 'discourse-article--beginning-of-body
  :tail-matcher 'discourse-article--end-of-body
  :head-mode 'host
  :tail-mode 'host)

(define-polymode poly-gnus-article-mode
  :hostmode nil ;; Trying this as minor mode.
  :innermodes '(poly-gnus-markdown-innermode))
```

And while it sort-of worked, it spewed a bunch of errors:

    (pm-switch-to-buffer 527): Bad polymode selection: span:(528 528) pos:527

    Error during redisplay: (poly-lock-function 1) signaled (error "Bad polymode selection: span:(528 528) pos:1")

(where 528 was the beginning of the body)

Note that I also tried with `(cons b (1+ b))` (where `b` is the
beginning of the body) but I had the same errors.

>> t's not feasible at the moment?
>
> It's possible but the text of innermode spans will be editable and you
> will be placed into corresponding modes which is not what you want.
>
> Preventing buffer switching to innermodes is trivial, I can add this
> feature anytime. I suggest that you post whatever you have already
> with examples of gnus articles that you want to highlight and we go
> from there.

Here's the repo for "Discourse article", containing sample e-mails:

https://github.com/damiencollard/discourse-article

(This does *not* use my polymode attempt, but the temp buffer method I described.)

The sample of interest is `tests/samples/sample1-raw-plaintext-only.txt`
as it contains fenced Rust code blocks. I can upload more samples if
needed.

And here's the code I'm trying to get highlighting with (markdown works,
fenced blocks don't):

```lisp
(defun dc/highlight-markdown ()
  (interactive)
  (with-silent-modifications
    (save-excursion
      (message-goto-body)
      (let* ((text (buffer-substring (point) (point-max)))
             (new-text (with-temp-buffer
                         (insert text)
                         (poly-markdown-mode)
                         (font-lock-fontify-buffer)
                         (poly-lock-flush)
                         (buffer-string))))
        (delete-region (point) (point-max))
        (insert new-text)))))
```

Thanks

**Comment by vspinu** [comment]
Thanks. I will have a look sooninish. The selection error is most likely due to bad head-tail detection.

**Comment by vspinu** [comment]
@damiencollard I have finally found time to look at it. Your matchers were not well defined. They should behave similarly to how `re-search-forward` does the search. This would be the correct way to define it

```el

(define-hostmode poly-gnus-article-hostmode
  :mode 'gnus-article-mode)

(defun discourse-article--beginning-of-body (ahead)
  (let ((beg (save-excursion (message-goto-body) (point))))
    (if (> ahead 0)
        (when (<= (point) beg) (cons beg beg))
      (when (< beg (point)) (cons beg beg)))))

(defun discourse-article--end-of-body (ahead)
  (when (> ahead 0) (cons (point-max) (point-max))))

(define-innermode poly-gnus-markdown-innermode
  :mode 'markdown-mode
  :protect-font-lock t
  :head-matcher 'discourse-article--beginning-of-body
  :tail-matcher 'discourse-article--end-of-body
  :head-mode 'host
  :tail-mode 'host)

(define-polymode poly-gnus-article-mode
  :hostmode nil ;; Trying this as minor mode.
  :innermodes '(poly-gnus-markdown-innermode))
```

But that would mean that you won't see the plain markdown mode instead of the polymode. So, I think, what you are after is the other way around - poly-markdonw + gnus article innermode, right? Here you go:

```el
(defun discourse-article--message-header-beg (ahead)
  (when (< ahead 0) (cons (point-min) (point-min))))

(defun discourse-article--message-header-end (ahead)
  (let ((beg (save-excursion (message-goto-body) (point))))
    (if (> ahead 0)
        (when (<= (point) beg)
          (cons beg beg))
      (when (<= beg (point))
        (cons beg beg)))))

(define-innermode poly-gnus-article-innermode
  :mode 'gnus-article-mode
  :protect-font-lock t
  :head-matcher 'discourse-article--message-header-beg
  :tail-matcher 'discourse-article--message-header-end)

(define-polymode poly-gnus-article-mode poly-markdown-mode
  :innermodes '(:inherit poly-gnus-article-innermode))
```

But this still has the problem that the body is edditable and you don't have gnus shortcuts. I am thinking right now of how to always keep the gnus mode on.

**Comment by damiencollard** [comment]
Hi @vspinu,

On Sam, avr 13 2019, Vitalie Spinu wrote:

> Your matchers were not well defined. They should behave similarly to how
> re-search-forward does the search.

Ah, got it, thanks.

> [...]
> But that would mean that you won't see the plain markdown mode instead
> of the polymode. So, I think, what you are after is the other way
> around - poly-markdonw + gnus article innermode, right?

Yes, your solution (with Gnus article mode as innermode) works better,
with the exception that the article's headers aren't highlighted anymore
even though when point is within the headers, the active mode is article
mode, as expected. I'll see if I can fix that.

> But this still has the problem that the body is edditable and you
> don't have gnus shortcuts. I am thinking right now of how to always
> keep the gnus mode on.

Regarding the body being editable: it's not a problem since the article
buffer is readonly, so the article can't actually be edited.

As for the key bindings, it is indeed crucial to keep the Gnus bindings
active. Thanks for looking into it!

**Comment by vspinu** [comment]
Just made it work in master. This is the new way of doing it:

```el

(defun discourse-article--message-header-end (ahead)
  (let ((beg (save-excursion (message-goto-body) (point))))
    (and
     (if (> ahead 0) (<= (point) beg) (<= beg (point)))
     (cons beg beg))))

(define-innermode poly-gnus-article-innermode
  :mode 'gnus-article-mode
  :protect-font-lock t
  :head-matcher "\\`"
  :tail-matcher 'discourse-article--message-header-end)

(define-polymode poly-gnus-article-mode poly-markdown-mode
  :innermodes '(:inherit poly-gnus-article-innermode)
  :keep-in-mode 'gnus-article-mode)

(pm-around-advice #'mm-enable-multibyte #'polymode-with-current-base-buffer)
(pm-around-advice #'mm-disable-multibyte #'polymode-with-current-base-buffer)
```
The buffer is now constantly in gnus mode. The last two advices are there because gnus atempts to set the multibyte and that's not allowed in indirect buffer where it now resides.

> the article's headers aren't highlighted anymore

If I just enable `gnus-article-mode` in your sample I don't see any highlighting. So it has something to do with the gnus itself.

**Comment by damiencollard** [comment]
On Sat, Apr 13 2019, Vitalie Spinu wrote:

> The buffer is now constantly in gnus mode.

Yes, that's great! The Gnus keybindings do work.

There are a few weird things, though:

  - Headers are not highlighted and their background looks the same as
    markdown's fenced code block background, while they're usually the
    same background as the mail's text.

  - `q`, which usually closes the article window, kills the buffer and
    goes back to the summary window (the list of e-mails) doesn't work
    and instead displays "Selecting deleted buffer".

  - `s`, which moves the focus to the summary window, makes the line
    numbers appear (I use `display-line-numbers-mode`). I normally have
    them disabled in `gnus-article-mode`. Changing window with `C-x o`
    doesn't make the line numbers appear.

>> the article's headers aren't highlighted anymore
>
> If I just enable `gnus-article-mode` in your sample I don't see any
> highlighting. So it has something to do with the gnus itself.

Yes, Gnus performs the header highlighting. For some reason the
highlighting is lost when `poly-gnus-article-mode` is active.

I haven't investigated any of the above yet; I'll have to dig into Gnus'
innards!

Thank you

**Comment by vspinu** [comment]
>   - Headers are not highlighted and their background looks the same as
>   markdown's fenced code block background, while they're usually the same
>   background as the mail's text.

That's because gnus is now innermode. Just add `:adjust-face nil` to the
declaration to get rid of the background. 

>   - `q`, which usually closes the article window, kills the buffer and
>     goes back to the summary window (the list of e-mails) doesn't work
>     and instead displays "Selecting deleted buffer".

How do you install poly-gnus into gnus article? I use gnus so I can test
this. So far I was testing it on the txt file which you provided.

>   - `s`, which moves the focus to the summary window, makes the line
>     numbers appear (I use `display-line-numbers-mode`). 

I was not aware of display-line-numbers-mode, so it was not moved between the
indirect buffers. Should be fixed in master.

**Comment by damiencollard** [comment]
On Sat, Apr 13 2019, Vitalie Spinu wrote:

>>   - Headers are not highlighted and their background looks the same as
>>   markdown's fenced code block background, while they're usually the same
>>   background as the mail's text.
>
> That's because gnus is now innermode. Just add `:adjust-face nil` to the
> declaration to get rid of the background.

Done!

>
>>   - `q`, which usually closes the article window, kills the buffer and
>>     goes back to the summary window (the list of e-mails) doesn't work
>>     and instead displays "Selecting deleted buffer".
>
> How do you install poly-gnus into gnus article? I use gnus so I can test
> this. So far I was testing it on the txt file which you provided.

I open an article with `C-u C-u g` (instead of `g`) either from the
summary buffer or from the article buffer itself, so no processing is
applied to the article (in particular, my current "discourse article"
treatment is not applied). Then, with the cursor in the article window,
I call `poly-gnus-article-mode` (which runs the latest version of the
code you posted).

>>   - `s`, which moves the focus to the summary window, makes the line
>>     numbers appear (I use `display-line-numbers-mode`).
>
> I was not aware of display-line-numbers-mode, so it was not moved between the
> indirect buffers. Should be fixed in master.

It works, thanks. There's a complication, though:

- Although I don't have `display-line-numbers-mode` enabled for
  `gnus-article-mode`, I have it enabled for `text-mode` which means
  it's also enabled for `markdown-mode`. This is what made the line
  numbers show up with `poly-gnus-article-mode`.

- The line numbers can't be disabled from the `gnus-article-mode` hook.
  I had to disable them from `text-mode` (or `markdown-mode`), but
  ideally I'd want to keep the line numbers enabled for these modes
  (for editing), so I tried using `poly-NAME-mode-hook` as follows:

```elisp
(add-hook 'poly-gnus-article-mode
          (lambda ()
            (setq display-line-numbers nil)))
```

It didn't work. Is this hook run after the parents' hooks?

**Comment by vspinu** [comment]
>> On Sat, Apr 13 2019 13:24, Damien Collard wrote:

> I open an article with `C-u C-u g` (instead of `g`) either from the

Good to know. Will try.

> It works, thanks. There's a complication, though: - Although I don't have
> `display-line-numbers-mode` enabled for `gnus-article-mode`,

If gnus-article-mode doesn't have it enable then it should never pop up in any
mode because, first, display-line-numbers variable is ported between polymode
buffers, second, you are actually never switching to markdown buffer. So I have
no idea how that could happen.

Can you form-ward a discuss email to me so that I can play with it from gnus?


> ```elisp
> (add-hook 'poly-gnus-article-mode

Did you forget the `-hook prefix`?

> It didn't work. Is this hook run after the parents' hooks?

Yes. It should run after both emacs modes and all polymode parents.

**Comment by vspinu** [comment]
>> On Sat, Apr 13 2019 12:02, Damien Collard wrote:

>   - `q`, which usually closes the article window, kills the buffer and
>     goes back to the summary window (the list of e-mails) doesn't work
>     and instead displays "Selecting deleted buffer".

I see this. Gnus traks origin when you press g from summary. I guess that that
origin (gnus-article-current-summary in this case) is lost or is wrong when we
set markdown-mode host and re-install gnus-article as an inner-mode.

From this prospective it would be really nice to have gnus-article as the host
mode and install poly-gnus as a minor mode. Uff ...

>   - `s`, which moves the focus to the summary window, makes the line

Actually this makes sense. markdown-mode is installed first, so the variables
are picked from there originally. But setting it in the -hook works.

**Comment by damiencollard** [comment]
On Sat, Apr 13 2019, Vitalie Spinu wrote:

> Can you form-ward a discuss email to me so that I can play with it
> from gnus?

Sure, sent to your gmail address.

>> ```elisp
>> (add-hook 'poly-gnus-article-mode
>
> Did you forget the `-hook prefix`?

Ahhh dammit. Yes I did! :-)
Now the line numbers are disabled as expected.

**Comment by vspinu** [comment]
The minor-mode works and polymode innermodes are highlighted as expected

```el

(define-polymode poly-gnus-article-mode poly-markdown-mode
  :hostmode 'poly-gnus-article-hostmode
  :innermodes '(:inherit poly-gnus-article-innermode)
  :keep-in-mode 'gnus-article-mode)
```

But everything else is gnus stuff and you want it markdown, so this won't work unless I can make  an inner span to hold an entire polymode which is a bit crazy.

Here is something that should work pretty easely, first cache all the variables that gnus needs (gnus-article-current-summary for example), then install the polymode and re-install all the variables back to normal in the gnus' indirect buffer.

**Comment by damiencollard** [comment]
On Sat, Apr 13 2019, Vitalie Spinu wrote:

>>> On Sat, Apr 13 2019 12:02, Damien Collard wrote:
>
>>   - `q`, which usually closes the article window, kills the buffer and
>>     goes back to the summary window (the list of e-mails) doesn't work
>>     and instead displays "Selecting deleted buffer".
>
> I see this. Gnus traks origin when you press g from summary. I guess that that
> origin (gnus-article-current-summary in this case) is lost or is wrong when we
> set markdown-mode host and re-install gnus-article as an inner-mode.

Yes, Gnus checks origin and liveness of buffers quite extensively...
Does the process of installing host mode and inner mode kill and
re-create the article buffer?

> From this prospective it would be really nice to have gnus-article as the host
> mode and install poly-gnus as a minor mode. Uff ...

Much more involved, I take it?

**Comment by vspinu** [comment]
> Does the process of installing host mode and inner mode kill and re-create the article buffer?

No. The hostmode is installed on top first, so the original gnus-article mode is wiped and that's the problem here. Then new gnus-article mode is installed in the new indirect buffer. 

So you basically have to move all relevant variables from the original article buffer to the new article buffer. This could be done in the `:init-functions` slot of the gnus-article-innermode.  Should be straightforward.

**Comment by damiencollard** [comment]
On Sat, Apr 13 2019, Vitalie Spinu wrote:

>> Does the process of installing host mode and inner mode kill and re-create the article buffer?
>
> No. The hostmode is installed on top first, so the original
> gnus-article mode is wiped and that's the problem here. Then new
> gnus-article mode is installed in the new indirect buffer.
>
> So you basically have to move all relevant variables from the original
> article buffer to the new article buffer. This could be done in the
> `:init-functions` slot of the gnus-article-innermode.  Should be
> straightforward.

Ok, I'll try that and report back.
Thank you.

**Comment by vspinu** [comment]
Over the night I got an idea. This is all what's needed with the most recent polymode:

```el
(defun poly-gnus-article-body-start (ahead)
  (let ((beg (save-excursion (message-goto-body) (point))))
    (and (if (> ahead 0) (<= (point) beg) (<= beg (point)))
         (cons beg beg))))

(define-innermode poly-gnus-markdown-innermode
  :mode 'markdown-mode
  :head-matcher #'poly-gnus-article-body-start
  :tail-matcher "\\'"
  :allow-nested 'always
  :adjust-face nil)

(define-polymode poly-gnus-article-mode poly-markdown-mode
  :hostmode nil
  :innermodes '(:inherit poly-gnus-markdown-innermode)
  :keep-in-mode 'host)
```
One small issue is that fenced code heads are no longer highlighted by the markdown-mode, but I guess it's a small price to pay I would say. It can be fixed easily by changing :head-mode and :tail-mode slots in installed configs once the mode is on. Those configs are in `-innermodes` slot of the `pm/polymode` objects. 

I actually realized that from this to allowing entire nested `polymodes` inside `:mode` slot is one step. It doesn't sound crazy any longer :)

**Comment by damiencollard** [comment]
On Sun, Apr 14 2019, Vitalie Spinu wrote:

> Over the night I got an idea. This is all what's needed with the most
> recent polymode:
>
> ```el
> (defun poly-gnus-article-body-start (ahead)
>   (let ((beg (save-excursion (message-goto-body) (point))))
>     (and (if (> ahead 0) (<= (point) beg) (<= beg (point)))
>          (cons beg beg))))
>
> (define-innermode poly-gnus-markdown-innermode
>   :mode 'markdown-mode
>   :head-matcher #'poly-gnus-article-body-start
>   :tail-matcher "\\'"
>   :allow-nested 'always
>   :adjust-face nil)
> ```

This fails for me: 'always is not accepted, it requires a boolean (on
up-to-date master branch of polymode). So I modified it to
`:allow-nested t` -- not sure if this has an impact on my results below.

> One small issue is that fenced code heads are no longer highlighted by
>   the markdown-mode, but I guess it's a small price to pay I would
>   say. It can be fixed easily by changing :head-mode and :tail-mode
>   slots in installed configs once the mode is on. Those configs are in
>   `-innermodes` slot of the `pm/polymode` objects.

I agree, that's a very small price, even more so since in my case the
goal is to make the mail as legible as possible ; and anyway can add
display properties if needed (I already do so in the mail treatment).

> I actually realized that from this to allowing entire nested
> `polymodes` inside `:mode` slot is one step. It doesn't sound crazy
> any longer :)

That's great news!

In my testing the code you just posted (on up-to-date master branch for
both `polymode` and `poly-markdown`), I don't get the fenced code blocks
syntax-highlighted. Instead, the whole text in the blocks is highlighted
the same, as if no language were specified in the fenced block header.

Here's the code I eval in its entirety, maybe I missed a step? Or is it
my replacing `:allow-nested 'always` with `:allow-nested t`?

```el
;; Both at
(add-to-list 'load-path "...path to.../polymode/")
(add-to-list 'load-path "...path to.../poly-markdown/")

(require 'poly-markdown)

(defun poly-gnus-article-body-start (ahead)
  (let ((beg (save-excursion (message-goto-body) (point))))
    (and (if (> ahead 0) (<= (point) beg) (<= beg (point)))
         (cons beg beg))))

(define-innermode poly-gnus-markdown-innermode
  :mode 'markdown-mode
  :head-matcher #'poly-gnus-article-body-start
  :tail-matcher "\\'"
  :allow-nested t ;; was 'always
  :adjust-face nil)

(define-polymode poly-gnus-article-mode poly-markdown-mode
  :hostmode nil
  :innermodes '(:inherit poly-gnus-markdown-innermode)
  :keep-in-mode 'host)

(pm-around-advice #'mm-enable-multibyte #'polymode-with-current-base-buffer)
(pm-around-advice #'mm-disable-multibyte #'polymode-with-current-base-buffer)
```

**Comment by vspinu** [comment]
Arh. Sorry. Forgot to push. Please try again. Advice is no longer needed as gnus stays in the original buffer and is not replaced.

**Comment by damiencollard** [comment]
Thanks, it works! I also noticed that my hook to disable line numbers is no longer required either.

Apart from the headers not being highlighted (which we already discussed and which I'll look into), the only problem I currently see is that while links can be followed by clicking, they can't with RET (with point on them): it issues error "Buffer is read-only". All other key bindings seem to work well.

**Comment by damiencollard** [comment]
When both `poly-gnus-article-mode` and my Discourse treatment are active, the result is very interesting: 

- `poly-gnus-article-mode` highlights both fenced code blocks and regular text.
- The treatment then applies its own transformations on the fenced code blocks.
- The treatment adds links to user profiles, etc.
- The treatment makes RET on links work.

It's starting to look very good, and I should be able to cut down a lot of code in `discourse-article`.

**Comment by vspinu** [comment]
>  they can't with RET 

This is expected. Those links are from markdown mode, not gnus anymore. They are clickable but not RETable because markdown is not designed for read-only mode. You will have to add a bit of extra logic. 

> It's starting to look very good, and I should be able to cut down a lot of code in discourse-article.

Cool. Let me know when you are done. I wold like to add a page with links to polymode based modes. This one is definitely very special.

**Comment by damiencollard** [comment]
On Sun, Apr 14 2019, Vitalie Spinu wrote:

> Cool. Let me know when you are done.

Will do!

**Comment by damiencollard** [comment]
Just fyi, I fixed the article headers losing their highlighting: it was just a matter of replacing `:hostmode nil` with `:hostmode 'gnus-article-mode` in the last snippet you posted:

```el
(define-polymode poly-gnus-article-mode poly-markdown-mode
  :hostmode 'gnus-article-mode ;; was nil
  :innermodes '(:inherit poly-gnus-markdown-innermode)
  :keep-in-mode 'host)
```

**Comment by vspinu** [comment]
Hmm, those should have been equivalent in this particular case :/ On nil,
host mode is picked from the currently installed mode.

**Comment by damiencollard** [comment]
Yes, I spoke too soon: I hadn't noticed an error in my code that led to
the polymode not being applied. I deleted my post right away but I guess
you received the notification. Sorry for the noise.

I'm investigating the problem, and I think in this case the innermode
(markdown) may be "spilling" out of its head boundary.

If I modify `poly-gnus-article-body-start` (see below) to move point
past the first fenced code block (in the sample e-mail I forwarded you),
that first code block is highlighted by markdown even though it
shouldn't.

```el
(defun poly-gnus-article-body-start (ahead)
  (let ((beg (save-excursion (message-goto-body) (forward-line 10) (point))))
    (and (if (> ahead 0) (<= (point) beg) (<= beg (point)))
         (cons beg beg))))
```

(Note the added `(forward-line 10)`.)

**Comment by vspinu** [comment]
>  "spilling" out of its head boundary.

Not really. If you save the email and do `M-x gnus-article-mode` you won't see any highlighting. 

I think more likely gnus has a single pass in the begining and highlights everything once without the font-lock machinery, then those properties are erased in the process of polymode instalation, but never put back because gnus doesn't have the font-lock setup. Can be?

>  markdown even though it shouldn't.

Works as expected for me. Markdown highlights from the line where the new function returns the start, exactly 10 lines below the 
![Screenshot_20190416_205410](https://user-images.githubusercontent.com/1363467/56236428-d90ffb00-6089-11e9-92dc-f9e6ee27c7b0.png)

**Comment by damiencollard** [comment]
On Tue, Apr 16 2019, Vitalie Spinu wrote:

>>  "spilling" out of its head boundary.
>
> Not really. If you save the email and do `M-x gnus-article-mode` you won't see any highlighting. 
>
> I think more likely gnus has a single pass in the begining and
> highlights everything once without the font-lock machinery, then those
> properties are erased in the process of polymode instalation, but
> never put back because gnus doesn't have the font-lock setup. Can be?

This may be true, but once these properties are erased, you can re-add
them (the highlighting, at least) with `(gnus-summary-toggle-header -1)`
but you'll see that the highlighting only briefly flashes before being
erased again.

>>  markdown even though it shouldn't.
>
> Works as expected for me. Markdown highlights from the line where the
> new function returns the start, exactly 10 lines below the
> ![Screenshot_20190416_205410](https://user-images.githubusercontent.com/1363467/56236428-d90ffb00-6089-11e9-92dc-f9e6ee27c7b0.png)

In your screenshot, is the cursor at body start + 10? If so, we're not
working on exactly the same e-mail, possibly because you have the sample
I use as an attachment while I'm using the "original" e-mail.

Here's where body start + 10 is on my sample:



Shouldn't the first fenced code block *not* be highlighted since it's
located before the innermode start?

**Comment by damiencollard** [comment]
It seems the picture didn't go through by mail (?) Here it is:

![first-fenced-code-block-shouldnt-be-highlighted--annotated](https://user-images.githubusercontent.com/4697338/56244625-a1ab4980-609d-11e9-8848-648516fda222.png)
