### ISSUE TITLE
make start should use EMACSBATCH

### ISSUE THREAD

**Issue by slyrus** [polymode/polymode#220]
make start (and make startvs) use $(EMACSRUN) instead of $(EMACSBATCH), so I end up with my emacs processing puking on non-safe local variables.

**Comment by vspinu** [comment]
They do use EMACSRUN. The batch wouldn't start the interactive session. I am not sure how to deal with this problem cleanly. For now, I just fix this by explicitely requiring the relevant library in melpa-init.el which both "start"s use.

**Comment by slyrus** [comment]
vspinu, sorry for being dense but I don't understand your response at all. Perhaps I wasn't clear. The problem, as I see it, is that start and startvs currently use EMACSRUN. Among other things, this means that bad things happen if you try to do make start all from a shell inside an emacs buffer. The only way I can get things to build is to manually change EMACSRUN to EMACSBATCH in those targets. I'm not sure why one would want an interactive shell to pop up in a make target, but, hey, I'm probably missing something. Thanks!

**Comment by vspinu** [comment]
Those targets are for starting emacs -Q from outside of emacs to provide clean bootstrap experience. They are not designed to be used from an emacs shell.

**Comment by slyrus** [comment]
I'm not sure I understand what's supposed to happen here. Maybe this is explained, but what's the best way to build polymode and the modes? I generally update polymode and the various, cd into each of the modes and do:

```
make start
```
which downloads a bunch of stuff from MELPA then brings up an emacs buffer (that I have no idea what to do with). Then I do:
```
make
```
and the *.el's are byte-compiled and the tests run.

Is there a better way to do all of that? What is the purpose of bringing up a buffer? Why can't all of that be run from an emacs sh buffer?

thanks!

**Comment by vspinu** [comment]
> I generally update polymode and the various,

So you install and then load from source? Then `git pull` and that's it. This will avoid various cross compilation issues when you use different versions of emacs. If you want to byte-compile then `make elpa` will download all dependencies and then `make` to build and test. `make build` will just build. 
I will add `elpa` to `all` target to avoid the confusion, so you could just `make`. 

Goes without saying that, unless you want to develop on polymode, the preferred way is install is from MELPA.
