### ISSUE TITLE
`pm--run-shell-command: Text is read-only` when weaving document a second time

### ISSUE THREAD

**Issue by tmalsburg** [polymode/polymode#221]
When I weave my `.Rnw` document the first time, it works as expected (using knitr).  However, when I edit it and try weaving again, I get an error:

    pm--run-shell-command: Text is read-only

I think the cuplprit is the buffer `*polymode-weave*`.  When I delete it, weaving again works (but just one time).

Using a recent development Emacs with polymode, poly-noweb, and poly-R installed from MELPA.

**Comment by vspinu** [comment]
Could you please `M-x toggle-debug-on-error` and let me know the trace? I don't see this locally. 

Which text is read-only, in `*polymode-weave*` buffer? Do you have some hook which makes text read-only in some buffer?

You can always check if it's local issue or polymode by doing `make start` from the `poly-R` repo.

**Comment by vspinu** [comment]
I have made some tiny changes in the `pm--run-shell-command`, but shooting in the dark. Let's see if it helps with your issues.

**Comment by tmalsburg** [comment]
Thanks you. I'll have a closer look and will report back when I have something.

**Comment by vspinu** [comment]
@tmalsburg any news on this one?
