### ISSUE TITLE
Emscripten EM_ASM and EM_JS macro support

### ISSUE THREAD

**Issue by jdwissler** [polymode/polymode#224]
[Emscripten](https://emscripten.org/) has ways to write Javascript within C++ with the `EM_JS` and `EM_ASM` [macros](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-javascript-from-native), e.g:

```
EM_ASM(
    alert('hello world!');
    throw 'all done';
  );
```

I'd like to create a Javscript innermode for this macro. Obviously a regular expression for the `tail-matcher` won't work since `);` is all throughout the Javascript code. The only solution I've come up with is to add a comment at the end of the `EM_ASM` macro and use that for the `tail-matcher`:

```
EM_ASM(
    alert('hello world!');
    throw 'all done';
   // EM_ASM_END
  );
```

Is there a better way? Maybe polymode has a open/close parentheses stack?

**Comment by vspinu** [comment]
Either make `)` alone on the line like in `"^[ \t]*)$` or make the tail matcher a function which will call forward-list. `tail-matcher` is called at the end of the head only with `+1` argument, so you can ignore the more complicated case of search backward.

**Comment by vspinu** [comment]
@jdwissler BTW, if you have a working solution, could you please post it here for the future reference? Others might find it useful.
