### ISSUE TITLE
polymode seems to break indirect buffer

### ISSUE THREAD

**Issue by dankessler** [polymode/polymode#225]
I first noted that org-capture seemed broken (#40, i.e., when trying to use `org-capture` rather than giving me a narrowed indirect buffer, I'd get kicked directly to the base-buffer), but after more experimentation it seems that when in a poly-mode enabled file, it doesn't seem possible to visit indirect buffers anymore. Given that indirect buffers is kind of fundamental to how polymode works, this doesn't seem like a coincidence.

I've tested this in r markdown files (`.Rmd`) and org files (`.org`) and in either case, if visiting one of these files while polymode is enabled, calling `clone-indirect-buffer` successfully creates an indirect buffer (i.e., it shows up in the buffer list) but it is impossible to switch to that buffer: any attempt to switch just results in the user visiting the base buffer. I assume there's something in the way polymode is implemented that prevents users from directly visiting indirect buffers for a polymode-enabled buffer, since that would make break some of the magic, but unfortunately it breaks tools that rely on indirect buffers in other ways (e.g., `org-capture`) to do their work.

**Comment by vspinu** [comment]
Thanks for digging this far. It's indeed fundamental to how polymode works as it doesn't invisage visiting indirect buffers, because the buffers which you visit in polymode are already indirect buffers. 

Shouldn't be hard to fix. I will have a look.

**Comment by dankessler** [comment]
Excellent! I'm sure @vspinu has a much better insight into this than me, but as I was thinking more about this and my guess is that in a literal sense one *can* switch to an indirect-buffer, but then the `polymode` logic kicks in and switches one to the appropriate buffer based on where point is.

As an experiment which seems to confirm this intuition, I tried the following:

1. Visit an `.Rmd` file that has a mix of markdown, LaTeX, and R code in fenced blocks
2. Run `clone-indirect-buffer`
3. Check the buffer list to confirm that the indirect buffer was created (it ends in `<2>`)
4. Try switching to that buffer; it seems to fail
5. Instead, run `display-buffer` and choose the indirect buffer
6. Observe that a new window is created that displays the desired indirect buffer
7. Switch windows, activating point in the indirect buffer, and observe that it *immediately* toggles back to either the host buffer or the mode-specific indirect buffer based on where point is

so it does sound like switching works but that emacs switches back so fast it's invisible to the user.

I'm not sure where in the codebase is the logic that `polymode` uses to implement its slick point-based indirect-buffer switching that undergirds the `polymode` functionality, but if I can find that (or is @vspinu can point me towards it) I imagine I may have a better understanding of this and can also see if I can think of a fix, although if this is something you think you can get to soon, @vspinu , let me know and I'll not duplicate your more valuable effort :)

**Comment by vspinu** [comment]
> but then the polymode logic kicks in and switches one to the appropriate buffer based on where point is.

This is indeed what's going on. The fix would be relatively easy as polymode tracks all indirect buffers it creates, but I am not sure about the UI.  Particularly. Do you want your indirect buffer to be always in the host mode? What should happen when you move to the inner chunk? What happens if you call clone-indirect-buffer from an inner-chunk?

**Comment by vspinu** [comment]
Non-polymode indirect buffers are now allowed. Font lock works there as expected but the mode is the host mode throughout. I think this makes most sense as cloning always happens from the base buffer.

**Comment by dankessler** [comment]
Thanks! I agree that this is the most sensible implementation. I skimmed the diff and learned a bit more about how polymode works in the process. Thanks for a very useful package and a quick fix :)
