### ISSUE TITLE
occasionally gets stuck searching and moving around

### ISSUE THREAD

**Issue by rdiaz02** [polymode/polymode#227]
I removed markdown-mode, and all poly*. I reinstalled and have:

- markdown-mode (20190305.319)
- poly-markdown (20190415.1547)
- poly-noweb (20190317.1352)
- poly-R (20190504.1020)
- polymode (20190508.1847)

I experience occasional and hard to reproduce problems when moving around: e.g., going to the beginning or end of buffer, or jumping from one to the other, it sometimes can get stuck for over 10 seconds, with emacs using close to 100% of a CPU. Sometimes when searching (isearch) I find similar behavior.
I experience no problem with markdown-mode itself. (The file opens immediately, and moving around, and searching feel faster than with polymode enabled).

I have been playing with this moderately sized file:  https://github.com/rdiaz02/OncoSimul/blob/freq-dep-fitness/OncoSimulR/vignettes/OncoSimulR.Rmd

**Comment by vspinu** [comment]
Do you see these kind of messages?

```
ERROR: (markdown-syntax-propertize 23762 45092) -> Too much matching reentrancy
Error during redisplay: (internal--syntax-propertize 42835) signaled (error "Too much matching reentrancy")
```

I see them in the plain markdown as well.

**Comment by vspinu** [comment]
This is emacs dependent. What version is this?

**Comment by rdiaz02** [comment]
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.4) of 2019-02-03, modified by Debian

**Comment by vspinu** [comment]
When you jump to the end of the buffer emacs needs to `syntax-propertize` the entire buffer. But that means that all chunks must be discovered. As you have hundreds (maybe thousands) of spans, this takes a while.

Unfortunately I don't see how this could be avoided in a general case. It's a tough one.

**Comment by vspinu** [comment]
This one was hard but fixing it propelled polymode to a much higher ground. Things at the core are done differently now, 20x more efficiently for some contexts like yours. 

You will still see a short delay when you jump to the end of your file, but that's unavoidable as `syntax-propertize` must do its work and you have 2420 distinct spans in the file which all must be detected. 

Let me know if you still see something amiss.

**Comment by rdiaz02** [comment]
Thanks!! Yes, it is a lot speedier now (the delay jumping to the end is not a problem anymore).
