### ISSUE TITLE
No fontification is happening for polymode buffers.

### ISSUE THREAD

**Issue by vlurgio** [polymode/polymode#231]
I'm getting no fontification at all in poly mode buffers. The fontification works as if I call `  (poly-lock-fontify-now (point-min) (point-max))` I get a pretty fontified buffer. This function just isn't getting called. I'm not getting any errors either. I've tried to read through the source code and see why this is happening, but can't seem to figure out what controls the fontification. I'm noticing this in .Rmd files with `poly-markdown+r-mode`. I'd like to get this working as having to do it manually every time I type isn't overly efficient. 

This is my config for polymode
```
  (use-package polymode
    :ensure t
    :config
    (markdown-toggle-fontify-code-blocks-natively)
    )
  (use-package poly-R
    :mode
    ("\\.rmd\'" . poly-markdown+r-mode)
    ("\\.Rmd\'" . poly-markdown+r-mode))
  (use-package poly-markdown
    :mode
    ("\\.md\'" . poly-markdown-mode))
```

**Comment by vspinu** [comment]
Is this recent? Do you have some global font-lock configuration somewhere (like disabling it or something)? Can you do `M-x pm-debug-print-relevant-variables` from an Rmd buffer and post here?



> (markdown-toggle-fontify-code-blocks-natively)

This is not needed. You are making it much worse performance wise.

**Comment by vspinu** [comment]
> ("\\.rmd\'" . poly-markdown+r-mode)

All these auto-mode setups are not needed either. They are added automatically.

**Comment by vspinu** [comment]
It's most likely your local setup. Would be interesting to know what is causing it. Try bisecting your config. 

You can also git-clone `poly-R` repository and do `make start` from within. It will download all the dependencies and will start a clean emacs. If fontification works from there, it means it's your configuration that is causing it.

**Comment by vlurgio** [comment]
This is `pm-debug-print-realtive-variables` while I see if anything in my config is messing with fontification.
```
================== test.rmd ===================
((:change
  (before-change-functions)
  (after-change-functions polymode-flush-syntax-ppss-cache t markdown-gfm-checkbox-after-change-function))
 (:command
  (pre-command-hook polymode-pre-command-synchronize-state eldoc-pre-command-refresh-echo-area evil--jump-hook company-pre-command t)
  (post-command-hook evil-normal-post-command linum-update-current polymode-post-command-select-buffer eldoc-schedule-timer company-post-command yas--post-command-handler t))
 (:font-lock
  (fontification-functions)
  (font-lock-function . poly-lock-mode)
  (font-lock-flush-function . jit-lock-refontify)
  (font-lock-ensure-function . jit-lock-fontify-now)
  (font-lock-fontify-region-function . font-lock-default-fontify-region)
  (font-lock-fontify-buffer-function . jit-lock-refontify)
  (font-lock-unfontify-region-function . font-lock-default-unfontify-region)
  (font-lock-unfontify-buffer-function . font-lock-default-unfontify-buffer)
  (jit-lock-after-change-extend-region-functions font-lock-extend-jit-lock-region-after-change t markdown-font-lock-extend-region-function)
  (jit-lock-functions font-lock-fontify-region)
  (poly-lock-defer-after-change . t))
 (:search
  (parse-sexp-lookup-properties . t)
  (case-fold-search . t))
 (:indent
  (indent-line-function . pm-indent-line-dispatcher)
  (indent-region-function . pm-indent-region)
  (pm--indent-line-function-original . markdown-indent-line))
 (:revert
  (revert-buffer-function . revert-buffer--default)
  (before-revert-hook tramp-flush-file-function)
  (after-revert-hook doom-modeline-update-buffer-file-name doom-modeline-update-buffer-file-state-icon turn-on-solaire-mode))
 (:save
  (after-save-hook t markdown-live-preview-if-markdown)
  (before-save-hook)
  (write-contents-functions)
  (local-write-file-hooks)
  (write-file-functions appt-update-list recentf-track-opened-file undo-tree-save-history-hook))
 (:syntax
  (syntax-propertize-function . polymode-syntax-propertize)
  (syntax-propertize-extend-region-functions markdown-syntax-propertize-extend-region syntax-propertize-wholelines)
  (pm--syntax-propertize-function-original . markdown-syntax-propertize)))
```
As for the markdown mode that was just so i could hit `M-o M-o` in the mardown portion at first to at least get some syntax highlighting, but it's not being used now. The `:mode`s aren't needed for configuring when to use them but they make sure the packages aren't loaded unless I open an Rmd buffer because of use-package's functionality.

**Comment by vlurgio** [comment]
Only thing In my config I see that would mess with fontification is doom-one theme but I can't imagine that's causing this 
[emacs.html.zip](https://github.com/polymode/polymode/files/3237678/emacs.html.zip)
I've attached my config above if you wanted to take a look. It's gigantic but at least literate haha.

**Comment by vlurgio** [comment]
I does seem that the first function in `:font-lock` in `pm-debug-print-relative-variables`, `(fontification-functions)` is undefined anywhere so I'm not sure where that's coming from

**Comment by vlurgio** [comment]
Ok I got somewhere by installing the melpa version of ess instead of cloning from git. Don't know why that had anything to do with it. It's still a little wonky. I use evil mode and it seems to only refontify if I'm in insert mode in a chunk. It also recolors the whole bufffer as whatever the syntax in that chunk is. For example if I go into insert mode in an R chuck, the whole buffer get's fontified as R inlcuding the markdown.

**Comment by vspinu** [comment]
Indeed. fontification-function should be `poly-lock-function`. Something must be throwing it away for you. 

People use polymode with evil and it should work fine (except of #228). Can you see this with bare-bones emacs, polymode and evil? It could be some crazy interaction with some other package in your setup. I presume you are using the most recent polymode and poly-r, right?

**Comment by vlurgio** [comment]
Yeah all my versions are exactly the same as those in the `make start` version of poly-R and it does work in that version for me. I'll have to keep playing with it. Will report back if I get it to work better.

**Comment by vlurgio** [comment]
So finally fixed it. moving from `use-package` to just using `require` fixed the problem. My config is tangled and compiled from the command line then emacs.elc is the actual config have a feeling this made it not work some. Thanks for you help!

**Comment by domq** [comment]
In my own case, deleting `.emacs.desktop` and restarting Emacs helped. This is not the first time I notice `desktop.el` having a tendency to save too much of the state. Hope this helps.
