### ISSUE TITLE
Please help us to see polymode as a dependency of ein

### ISSUE THREAD

**Issue by yefeiyu** [polymode/polymode#232]
https://github.com/millejoh/emacs-ipython-notebook/issues/556

**Comment by vspinu** [comment]
How can I help? I see that @dickmao made some extensive fixes recently but thing seem to be a bit hacky still. Shouldn't polymode be just working in ein buffers once chunk boundaries are defined?

**Comment by dickmao** [comment]
I would close this issue.  The maintainers of polymode should not be concerned with ein.

**Comment by vspinu** [comment]
Though it becomes a concern when ein modifies the core behavior of polymode in a such a way that it  affects other modes.
