### ISSUE TITLE
Add option to change remote shell file name?

### ISSUE THREAD

**Issue by yiufung** [polymode/polymode#252]
First thanks for developing this great package. I use it daily and enjoy it a lot. 

My workflow is as follows:
1. Write `Rmd` document in remote VM. Edit with TRAMP.
2. Use `M-n e` to export as HTML.

When I export, there's error in buffer `*polymode export*`:

```
Exporting Rmarkdown-->html with command:

     Rscript -e "rmarkdown::render('test.Rmd', output_format = 'html_document', output_file = 'test-exported.html')"

env: ‘/usr/bin/zsh’: No such file or directory
```

The cause is that I use `zsh` locally, while the remote VM uses `/bin/bash`. Dig through the source code of `pm--run-shell-command`, I changed the value of `shell-file-name` and, viola, it works. 

Then I thought I should set it as directory variables using `.dir-locals.el`. And it was set. But when I export in polymode again, it fails with same error again. The reason is that `pm--run-shell-command` is still using system-wide `shell-file-name`. 

Is there an easy way to fix this? It seems a low hanging fruit to enable more fluent remote editing experience.

**Comment by vspinu** [comment]
Sorry for coming late on this. I am myself on zsh locally so would face the same issue. 

Did you have a chance to figure it out? Could it be that TRAMP ignores the buffer local value? 

For some reason I have this in my config:

```el
(eval-after-load 'tramp
  '(progn
     (setenv "SHELL" "/bin/bash")
     (setenv "ESHELL" "/bin/bash")))
```
Don't recall anymore what was the reason behind it.

**Comment by yiufung** [comment]
I don't have the two lines, and `(getenv "SHELL")` returns `/usr/bin/zsh` with `(getenv "ESHELL")` returns nil. 

Perhaps that's the case. I seldom do remote editing Rmd any more, but good to have this conversation. Someone may find it useful in the future.
