### ISSUE TITLE
`adjust-face` works differently in recent emacs version?

### ISSUE THREAD

**Issue by bk322** [polymode/polymode#256]
Here's a small snippet:

    (require 'cl)

    (setq load-path
          (append
           (cl-map 'list 'expand-file-name
                   '("~/.emacs.d/elpa/polymode-20191208.1239/"
                     "~/.emacs.d/elpa/markdown-mode-20191230.1055/"
                     "~/.emacs.d/elpa/poly-markdown-20190916.702/"))
           load-path))

    (require 'poly-markdown)
    (poly-markdown-mode)

    ```elisp
    (setq load-path
          (append
           (cl-map 'list 'expand-file-name
                   '("~/.emacs.d/elpa/polymode-20191208.1239/"
                     "~/.emacs.d/elpa/markdown-mode-20191230.1055/"
                     "~/.emacs.d/elpa/poly-markdown-20190916.702/"))
           load-path))
    ```

If I `eval-buffer` that snippet with `emacs -Q` in 2019-07-24 version of emacs I get:

![270](https://user-images.githubusercontent.com/875273/71646372-9a45d200-2cf8-11ea-9e3b-d699fc5dee10.png)

If I do the same with any recent version of emacs, say 2020-01-01, I get

![271](https://user-images.githubusercontent.com/875273/71646373-a03bb300-2cf8-11ea-9998-9e34fabd8e87.png)

`adjust-face` "folding" (or "wrapping") inner-mode chunk is different between the two versions. Is there a way to restore the old adjust-face in the recent versions of emacs?

**Comment by bk322** [comment]
Turns out the issue is caused by the new face property called `:extend`, which appears in Emacs 27.0.60+:

```
** New face attribute ':extend' to control face extension at EOL.
The new face attribute ':extend' controls whether to use the face for
displaying the empty space beyond end of line (EOL) till the edge of
the window.  By default, this attribute is non-nil only for a small
number of faces, notably, 'region'; any other face that crosses end of
line will not affect the display of the empty space at EOL.  This is
to make Emacs behave more like other GUI applications with respect to
displaying faces that cross line boundaries.
```

The fix is simply:

```elisp
(defun poly-lock-adjust-span-face (span)
  "Adjust 'face property of SPAN..
How adjustment is made is defined in :adjust-face slot of the
SPAN's chunkmode."
  (interactive "r")
  (let ((face (pm-get-adjust-face (nth 3 span) (car span))))
    (let ((face (if (numberp face)
                    (unless (= face 0)
                      (list (list
                             :background (poly-lock--adjusted-background face)
                             :extend t ;; added this line
                             )))
                  face)))
      (when face
        (font-lock-append-text-property
         (nth 1 span) (nth 2 span) 'face face)))))
```

**Comment by vspinu** [comment]
Thanks for tracking this. Any idea of how to check if `:extend` property is available except for relying on the emacs version check?

**Comment by vspinu** [comment]
Figured it out, there is a new function `set-face-extend`.
