### ISSUE TITLE
Inner mode prefix text

### ISSUE THREAD

**Issue by astoff** [polymode/polymode#257]
Is is possible to stipulate that each line of an inner mode has a prefix, which should be invisible to the inner mode?  A use case would be to render and edit long comments in markdown mode.  So, for instance, in the following Python code

```python
# # Some heading
#
# Some text, etc.
```

the prefix would be `# ` and the text as seen by the inner markdown mode would be

```markdown
# Some heading

Some text, etc.
```

**Comment by vspinu** [comment]
No, unfortunately this is not possible with the current design of polymode. It would be pretty hard in emacs in general. There is a mode somewhere (I forgot the name) which opens a mirror buffer without comments and allows you to edit the original and see the output without comments and vice-versa.
