### ISSUE TITLE
Make parts of head/tail belong to outer, and other parts belong to inner mode.

### ISSUE THREAD

**Issue by NobbZ** [polymode/polymode#259]
I currently try to use `polymode` to have highlighting of my `elisp` and `sh` snippets in `nix` files.

I've started with only doing `nix` + `elisp`, as `elisp` snippets are a lot more common for me currently (as I'm configuring `emacs` through `nix`):

```elisp
(add-to-list 'auto-mode-alist '("\\.nix$" . poly-nix-mode))

(define-hostmode poly-nix-hostmode :mode 'nix-mode)

(define-innermode poly-elisp-expr-nix-innermode
  :mode 'emacs-lisp-mode
  :head-matcher "''\n *;;.*\n"
  :tail-matcher " *'';$"
  :head-mode 'host
  :tail-mode 'host)

(define-polymode poly-nix-mode
  :hostmode 'poly-nix-hostmode
  :innermodes '(poly-elisp-expr-nix-innermode))
```

This makes the embedded `elisp` look nice.

Though the initial "marker line" is highlighted as a `nix` string, while it should be an `elisp` comment.

It would be nice to apply modes per "submatch". Perhaps using matchgroups?

Given the matcher `(?<delim>''\n *)(?<lisp>;;.*\n)`, I'd like be `delim` be `host` and `lisp` be `inner`.

**Comment by vspinu** [comment]
If you want your head/tail to be in elisp then you should say `:head-mode 'body` instead of `'head`. 

Regarding the sub-expression, `:head-matcher` and `:tail-matcher` can be cons lists `(regexp . submatch)` see the docs for `pm-inner-chunkmode`. 

The above should solve your of your issues, please give me an example and I will cook something for you.

**Comment by NobbZ** [comment]
I don't see how this will help me to have the `''\n` of the head beeing in host-mode while the line containing the comment is in body-mode.

```nix
programs.emacs.extraConfig = ''
      ;; polymode
      (add-to-list 'auto-mode-alist '("\\.nix$" . poly-nix-mode))

      (define-hostmode poly-nix-hostmode :mode 'nix-mode)

      (define-innermode poly-elisp-expr-nix-innermode
        :mode 'emacs-lisp-mode
        :head-matcher "'''\n *;;.*\n"
        :tail-matcher " *''';$"
        :head-mode 'host
        :tail-mode 'host)

      (define-polymode poly-nix-mode
        :hostmode 'poly-nix-hostmode
        :innermodes '(poly-elisp-expr-nix-innermode))
    '';
```

In this example, everything in the quote but `;; polymode` is in emacs-lisp mode, while everything else, including the `;; polymode` is in hostmode (and therefore `;; polymode` highlighted as a string.

**Comment by vspinu** [comment]
Something like this 
```el
  :head-matcher (cons "'''\n *\\(;;.*\\)$"  1)
  :head-mode 'body
```

**Comment by NobbZ** [comment]
Thanks that worked!

**Comment by vspinu** [comment]
Great, could you please post the entire solution here? Others might find it useful.

**Comment by NobbZ** [comment]
Sure.

```elisp
(define-innermode poly-elisp-expr-nix-innermode
  :mode 'emacs-lisp-mode
  :head-matcher (cons "''\n\\( *;;.*\n\\)" 1)
  :tail-matcher " *'';$"
  :head-mode 'body
  :tail-mode 'host)
```
