### ISSUE TITLE
Setting my own indent function.

### ISSUE THREAD

**Issue by charJe** [polymode/polymode#269]
I have set up a rather complex polymode for [html inside common lisp](https://github.com/moderninterpreters/markup/). I have everything working except the indentation. I wrote my own indentation function that works for both html and lisp, so it could just be used anywhere; the problem is that I can't get it to be activated correctly. What is the proper way to do this. I know that `indent-line-function` is `pm-indent-line-dispatcher`. It seems I cannot change that, and I'm not sure how to modify it's functionality to call my function.

**Comment by vspinu** [comment]
One way to do that is to define your own chunkmode class and define `pm-indent-line` method for it.

Basically (tested with `poly-rd-mode`):

```el
(defclass pm-cool-inner-chunkmode (pm-inner-chunkmode) () "Some doc")

(defvar poly-cool-innermode
  (pm-cool-inner-chunkmode :name "cool-innermode"
                           :mode 'R-mode
                           :head-mode 'host
                           :head-matcher 'pm--rd-head-matcher
                           :tail-matcher 'pm--rd-tail-matcher))

(cl-defmethod pm-indent-line ((_chunkmode pm-cool-inner-chunkmode) span)
  (indent-line-to 10))
```

You can also define your own `def` macro for this class if you need to expose it to other users with the help of `polymode--define-chunkmode`. See [`define-innermode`](https://github.com/polymode/polymode/blob/2a61fb6d3e805bc0e4ca7b6510510a955c6bfb6a/polymode-core.el#L274) for an example.

But I wonder if `inner-html` mode could be fixed generically to work everywhere. It would be helpful to a lot of people. So, maybe instead of writing own custom indentation for html from scratch we could fix the nhtml indentation to work with polymode. WDYT?

**Comment by charJe** [comment]
I was looking for a `:indent-function` slot for `define-innermode` and `define-hostmode`

I had define the method for the hostmode as well: 
```lisp
(defclass pm-lisp-host-chunkmode (pm-host-chunkmode) () "Chunkmode for lisp.")
(defvar poly-lisp-hostmode
  (pm-lisp-host-chunkmode
   :mode 'lisp-mode))
(defmethod pm-indent-line ((_chunkmode pm-lisp-host-chunkmode) span)
  (lisp-html-indent-line))
```
After that it works perfectly!

A fixed inner html mode would be useful due to the large number of embeded html packages there are (lisp, js, ts, php). You can see my [indent function](https://github.com/charJe/.emacs.d/blob/master/charles/poly-lisp-html.el) is not very complicated: just figure out from context to do sgml-indent-line or indent according to host-mode. It should be doable.

**Comment by charJe** [comment]
I would like to add that while implementing indentation for inner-html shouldn't be too much trouble, having generic `:head-matcher` and `:tail-matcher` (especially tail) would be troublesome.

**Comment by vspinu** [comment]
Do you really need custom indentation for the host? I would expect common lisp indentation won't be that picky, so the default would work. 

BTW, any reason why not replacing `indent-line-function` and `indent-region-function` directly in the poly-xyz-mode would not work for you?

**Comment by charJe** [comment]
sometimes it is desirable for `sgml-indent-line` to be called from `lisp-mode`:
```html
<head>
    <title>,(prog|n title)</title>
</head>
```
or
```html
<body>
    ,@(pr|ogn children)
</body>
```
where `|` is the cursor.

I tried replace `indent-line-function` and `indent-region-function`, but it didn't work, that's why I made this issue. I don't know why it didn't work. I think the most intutive solution would be for `define-innermode` and `define-hostmode` to have an optional `:indent-function` slot.

**Comment by vspinu** [comment]
> sometimes it is desirable for sgml-indent-line to be called from lisp-mode:

Polymode's indentation should be able to handle this case okeishly I think. 

>  but it didn't work,

It does, but with a twist.

Either set it in the chunk-mode's :init-functions to replace only in the host or inner modes. For example:

```el
(define-innermode poly-xyz-innermode
  ...
  :init-functions '((lambda (_)
                      (setq-local indent-line-function ' lisp-indent-line))))
```

or in polymode's hook to set it for both host and innermodes

```el
(add-hook 'poly-xyz-hook (lambda ()
                               (setq-local indent-line-function ' lisp-indent-line)))
```

Now, the second option works slightly unexpectedly. In host modes you will see lisp-indent-line mode as value of indent-line-function, but in innermodes it will still be `pm-indent-line-dispatcher`, but it will delegate to `pm--indent-line-function-original` eventually which is set to `lisp-indent-line` in the above example. 

The reason for this is that the polymode minor mode is actually run [just before](https://github.com/polymode/polymode/blob/2a61fb6d3e805bc0e4ca7b6510510a955c6bfb6a/polymode-methods.el#L103-L106) `pm--common-setup` where the indentation is initialized. I don't think I gave this one a due thought though. It certainly seems that polymode hook should be run after the setup.

**Comment by vspinu** [comment]
I have moved the hook to the end of inner mode initialization. Hopefully this won't break some other modes assumption.
