### ISSUE TITLE
exitting innermode

### ISSUE THREAD

**Issue by d9d6ka** [polymode/polymode#281]
Hello! Thank for the polymode, it helps me a lot!

I have a question whether I can exit the innermode to the hostmode.

To be more clear, I manage my Emacs config in org-mode tangling src-blocks. Tangling function is called automatically on save. But when the cursor is inside the src-block tangling fails. So it would be great to have an ability to exit the inner elisp-mode to the host org-mode without moving the cursor out of the src-block (as it starts annoying). Thanks!

**Comment by vspinu** [comment]
Do you want an interactive function for that, or you wonder how to do it programatically?  From what you described you need a programatic way of instructing auto-save to do it in the host buffer. 

There is a function `polymode-with-current-base-buffer` which is used to advice other functions to work inside the host mode. Just advice whatever function cannot work from the inner modes. See [examples](https://github.com/polymode/polymode/blob/b3871e946d278a256d95a3bd4615b1df234ad75a/polymode-core.el#L1434)

**Comment by d9d6ka** [comment]
I'm afraid, that the problem in the comment to the function `polymode-with-current-base-buffer` affects me as I try to use `org-babel-tangle` which maybe has something to do with moving points.

**Comment by Zaijab** [comment]
Aloha @d9d6ka,

You mention wanting to use `org-babel-tangle` as an `after-save-hook` in `org-mode` files. Here is a workaround.

```emacs-lisp
(defun tangler ()
  (interactive)
  (call-process-shell-command
   (concat "emacs -Q --batch --eval \"(require \'org)\" --eval \'(org-babel-tangle-file \""
	   (buffer-file-name (current-buffer))
	   "\")'")
   nil 0))

(add-hook 'org-mode-hook
          (lambda () (add-hook 'after-save-hook #'tangler nil 'local)))
```

Let me know if it works, I tested it on my end.

We may shorten it using a lambda but because we wish to call on `tangler` instead of `org-babel-tangle` I created it as an interactive function to call using `M-x`.
