### ISSUE TITLE
Needs some way to control major mode hooks in chunks upon interaction

### ISSUE THREAD

**Issue by wyuenho** [polymode/polymode#288]
Major mode hooks tend to consist mostly of formatters and linters and the like, all of which assume an actual file and some configuration files available. None of these things exist for multi modes like markdown, restructuredtext and sometimes even html. The consequence of running these derived inner mode hooks is spurious errors all over the place. Most of the time, people just want syntax highlighting in the chunks. Polymode needs to provide a way to determine whether the inner mode hooks should be run during definition.

**Comment by vspinu** [comment]
> Major mode hooks tend to consist mostly of formatters and linters and the like, all of which assume an actual file and some configuration files available

So you propose not to run them at all? I would say linters is an exception rather than the rule, everything else is a configuration that should be run. 

I would say it's up to the configuration of the linter to determine if it should run, and not the other way around. There is no way for polymode to detect that. Not running a mode hook is out of options I am afraid.

**Comment by wyuenho** [comment]
Linters and formatters are the rules rather than the exception, what else would you have in your mode hooks? Your settings go in custom-set-variables or use-package settings, and so do the key bindings.

There's also no easy way for these mode hooks to find out if they are being run by polymode. You want all 100s of packages out there like all those flycheck* lsp* company* packages to change to cater to polymode or the hundreds of thousands of emacs users to change their config to detect polymode in their mode hooks? How do you even do that?

**Comment by vspinu** [comment]
> Your settings go in custom-set-variables or use-package settings, and so do the key bindings.

No they are not. All my settings (and I bet for many others) go into hooks. 

> There's also no easy way for these mode hooks to find out if they are being run by polymode.

The polymode lives trace (like `pm-polymode` objects) intentionally for other modes to detect that. 

This is a generic problem. Linter and formaters developers are more than aware of the problem. So there should be a way to disable the linter or formatter if it does not understand or does not support a multi-mode file. 

What we can do on our side is to whitelist those variables for command use-cases like lsp and linters. If you have a list of variables that disable linters we can add them to polymode generically. The only issue is that if they suddenly start supporting polymodes and other multi-modes. 

> How do you even do that?
That you propose is even more problematic. People expect mode hooks to run. So what you propose is even more problematic. Every user would need to configure two hooks, one for polymode and one for major mode. It's not an option, sorry.

**Comment by wyuenho** [comment]
> Polymode needs to provide a way to determine whether the inner mode hooks should be run during definition.

This is what I proposed, not disable the major mode hook entirely by default.

> Every user would need to configure two hooks, one for polymode and one for major mode.

This is insane. autoinner-modes literally dynamically searches for modes from a whole bunch of sources to initialize, that means any user of polymode will have to reconfigure all of their programming language mode hooks to detect polymode. I for example have 10 different hooks on `js-mode-hook`, most of which will throw errors under polymode. If I were to reconfigure the hooks, I'd have to turn off the global minor modes and conditionally turn them on depending on some internal private guts of polymode that's barely documented. What's worse, there's not even any hooks for autoinner-mode activation, so I don't even know what you mean by "two hooks".

There is no interception point anywhere in polymode to allow the user to determine whether they should turn on some minor modes.

**Comment by vspinu** [comment]
> > Polymode needs to provide a way to determine whether the inner mode hooks should be run during definition.
> This is what I proposed, not disable the major mode hook entirely by default.

That statement is not clear. If you could elaborate in more concrete terms what you want maybe the discussion can become a bit more constructive. 

>  depending on some internal private guts of polymode 

It's not internal, and [documented](https://github.com/polymode/polymode/blob/9367c27e4eaa9e65cf02bb8c4f1e78620240e286/polymode-core.el#L48-L49)

> here's not even any hooks for autoinner-mode activation, so I don't even know what you mean by "two hooks".

[global hooks](https://github.com/polymode/polymode/blob/7d0c30c2a9f9c32a13d19299f1c2cf1f1a619da8/polymode-core.el#L206-L219)
[chunk level hooks](https://github.com/polymode/polymode/blob/7d0c30c2a9f9c32a13d19299f1c2cf1f1a619da8/polymode-classes.el#L309-L320)

> There is no interception point anywhere in polymode to allow the user to determine whether they should turn on some minor modes.

Can you try to re-formulate this? Please be concrete. What is "interception"?  Which some  in "turn on some minor modes"?  Minor mode or hooks? How exactly you want to achieve this, per inner mode (say python in markdown) or per entire host major mode (markdown), or a combination?

**Comment by wyuenho** [comment]
> It's not internal, and documented

You said `pm/poly-mode`, not you are pointing me to `polymode-mode`, which one should I use? Are there examples on how to use it?

> global hooks
> chunk level hooks

I need a polymode hook when it switches from head to body, but *before* it runs the major mode hooks. I'll need access within this new hook to the new indirect-buffer as well, so I can make a local hook out of the major mode hook, and examine all the hooks attached to the global major mode hook, then decide whether I should put them into the buffer local hook, so polymode can turn them on later.

**Comment by vspinu** [comment]
> You said pm/poly-mode, now you are pointing me to polymode-mode, which one should I use? 

I just misremembered, polymode-mode should be used. 

> I need a polymode hook when it switches from head to body, but before it runs the major mode hooks. 

There are switch hooks https://github.com/polymode/polymode/blob/7d0c30c2a9f9c32a13d19299f1c2cf1f1a619da8/polymode-core.el#L190-L219 but those are triggered each time the point moves to a different span. It's probably not what you need. 

> so I can make a local hook out of the major mode hook, 

How do you see this happening? The mode will install itself, and you get to execute your local hook before the other hooks? You can try to install your own hook into the major mode hook and modify itself, though ti's weird and might not work. 

The initialization of both host and inner modes happens [here](https://github.com/polymode/polymode/blob/7d0c30c2a9f9c32a13d19299f1c2cf1f1a619da8/polymode-methods.el#L144-L150) at this moment we don't even know which mode this is or which hook it will be running. So, if I understand you correctly, it's would be hard to do what you want from polymode because everything happens inside the emacs mode proper.

**Comment by wyuenho** [comment]
Looks like I have to attach a hook to `change-major-mode-after-body-hook`. It would be nice if `polymode` could offer some helpers to help with that, so I can write something like:

```elisp
(add-hook 'python-mode-hook
  (polymode-disable-in-polymode 'lsp-deferred)))
```

`polymode-disable-in-polymode` would remove `lsp-deferred` from the local hook when `polymode-mode` is `t`.

**Comment by vspinu** [comment]
> Looks like I have to attach a hook to change-major-mode-after-body-hook

Looks promising. How about a list of such hooks `polymode-disabled-hooks`. Also I am thinking about `polymode-disabled-minor-modes` which will contain minor modes which should not be run in polymode buffers.  Polymode could check for the minor-mode presense and disable it after the instalation. Not sure if there is a better way.

**Comment by wyuenho** [comment]
> How about a list of such hooks polymode-disabled-hooks. Also I am thinking about polymode-disabled-minor-modes which will contain minor modes which should not be run in polymode buffers.

No. This is premature optimization. User hooks can have a lot of code before and after toggling a minor mode, some of these code would not be preferable if the minor mode was turned off by something else silently without telling the user.

As I've said, all you need to do is

1. Add a polymode function to `change-major-mode-after-body-hook` to put every major mode hook buffer-local when polymode is active.
2. A  `polymode-disable-in-polymode` utility function that will arrange for the given function to be removed from the buffer-local hook when polymode is active.

**Comment by vspinu** [comment]
The proposed solution is not generic. People (myself included) often create wrapper functions where they put all the initialization and hook those new functions into major mode. 

Major mode hooks should be running at the end, after all the other polymode hooks. I tried it but it didn't work due to how font-lock is initialized in polymode. To be done. 

For now you can just addvice the functions. See `polymode-inhibit-in-indirect-buffers`. I think that's a generic solution.
