### ISSUE TITLE
polymode-eval- functions don't work in rmarkdown chunks

### ISSUE THREAD

**Issue by ghowoo** [polymode/polymode#291]
In rmarkdown chunks, when I evoke functions, such as polymode-eval-buffer, or polymode-eval-buffer-from-beg-to-point, the functions don't work. And it shows that:

none of the inner spans have "polymode-eval-buffer" defined

But other functions work well, such as polymode-next-chunk, polymode-previous-chunk.

These functions used to work well until recently I modified my init a little bit, but I have no idea where is the problem. Here is my init:

    (use-package ess
      :ensure t
      :pin melpa
      :init (require 'ess-site)
    )

    ;; Polymode and Poly-markdown

    (use-package poly-R
      :ensure t)
    (use-package poly-markdown
      :ensure t)
    (use-package poly-noweb
      :ensure t)

    (use-package polymode
      :ensure t
      :after (poly-markdown poly-R poly-noweb)
      :init
      (require 'polymode-core)
      :mode
      ("\\.Rmd" . poly-markdown+r-mode)
      ("\\.md" . poly-markdown-mode)
      ("\\.Snw" . poly-noweb+r-mode)
      ("\\.Rnw" . poly-noweb+r-mode)
      )

**Comment by ghowoo** [comment]
It seems that within the rmarkdown r chunk, the mode honors ESS instead of polymode. So, the function ess-eval-buffer-from-beg-to-point works. The polymode-eval functions used to work. I just don't know when and where changes happened.

**Comment by ghowoo** [comment]
polymode-eval- functions donot work. It sends a message:
None of the inner spans have 'polymode-eval-region-function' defined

**Comment by rmcd1024** [comment]
Same issue here, it suddenly stopped working. I think this may have coincided with pulling the latest polymode from elpa.

**Comment by rmcd1024** [comment]
It seems to be working correctly again after installing polymode-20220118.2310

**Comment by ghowoo** [comment]
Yes. It works now.
