### ISSUE TITLE
polymode-core failed to compiled with native-compilation

### ISSUE THREAD

**Issue by kiennq** [polymode/polymode#293]
The error is something like
> Warning (comp): ....../polymode-core.el: Error: Invalid function #\<subr or\>

**Comment by kiennq** [comment]
Might relate to #285, however without the byte-compile problem. This is a warning in native compiling and the polymode-core...eln` file is not produced.

**Comment by vincentarelbundock** [comment]
FWIW, I am running into the same issue on a MacOS Big Sur and on an Ubuntu 20.04 running under Windows10-WSL2.

I pulled from the emacs repo today and compiled by following the "From source" instructions on EmacsWiki: https://www.emacswiki.org/emacs/GccEmacs
