### ISSUE TITLE
Point moves when saving within a code chunk.

### ISSUE THREAD

**Issue by sje30** [polymode/polymode#295]
hi Vitalie, I appreciate this is going to be difficult to reproduce, so maybe if you think of somewhere for me to start tracing this, that would be a great help.  At the weekend I upgraded to Emacs 28.0.50 (master) together with updates from MELPA.  Since then, if my point is within a code chunk, when I save the buffer, the point moves to some other part of the buffer!  Is there any hook that polymode uses when saving a buffer?  I've not witnessed this behaviour other than in .Rmd buffers so far (and it doesn't happen if I'm not in a code chunk, which is what made me suspicious.)

Apologies if this sounds too vague to debug.

**Comment by vspinu** [comment]
I can reproduce this when I have `  (eval . (add-hook 'before-save-hook 'delete-trailing-whitespace nil t))` in dir locals. 

Last time I tried to hunt this I failed. Have to give it another try.

**Comment by fernandomayer** [comment]
I'm having the same exact issue in Emacs 27.2, and the problem occurs only in Rmd code chunks.

**Comment by sje30** [comment]
thanks both. (Vitalie: before-save-hook is nil for me, and yet I see this.)

**Comment by Jehops** [comment]
Also seeing this with `.Rnw` code chunks running Emacs from a recent commit from the master branch (3b32d05).

An unexpected positive outcome is that I've been reminded how useful it can be to save the point position in registers.

**Comment by rdiaz02** [comment]
I am also seeing this with `.Rnw` code chunks, where, on saving, if point is inside a chunk, point is taken to the last chunk of the buffer. I am using `polymode-20210521.1131` and Emacs 28.0.50 (though from the pgtk-nativecomp branch at  https://github.com/flatwhatson/emacs.git, commit 7b62cf ).

**Comment by vspinu** [comment]
I think I tracked this one down. At least in my case. Could you please confirm that the problem is gone on your side?

**Comment by Jehops** [comment]
A quick test passes.  Thank you!

**Comment by sje30** [comment]
Thanks Vitalie; a quick test here couldn't get point jumping on save this time.  will watch it.

**Comment by fernandomayer** [comment]
Same here. Apparently it's fixed, but will keep watching. Thanks!

**Comment by rdiaz02** [comment]
Thanks Vitalie: it also seems to be working here.
