### ISSUE TITLE
Feature - Support ```{.language .other-class } ... ``` language tag syntax in Markdown

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [polymode/polymode#296]
Hello,

Currently `polymode` supports only the ` ```language ... ``` ` language tag syntax to switch to the appropriate major mode for the `language`.

Pandoc markdown supports addition of HTML classes to a code block with the following syntax ` ```{.language .numbered} ... ``` `, which causes `polymode` to fall back to markdown major mode instead of switching to the appropriate `language` major mode.

Could you, please, extend `polymode` to support the Pandod markdown language class syntax?

Thank you!

**Comment by vspinu** [comment]
The `{mode xyz}` syntax is already supported.  The issue was `.` in front of the class.

**Comment by volodymyrprokopyuk** [comment]
Hi,

The `.` dot is actually the point of the issue (name the `language` of a chunck with a `.language` class), not a typo.

When using ` ```{latext .numberLInes} ... ``` ` which is supported by `polymode` with correct `latex` highlighting in `emacs`, `knitr` reports the error of ``Unknown language engine `latex` ``.

When using the new requested language class syntax to be supported by `polymode` ` ```{.latext .numberLInes} ... ``` `, `knitr` forwards correctly the results to `pandoc` which correctly does syntax highlighting of the `latex` code. The only issue with this new syntax is that in `emacs` the code chunk is not highlighted as `latex`, because the language class syntax is not currently supported by `polymode`.
