### ISSUE TITLE
Question: How to let tail-matcher match closing bracket?

### ISSUE THREAD

**Issue by bk138** [polymode/polymode#306]
I'm pretty sure this is a bit of a noob question, so please accept my excuses in advance.

What I'd like to achieve is to match on block like 
```
html! {
{} // opening and closing brackets in there as well
}
```
where the head is easily matched by `html\!.*{` for instance, but my lisp skills are clearly lacking when it comes to matching the last bracket closing the very first one. This can very probably be done through some function, but I couldn't find any similar tail-matchers in any of the modes in https://github.com/polymode. Any help on this greatly appreciated!

**Comment by vspinu** [comment]
All you have to do is to call `forward-sexp` from your `tail-matcher`.  Something like this:

```el
(defun my-tail-matcher (arg)
  (backward-char)
  (forward-sexp)
  (cons (1- (point)) (point)))
```

**Comment by bk138** [comment]
Ah, ok, this looks at the last character of the head match and then moves over the balanced expression?  Works for me, thanks a lot!

**Comment by vspinu** [comment]
> this looks at the last character of the head match and then moves over the balanced expression?

precisely

**Comment by vspinu** [comment]
I just pushed a new function `pm-forward-sexp-tail-matcher` that does exactly this matching. It's a common requirement. Feel free to use.
