### ISSUE TITLE
unable to install manually

### ISSUE THREAD

**Issue by xvtstephen** [polymode/polymode#312]
I saved the unzipped folder and then put

```
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'load-path "C:/emacs/emacs-26.3/site-lisp/markdown-mode")
(setq load-path
      (append '("C:/emacs/emacs-26.3/site-lisp/polymode/" "C:/emacs/emacs-26.3/site-lisp/poly-markdown/"
	"C:/emacs/emacs-26.3/site-lisp/poly-R/"	)
              load-path))

(require 'poly-markdown)
(require 'poly-R)

```
in my .emacs. I get
```
../../emacs-26.3/site-lisp/polymode/polymode-classes.el: ‘eieio-object-name-string’ is an obsolete generic function (as of 25.1); use ‘eieio-named’ instead.
```
which breaks my .emacs and lines below which used to work are not evaluated. I do this because I am behind a firewall on windows and setting the proxy did not work for me. I used to be able to install downloaded files from Melpa, but this does not work after the switch to Github. I have a question on stackoverfow on this:
https://stackoverflow.com/questions/71024293/how-can-i-install-package-from-a-downloaded-zip

**Comment by xvtstephen** [comment]
the complaint about eieio is not crucial. I was able to load the file by including poly-noweb on the load path. it seems to be expecting that even though I never required noweb.

**Comment by vspinu** [comment]
Happy you could solve it!

> it seems to be expecting that even though I never required noweb.

poly-R does require poly-noweb because of the knitr/sweave support.
