### ISSUE TITLE
Hide implementation buffers from buffer switching

### ISSUE THREAD

**Issue by doublep** [polymode/polymode#34]
I use Ido for buffer switching. If I open a file with my self-defined multimode, Ido shows three buffers for that file:
- file.jsp
- file.jsp[js]
- file.jsp[fundamental]

This makes switching to other buffers with similar name more complicated, because minibuffer is full of stuff I don't care about (i.e. when typing 'fi' I don't want to see 'file.jsp[js]' or 'file.jsp[fundamental] because it is implementation details, instead I'd like to see 'file2.jsp', for example).

I'm not sure if it is possible to generally hide buffers from Ido or other buffer switching at all. If it is not possible at the moment, it would help to at least _name_ them in such a way I would not see them.

**Comment by ashiklom** [comment]
Loosely related, but I am currently using a function like this to kill all polymode buffers for the current buffer (useful when switching to plain `markdown-mode`). Perhaps a similar approach can be used as advice (?) for the buffer list.

```emacs-lisp
(defun ans/kill-polymode-buffers ()
  "List all polymode implementation buffers."
  (interactive)
  (let* ((b (buffer-name))
         (pattern (concat b "\\[.+\\]"))
         (matched-buffers (-filter (lambda (buf) (s-matches? pattern (buffer-name buf))) (buffer-list)))
         (n-matched (length matched-buffers)))
    (-map #'kill-buffer matched-buffers)
    (message "Killed %d polymode buffers." n-matched)))
```

**Comment by srnnkls** [comment]
If you, like me, do use `ivy-switch-buffer` and friends you can go bruteforce with this regex:

```
(add-to-list 'ivy-ignore-buffers "\\[.+\\]")
```

**Comment by mavit** [comment]
We can make that regular expression a little bit tighter, since the part in square brackets is always at the end of the buffer name.

```emacs-lisp
(add-to-list 'ivy-ignore-buffers "\\[.+\\]\\'")
```

**Comment by srnnkls** [comment]
Good one. Just out of curiosity:

Is it more appropriate to use `\'` than `$` here?

**Comment by mavit** [comment]
Marginally.  The following is a valid (if foolish) buffer name, since buffer names can contain newlines:

```
foo[bar]
baz
```
