### ISSUE TITLE
General polymode documentation

### ISSUE THREAD

**Issue by basille** [polymode/polymode#35]
I've been using polymode for a while now, with great pleasure!

However, there are a few things that do not behave exactly as I wish, and I feel like it's mostly because I don't understand them, and how to tweak them. I was thus wondering whether there existed some detailed documentation on how to customize functions such as `polymode-weave` or `polymode-export`?

For instance, `polymode-weave` currently weave a file `toto.Rmd` into `toto[weaved].md`, and I'd like it to be simply `toto.md`. And I'm still unsure how to use `polymode-export` at all... 

Thank you!
Mathieu.

**Comment by vspinu** [comment]
The docs are now in a much better shape at https://polymode.github.io. The  technical details are still missing because a few things a still molted but all things which I deem stable are added there.
