### ISSUE TITLE
May you please create a tag for release?

### ISSUE THREAD

**Issue by grettke** [polymode/polymode#48]
Good evening,

Tonight I am writing to humbly put in a request for you to tag this project.

The reason is that a lot of users want to rely on the most "stable" release, by
the most broad definition of the term. For me, it is really simple, I am setting
up a "stable" Emacs configuration of my system here https://github.com/grettke/home/blob/master/.emacs.el
and I would like to rely 100% upon MELPA Stable http://stable.melpa.org/#/ .

I've used your package for a long time, love it, and so do many, many others.
This is a way to get that project out to the other thousands and thousands of
users who also rely upon MELPA stable.

All it takes is for you to create a tag, and within hours, it will show up on
MELPA stable.

Can't wait to hear about what you think and whether or not a tag is in this
project's future!

Kind regards,

Grant Rettke

P.S.

I use polymode for R knitr stuff, and it is sweet. It is usable now and it would be great even to
have a 0.000000N release, whatever makes sense to you. Making it available to folks on stable,
will open the door to many, many others.

**Comment by mdorman** [comment]
I would echo this---it doesn't have to be perfect, but it at least represents something someone else's package could, for instance, depend upon.

Maybe for the first one, like Grant said, just choose 0.0.0 and tag whatever's current, and then when there are pauses in development, just increment.

**Comment by vspinu** [comment]
I am actually very close to a refactored stable release ([next](https://github.com/vspinu/polymode/tree/next) branch). I don't think starting tagging this master branch is a good idea because it will surely create dependency confusion.

**Comment by vspinu** [comment]
The repo is tagged now but I would recommend using the master (MELPA) for time being as issues are fixed on a daily basis right now.
