### ISSUE TITLE
Mode change in polymode buffer triggers error

### ISSUE THREAD

**Issue by nrnrnr** [polymode/polymode#57]
Because of errors in polymode, I ran `fundamental-mode` in a buffer in which a polymode mode had been run. Now the buffer is somewhat in fundamental mode, but I keep getting this error:

```
polymode error: Method pm-select-buffer called on nil
```

**Comment by vspinu** [comment]
It's because `post-command-hook` is not cleaned on mode-change. Will need to add `chnage-major-mode-hook`.

Thanks for reporting this. I know it's a huge pain for you, but it's really helpful for the project. I am starting looking at it again. In the following months I will have loads of time for `polymode`, so everyhing will be fixed soon.

**Comment by nrnrnr** [comment]
@vspinu I'm so happy to hear of your availability and plans.  I have launched what is going to be an intensive effort that is going to involve lots of editing literate programs.  I would like to discuss with you the possibility of creating new polymodes dynamically based on buffer-local variables.  I think I can do most of the coding.  But it might be easier to do by email.  My email address is nr@cs.tufts.edu.

**Comment by vspinu** [comment]
>  I would like to discuss with you the possibility of creating new polymodes dynamically based on buffer-local variables. I

That sounds unusual :) I would be happy to discuss new features.  But the priority right now is to clean up all the issues with the existing functinality, even if that would mean abandoning indirect buffers altogether.

**Comment by nrnrnr** [comment]
> >  I would like to discuss with you the possibility of creating new
 > >  polymodes dynamically based on buffer-local variables. I
 > 
 > That sounds unusual :) I would be happy to discuss new features.  But the
 > priority right now is to clean up all the issues with the existing
 > functinality, even if that would mean abandoning indirect buffers
 > altogether.

Sounds good.  I will be happy to beta test.


Norman

**Comment by vspinu** [comment]
Hi Norman, 

I has been a while but I finally found time to rewrite polymode. `poly-noweb` now lives in its own [repo](https://github.com/polymode/poly-noweb). You can just pull the package from MELPA and start using it right away with `.nw` files. The errors should no longer be there and poly-noweb now implements things like nested code chunks, automatic mode detection and buffer local variables for the default mode (the noweb-mode specific `noweb-code-mode` is also recognized). 

I would appreciate if you could give it a go.

**Comment by nrnrnr** [comment]
Unfortunately I have some serious family medical stuff going on.  I will hope to be able to try this out in January, but it might not actually happen until next May.
