### ISSUE TITLE
Poly-mode for noweb with automatic inner mode

### ISSUE THREAD

**Issue by romildo** [polymode/polymode#65]
Please, write a poly-mode for editing `noweb` outer LaTeX with automatic inner mode detection.

**Comment by romildo** [comment]
First of all there should be a way of detecting the inner mode based on code chunks. I do not know a good solution for this. Maybe `noweb` could be extended to allow specifying the language of a code chunk. This would be appreciated in other circumstances too, like automatically pretty printing the code.

Until this happens, maybe a possible file extension in the chunk name can be used to indicate the inner mode.

**Comment by vspinu** [comment]
It has been ages but new poly-noweb is out [there](https://github.com/polymode/poly-noweb) with several options for automatic chunks.
