### ISSUE TITLE
polynode for inline R code?

### ISSUE THREAD

**Issue by biocyberman** [polymode/polymode#71]
I use ESS package and polymode with latest version installed from MELPA. Code is regconized correctly in code chunks, but whenever the cursor is in inline code, emacs modeline switches to "Markdown" instead of ESS. Consequently R code autocompletion doesnot work there. Is this something normal?

**Comment by vspinu** [comment]
What do you mean by inline code mardown? Code between ``?

**Comment by biocyberman** [comment]
Yes. That's what i mean. How could i not give a simple example about it before.

**Comment by kleinschmidt** [comment]
RMarkdown/knitr interprets inline code chunks with an `r` immediately after the opening backtick (like ``r``) as R code. Regular inline code (without the `r`) isn't evaluated.

**Comment by vspinu** [comment]
How about `{r} x<-1`? Can inline chunks span multiple lines? If so then inline markdown spans seem to be just like normal ones.

**Comment by kleinschmidt** [comment]
It looks like it has to be exactly `` `r ...` ``, with no line breaks. This input:

```
Inline `r (x <- 1)`.

With brackets `{r} x`.

Multiline inline `r
x
`.
```

produces this output:

```
Inline 1.

With brackets `{r} x`.

Multiline inline `r
x
`.
```

Only the first one is actually interpreted as R code.

**Comment by vspinu** [comment]
This is now implemented in the [next](https://github.com/vspinu/polymode/tree/next) branch, but I am not sure when I will be able to merge it into master. It's a major structural refactoring and simplification. Use on your own risk for now.
