### ISSUE TITLE
State is lost from one host chunk to the next

### ISSUE THREAD

**Issue by mavit** [polymode/polymode#75]
A span of the host mode does not carry on from where the previous span left off.

In the following example, the second `"` should end the string started by the first `"`, but under `poly-html-erb-mode` it is treated as starting a new string:

``` html
<div class="<%= @foo %>">
  Everything here should be treated as HTML, but with polymode is
  treated as if it's one big string.
</div>
```

I'm not sure whether this is a bug, or whether it's fundamental to the way that polymode works?

**Comment by vspinu** [comment]
This is probably a bug due to the simmetry of  the string delimiters. If I am not mistaken  @siassaj who implemented `poly-erb`, pointed this problem before.

**Comment by tim-teufel** [comment]
Still no solution/workaround? :worried: 
This bug screws up all the syntax highlighting in my template files.
I enjoy Polymode very much (in other modes). Perhaps, I should find some time to look into this issue.

**Comment by vspinu** [comment]
Sorry about that. This one is probably not very difficult to fix. The main problem is that I have started a rewrite of polymode some months ago and the code now is so different that there is not much point in fixing this old version.  I will do my best to merge it this week and then will have look at this issue.

**Comment by tim-teufel** [comment]
Happy to hear that! Keeping an eye on this project.

**Comment by vspinu** [comment]
I have just merged a major polymode rewrite. Taking the issues one by one now.

Could you please provide comprehensive examples of erb files (html, coffescript and js). It's not very clear to me what are the possibilities of the erb chunk. Is it always inside a string quote?

Thanks.

**Comment by tim-teufel** [comment]
> Is it always inside a string quote?

Not at all. The standard ERB chunk's _outermost_ borders are only `<` and `>` and the chunk may appear at any position of a document; not that there is complex grammar here.

> Could you please provide comprehensive examples of erb files (html, coffescript and js).

I don't think host modes matter in this case. [Web-mode](https://github.com/fxbois/web-mode) has [a good example](https://github.com/fxbois/web-mode/blob/master/tests/demo.erb) of HTML ERB. Also, there are JS ERB and CSS ERB among its [tests](https://github.com/fxbois/web-mode/tree/master/tests), but the first example looks more comprehensive and sufficient.

> It's not very clear to me what are the possibilities of the erb chunk.

If you mean the various types of the ERB chunk, then [this SO discussion](http://stackoverflow.com/questions/7996695/what-is-the-difference-between-and-in-erb-in-rails) may help. And if you want some quick introduction to ERB template syntax, I've found [this article](https://docs.puppetlabs.com/puppet/latest/reference/lang_template_erb.html) clearly written, but note that ERB itself is explained in two first chapters only.

**Comment by vspinu** [comment]
Thanks @tim-teufel for all the pointers. That's exactly what I was looking for.

**Comment by tim-teufel** [comment]
Should the issue be reopened not to forget about it?

**Comment by vspinu** [comment]
What do you mean? The issue has been fixed. HTML chunks are not highlighted in string face anymore.

**Comment by tim-teufel** [comment]
OK. I will explain my concern soon, when occasion serves. :hourglass:

**Comment by mavit** [comment]
I'm afraid that my example test case was over-simplified, and that only a special case has been fixed.  Consider the following slightly more complicated example:

```lang=html
<div class="foo <%= @bar %> baz">
  Everything here should be treated as HTML, but with polymode is
  treated as if it's one big string.
</div>
```

**Comment by vspinu** [comment]
So erb chunks could be anywhere then, even in a multi-line strings. This is definitely tricky. I will think about it.

**Comment by vspinu** [comment]
Hi folks. It has been a while and I don't know if you are still interested, but this and many other issues have been fixed after the rewrite. poly-erb and poly-slim now live in their own dedicated repositories.

**Comment by mavit** [comment]
Splendid!  I was able to use the new improved polymode to get my [poly mode for Ansible](https://gitlab.com/mavit/poly-ansible) working.
