### ISSUE TITLE
`find-alternate-file` fails because of the incorrect behavior of the  `get-file-buffer` 

### ISSUE THREAD

**Issue by vspinu** [polymode/polymode#79]
`C-x C-v` doesnt' work with polymodes. I traked it down to `get-file-buffer`. 

If you `(setq buffer-file-name nil)` as `find-alternate-file` does internally, `(get-file-buffer "old-filename.rmd")` still returns a buffer.

That is, the following should return nil but does not in polymode buffers. 

```
(let ((oname buffer-file-name))
  (setq buffer-file-name nil)
  (get-file-buffer oname))
```

It works in cloned indirect buffers though. This is very puzzling :(

**Comment by naphthalene** [comment]
:( getting bit by this as well. Polymode works great otherwise though! I do have one issue that i'll open a ticket for, regarding indentation
