### ISSUE TITLE
Autoloads

### ISSUE THREAD

**Issue by Pitometsu** [polymode/polymode#81]
Could you, please, add autoloads for:

``` elisp
(progn
   (autoload 'poly-slim-mode "poly-slim")
   (autoload 'poly-javascript-erb-mode "poly-erb")
   (autoload 'poly-coffee-erb-mode "poly-erb")
   (autoload 'poly-html-erb-mode "poly-erb"))
```

**Comment by vspinu** [comment]
Thanks. I will do that. Are you sure these are the only ones needed?

**Comment by Pitometsu** [comment]
Perhaps it will be better to have autoloads for all poly modes, I personally just use this only, thanks!

**Comment by Pitometsu** [comment]
For markdown there already exist, for example.

**Comment by vspinu** [comment]
That's right. I need to extract all these polymodes in separate packages such that they can freely require necessary packages.

**Comment by vspinu** [comment]
Fixed. poly-slim and poly-erb live in dedicated repositories after the rewrite.
