### ISSUE TITLE
Suggestion for enhancement : support ESS's "eval-chunk" in poly-markdown+poly-R

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [polymode/polymode#94]
Dear Vitali,

While editing a .Rnw" file mixing \LaTeX and R code, it is **extremely** handy to evaluate an R chunk with ESS's "eval chunk" (bound to M-n C-M-x by default). (I am not sure whic emacs package suppotr this feature...).

This functionality does not (yet) seems to be implemented when editing a .Rmd file mixing markdown and R chunks ; it would however be as damnably useful in such a .Rmd buffer as it is in a .Rnw buffer.

**Comment by vspinu** [comment]
Thanks. I will add that soon, as well as eval-all-chunks. 

I am not yet sure if this should be a generic polymode functionality of R/ESS specific.

**Comment by jabranham** [comment]
eval-all-chunks would definitely be appreciated. Is it possible to get something like ESS's eval-buffer-from-top-to-here (`C-c <up>`) as well?

**Comment by yamad** [comment]
I'd really like `eval-all-chunks`. Any progress? I might also try to implement if you haven't done much on this already.

**Comment by plijnzaad** [comment]
Seconded, this would be a great addition

**Comment by yamad** [comment]
For the record, I have implemented eval-chunk, eval-all-chunks, and so on in pull request https://github.com/vspinu/polymode/pull/129 . Feedback welcome.

(I am not sure subscribers to this issue are notified when the issue is mentioned in a pull request. Sorry for the noise if so)
